### ISSUE TITLE
CET : Calcul de fin de cycle erroné

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#1004]
Version 1.45.3
avec `use_card_reader_to_validate_shifts:` false

La régularisation de fin de cycle d'un utilisateur ayant fait 2 créneaux lors du cycle actuel nous semble erronée

Compteurs **avant** régularisation 
<html>
<body>

TOTAL TEMPS | TOTAL CYCLE EN COURS | TOTAL EPARGNE
-- | -- | --
6h00 | 6h00 | 0h00

</body>
</html>
Compteurs après régularisation (en 1.45.3)
<html>
<body>

TOTAL TEMPS | TOTAL CYCLE EN COURS | TOTAL EPARGNE
-- | -- | --
-3h00 | -3h00 | 6h00

</body>
</html>

Valeurs souhaitées : Les compteurs du  membre sont à zéro (il a fait le service requis) et son CET indique les 3 heures supplémentaires qu'il a effectué
<html>
<body>

TOTAL TEMPS | TOTAL CYCLE EN COURS | TOTAL EPARGNE
-- | -- | --
0h00 | 0h00 | 3h00

</body>
</html>

**Comment by raphodn** [comment]
Arg :exploding_head: j'ai dû me tromper quelque part...

**Comment by raphodn** [comment]
vous avez quelles valeur pour `max_time_at_end_of_shift` ?

**Comment by ctmareil** [comment]
`max_time_at_end_of_shift:` 0

**Comment by raphodn** [comment]
Ok ! Tu peux m'expliquer les étapes que tu as effectué pour régulariser ? Simplement lancé la commande `CycleStartCommand` ? Avec des paramètres ? Tu sais combien de temps la commande a pris ?

**Comment by ctmareil** [comment]
Rien de particulier 
- création du user par un admin
- sélection par le user de 2 créneaux dans son cycle courant
- Fin de cycle avec régulation,...

![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/54461b29-c083-446c-89a8-9a7ee2262900)
et 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/d89a2657-4ad0-49dd-9363-40dfc003adeb)

J'ai également fait le test en prenant dans la base un user qui avait son cycle se finissant le lendemain. Il a pris des créneaux supplémentaires. La fin de cycle a eu lieu
et le résultat est le même. 
ps: je peux te donner accès en admin ou en user aux comptes- Dis moi

**Comment by raphodn** [comment]
En fait @petitalb c'est toujours cette histoire de $date je pense. J'avais mis arbitrairement +1 minute, mais c'est la même date pour tout le monde dans cette commande, donc pour certains ça ne suffit pas pour prendre en compte le log de début de cycle.

Il faut que je trouve une solution alternative (sûrement revenir au fonctionnement précédent justement).

**Comment by raphodn** [comment]
@ctmareil quand tu passes ta souris sur les dates des 3 premières lignes de ta capture d'écran, ca indique quelle heure/minute pour chacun ?

**Comment by ctmareil** [comment]
Première ligne
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/7706111e-d6de-40c3-9065-ffd2e9a033a0)
Deuxième ligne
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/176b408b-5153-4e69-aa55-7b7ffcfbc4b1)
Troisième ligne
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/90e5d8b6-8415-463f-bfe9-cb076dc8694e)

**Comment by raphodn** [comment]
Ok zut il va me falloir l'accès à ta base de données pour voir les secondes...

**Comment by raphodn** [comment]
Si tu veux/peux le faire sinon, t'as les id des timelog dans le code HTML (click droit > inspecter), puis un select * dans time_log

**Comment by ctmareil** [comment]
Je te fais ça demain matin

Cordialement
Christophe
0630679557

Le mar. 26 sept. 2023, 21:04, Raphael Odini ***@***.***> a
écrit :

**Comment by ctmareil** [comment]
Je peux te donner l accès

Cordialement
Christophe
0630679557

Le mar. 26 sept. 2023, 20:59, Raphael Odini ***@***.***> a
écrit :

**Comment by ctmareil** [comment]
Voilà la copie de la table time_log pour le user
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/73bbce01-cdb0-4e91-8c9a-44e00d3fa9bb)
[Time_log_user_544.csv](https://github.com/elefan-grenoble/gestion-compte/files/12731414/Time_log_user_544.csv)

**Comment by raphodn** [comment]
Y'a pas de milisecondes ? ^^
Via une requête SQL peut-être ?

En tout cas j'arrive à mes limites de compétences, je comprends pas pourquoi php / doctrine ne prend pas en compte le log -3 créé en premier...

**Comment by raphodn** [comment]
Une idée sinon serait de remplacer l'utilisation de `em->refresh()` par un `em->clear()` ?

**Comment by ctmareil** [comment]
Réponse à ton commentaire https://github.com/elefan-grenoble/gestion-compte/issues/1004#issuecomment-1736739686
C'est une requête SQL mais la colonne `created_at` de la table `time_log` est en format `datetime` pas `timestamp,` donc ne stocke pas les millisecondes

**Comment by raphodn** [comment]
J'ai ouvert une PR : https://github.com/elefan-grenoble/gestion-compte/pull/1010

est-ce que tu pourrais faire tourner ton système de test sur cette branche et me dire si ca fonctionne ? Je t'offre une bouteille si c'est le cas :)

**Comment by ctmareil** [comment]
Testé sur un user et ça n'a pas l'air top  :)
Zut ! j'ai pas gagné une bouteille 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/985b857d-0352-4494-9f58-a93b5376f39e)

**Comment by ctmareil** [comment]
et les 3 dernières actions ont toujours la même date et time
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/439479bb-e1b3-457c-9fe4-a233aa2cb998)

**Comment by raphodn** [comment]
l'enfer ce bug... j'essaie de trouver une nouvelle solution avant ce soir

**Comment by raphodn** [comment]
bon je crois (encore) avoir trouvé ! Il y a un peu plus de changements que la précédent tentative de solution, si tu veux re-tester cette nuit :pray: :pray: :champagne: 
(le seul risque, c'est qu'il y aura peut-être des erreurs collatérales)

**Comment by ctmareil** [comment]
OK je teste, mais c'est quoi les erreurs collatérales potentielles ?

**Comment by ctmareil** [comment]
Quid des 2 fichiers de la PR1010 d'hier ? Je les garde ou restore la version précédente ?

**Comment by raphodn** [comment]
En fait l'erreur se situait dans la date de création du log de temps. En creusant j'ai decouvert que la commande de début de cycle définit une date à minuit, alors que dans tes captures (et chez nous aussi) ils se retrouvent à 6h05.
Donc j'ai corrigé le fait de pouvoir définir une date arbitraire lors de la création du log de temps.
Mais comme c'est utilisé ailleurs, j'ai veillé à ce que tout fonctionne, mais j'ai peut-être oublié un truc..

**Comment by ctmareil** [comment]
Ca m'a l'air résolu! 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/e7b75986-1127-477a-864c-f807d6bf4aad)

**Comment by ctmareil** [comment]
> bon je crois (encore) avoir trouvé ! J'ai mis à jour la PR. Il y a un peu plus de changements que la précédent tentative de solution, si tu veux re-tester cette nuit 🙏 🙏 🍾 (le seul risque, c'est qu'il y aura peut-être des erreurs collatérales)

Une idée sur les potentielles erreurs collatérales ? Que faut-il vérifier dans les tests ?

**Comment by raphodn** [comment]
Les impacts ca serait sur toutes les autres actions qui générant un log de temps (inscription et désinscription à un créneau, log de temps manuel, etc). 
Je vais re-vérifier chez nous que tout fonctionne bien :)
