### ISSUE TITLE
Relance Créneau : Pb de pagination

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#1009]
Outre le  filtre bloqué (https://github.com/elefan-grenoble/gestion-compte/issues/982), il y a un autre problème sur la relance Créneau

Connexion en administrateur > Administration > Relance Créneau
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/8e8a1392-8d0a-4ff3-942a-9d953ccdbce7)
Passage à la deuxième page par l'option en bas de l'écran < 1 2 3 4 > : **Nouveau total de relance** 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/d5a51403-fcba-44fd-97ec-4f409995d526)
Retour à la page 1 : **le tri n'est plus respecté**
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/bb115ff7-a5b4-4d6f-84cb-99987e7bd7f4)

**Comment by ctmareil** [comment]
As tu reproduit le problème de pagination ?

**Comment by raphodn** [comment]
Non, quand j'ai testé je pouvais aller sur la page suivante sans soucis d'ordre ni d'affichage.

**Comment by ctmareil** [comment]
Après avoir installé le nouveau master, j'ai toujours le même problème 
Administration > Relance Créneau
`Liste des membres en retard de créneaux (**95**)`
page 2 
`Liste des membres en retard de créneaux (**121**)`
retour page 1 : les comptes à -1h30 ont disparus

**Comment by raphodn** [comment]
En fait la PR n'est pas encore mergée, donc il faut aller sur le lien plus haut pour récupérer la branche en question 😅

**Comment by ctmareil** [comment]
J'ai installé la PR. Le total reste maintenant constant (👍), le champ du filtre est modifiable (👍)
mais le tri est aléatoire avec les valeurs à -1h30
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/e9c23a5c-8d24-4223-bb8c-0826a43bd533)

Etonnant mais c'est peut-être du à notre base de tests si tu n'as pas le même pb.

**Comment by raphodn** [comment]
je confirme en local j'ai aussi un soucis d'ordre pour le dernier membre de la liste (page 3). je vais creuser :thinking: 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/7147385/e504f67f-9d44-4bbf-945b-db3a7a742042)

**Comment by raphodn** [comment]
ok trouvé : la requête SQL utilisée pour calculer le compteur temps ne prenais pas en compte le compteur épargne (il faut retirer les logs d'épargne)
