### ISSUE TITLE
Amélioration des e-mails de pré-réservation

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#1018]
Le message envoyé lors de la pré-réservation de créneau peut être amélioré
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/c33390dd-8872-4f53-b9c2-bf399fbf44e3)

[ESPACE-MEMBRES] pourrait être remplacé par le site_name du fichier parameters.yml
September : le mois dans l'objet est en anglais
`7 jours` : le nombre de jours dépends d'une variable dans le CRON (à POP on reserve le créneau pendant 3 jours)

![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/f4aaddd9-c04e-4dc6-9751-6a9bd34de5a4)

**Comment by raphodn** [comment]
Le template utilisé : https://github.com/elefan-grenoble/gestion-compte/blob/master/app/Resources/views/emails/shift_reserved.html.twig

Et le bout de code qui gère l'envoi (et défini l'objet de l'e-mail) : https://github.com/elefan-grenoble/gestion-compte/blob/12390bae90017d8177deb0b0dfdebac66a988819/src/AppBundle/EventListener/EmailingEventListener.php#L231

Pour l'objet : actuellement tous les envois d'e-mails en lien avec les créneaux ont `[ESPACE MEMBRES]` comme prefix dans leur objet de mail... Un sujet qui pourrait être traité ici : #881

Pour le contenu, il faudrait en effet définir le paramètre ailleurs :thinking:

**Comment by raphodn** [comment]
J'ai mergée la PR #1034, qui rajoute un paramètre `reserve_new_shift_to_prior_shifter_delay` pour définir le délai à afficher dans le mail de pré-reservation. Ce délai est simplement indicatif, comme tu le sais c'est la commande `FreeReservedShiftsCommand` qui gère la libération des créneaux.

**Comment by raphodn** [comment]
Et je viens de merger la PR #1032 qui devrait corriger les erreurs de traduction (français par défaut)
