### ISSUE TITLE
erreur 500

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#102]
suppression de bénéficiaire (mdelmas2)
fusion de compte (Philippe Guéguen sur Christel Refour)
foreign key constraint fails

**Comment by janssens** [comment]
Compte à fusionner une fois résolu
https://lelefan.freshdesk.com/a/tickets/1032
https://lelefan.freshdesk.com/a/tickets/1098

**Comment by museOnSite** [comment]
Bénéficiaire à supprimer une fois résolu: Bénédicte LECLERC

**Comment by janssens** [comment]
fixed !
