### ISSUE TITLE
Code 500 sur le message d'acceptation d'une pré-réservation 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#1020]
Erreur 500 lorsque on clique sur J'ACCEPTE dans le message de reprise de créneau reçu ce matin pour un créneau effectué hier à partir d'un smartphone. 

Par contre, le refus fonctionne et à partir du moment où le refus a été effectué, quand on clique sur J'ACCEPTE, le lien renvoie vers POP service avec un beau message et il n'y a plus d'erreur 500

**Comment by raphodn** [comment]
ah c'est une fonctionnalité ancienne et plus utilisé chez nous, donc merci d'avoir testé en effet il doit y avoir une erreur quelque part. est-ce qu'il y a un message d'erreur ?

**Comment by ctmareil** [comment]
En recherchant dans la log il semble que ce soit ce message d'erreur 
[2023-09-30 09:32:02] php.CRITICAL: Type error: Argument 1 passed to AppBundle\Entity\Shift::setBooker() must be an instance of AppBundle\Entity\User or null, string given, called $
[2023-09-30 09:32:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\Shift::setB$

[issue1020.log](https://github.com/elefan-grenoble/gestion-compte/files/12774493/issue1020.log)

**Comment by raphodn** [comment]
Super merci pour la stacktrace. Je corrige ça ce soir ! 

Faudrait vraiment rajouter des tests dans cette application 😓

**Comment by raphodn** [comment]
Dans l'e-mail que tu as reçu, tu pourrais me donner l'url complet sur laquelle tu cliques ? Normalement il devrait y avoir un token, qui permet de savoir quel utilisateur souhaite reprendre le créneau (et ainsi le réinscrire)

**Comment by ctmareil** [comment]
Voilà  un exemple :
https://membres-formation.poplacoop.fr/shift/9011/accept?token=9ba9c25e7dfb4a23c34b8650950fa1c6

Cordialement
Christophe
0630679557

Le dim. 1 oct. 2023, 01:47, Raphael Odini ***@***.***> a
écrit :

**Comment by sebastienbianco** [comment]
Bonjour

Nous avons testé cette fonctionnalité mais nous ne l'avons pas retenu. En effet, nous avons trop de mal à boucler nos plannings pour se permettre d'être sélectif.

Bonne fin de journée

Sébastien

**Comment by ctmareil** [comment]
Ceux nouveaux exemples, si c'est nécessaire 

J’ai de nouveau l’erreur 500 sur 2 messages ce matin.
Je te donne les liens au cas où le lien de Pierre ne serait plus valable (délai de reservation écoulé)

Smartphone Android en premier,  Le magasin est fermé, J’ACCEPTE

 

`https://membres-formation.poplacoop.fr/shift/9034/accept?token=9f247cb937471fcd13e51096274b81ff`

`https://membres-formation.poplacoop.fr/shift/9033/accept?token=2a84c780365c46f63d76389acb1d7215`

 

Sabine

De : FORMATION Créneaux POP La Coop <no-reply.membres-formation@poplacoop.fr>
Envoyé : mercredi 4 octobre 2023 05:55
À : sjagot@xxxx.fr
Objet : [ESPACE MEMBRES] Reprends ton créneau du 03 October dans 27 jours

 

Bonjour Sabine,

Tu viens de réaliser un créneau à l'épicerie, merci de rendre possible notre projet.
Nous te proposons de reprendre le même créneau dans 27 jours, soit le mardi 31 octobre de 12h00 à 15h00.
Tu es prioritaire sur ce créneau pendant 7 jours, ensuite il deviendra disponible à la réservation pour les autres membres.

Merci de nous indiquer si tu souhaites le reprendre :
[J'accepte](https://membres-formation.poplacoop.fr/shift/9033/accept?token=2a84c780365c46f63d76389acb1d7215) [Je refuse](https://membres-formation.poplacoop.fr/shift/9033/reject?token=2a84c780365c46f63d76389acb1d7215)
Il n'est pas nécessaire de répondre à ce mail, sauf si tu as des questions.

Belle journée à toi.
Céleste, la petite fée des créneaux :)

**Comment by raphodn** [comment]
Merci pour les exemples. Je suis en vacances à partir d'aujourd'hui, je regarde ça à mon retour (dimanche).

Et si qqun passe par là et a une solution, il y a un début de PR d'ouverte pour info.

**Comment by ctmareil** [comment]
Suite à mon message sur Telegram:  sur le fix de l'issue 1020 (message de pré-réservation), as tu modifié le process d'envoi de message? Il semble qu'on ne reçoive plus le message de pré-reservation.   Je vais vérifier de notre coté mais il y a peut-être un pb

Je te joins le fichier log de ce matin. Il y a une erreur (la première ligne du fichier à 5h05 du matin (étrange)). Je ne suis pas sûrt que cela t'aide 
[log141023.log](https://github.com/elefan-grenoble/gestion-compte/files/12906211/log141023.log)

**Comment by raphodn** [comment]
Malheureusement ton fichier ne me donne pas d'indices... l'erreur dans ton fichier est surement un robot qui essaie de trouver une faille dans votre système (en essayant d'accéder `wp-login` (wordpress stuff))

**Comment by raphodn** [comment]
J'ai retesté `ShiftGenerateCommand` et j'ai detecté une typo, que je viens de corriger sur master ✅
