### ISSUE TITLE
Code 500 en dupliquant les créneaux d'un jour de la semaine tpye

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#1042]
En release 1.45.4, Erreur dans la duplication des créneaux d'un jour de la semaine type

Administration > Gérer la semaine type > Actions > Dupliquer des créneaux
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/0316db58-344c-4382-a25a-a25ef3f835dd)

Cliquez sur `Copier les Créneaux type`  => Erreur 500

Dans la log 
`[2023-10-21 10:30:01] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO period (day_of_week, start, end, created_at, updated_at, job_id, created_by_id, updated_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "16:30:00", "19:30:00", "-0001-11-30 00:00:00", "2023-10-21 10:30:01", 2, null, null]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '-0001-11-30 00:00:00' for column `gestion_compte_formation`.`period`.`created_at` at row 1" at /var/www/membres-formation.poplacoop.fr/gestion-compte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO period (day_of_week, start, end, created_at, updated_at, job_id, created_by_id, updated_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"16:30:00\", \"19:30:00\", \"-0001-11-30 00:00:00\", \"2023-10-21 10:30:01\", 2, null, null]:\n\nSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '-0001-11-30 00:00:00' for column `gestion_compte_formation`.`period`.`created_at` at row 1 at /var/www/membres-formation.poplacoop.fr/gestion-compte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '-0001-11-30 00:00:00' for column `gestion_compte_formation`.`period`.`created_at` at row 1 at /var/www/membres-formation.poplacoop.fr/gestion-compte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '-0001-11-30 00:00:00' for column `gestion_compte_formation`.`period`.`created_at` at row 1 at /var/www/membres-formation.poplacoop.fr/gestion-compte/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} {"user":"24 (#128 Christophe TOULEMONDE)"}
`

**Comment by raphodn** [comment]
Bien vu ! En creusant j'ai trouvé un autre bug sur la semaine type, je vais faire des améliorations.
