### ISSUE TITLE
Labels du message en cas de sous-effectif

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#105]
Aujourd'hui, j'ai fait l'ouverture et la fermeture. Et une bonne dizaine de personnes, que ce soit ce matin ou ce soir, se demandaient si le magasin serait ouvert ou fermé sur toute une série de créneaux. Ce soir, nous n'étions que deux, donc le message apparaissait en rouge, avec "fermeture". Toutes les personnes qui sont venues ont commencé par s'interroger sur l'heure de fermeture, et la bénévole avec moi m'a dit qu'elle s'était demandé si elle devait elle-même venir.
Même si ce n'est pas le label définitif, il me semble qu'il est urgent de le changer car "fermeture" apporte de la confusion et peut conduire des gens à ne pas venir au magasin.  Je vous suggère "alerte", mon préféré, ou "urgence". Après, je ne mesure pas ce que le changement de label implique pour le code. A vous de voir, vous êtes les juges en dernier ressort !

**Comment by museOnSite** [comment]
Encore un:
https://lelefan.freshdesk.com/a/tickets/1185

> J'essaye de trouver un créneau pour lequel je serai dispo mais pas mal sont grisés ou indiquent "Fermeture", exemple : vendredi 18 de 17h à 21h et samedi 19 9h30-12h30. Qu'est-ce que cela signifie ?

**Comment by janssens** [comment]
Je vais brainstormer et je vous code un truc ad hoc en vitesse.
