### ISSUE TITLE
Suppression de compte membre ne fonctionne pas

### ISSUE THREAD

**Issue by samueleyre** [elefan-grenoble/gestion-compte#1075]
La suppression d'un compte membre ne fonctionne pas. 

erreur : "Unrecognized field: created_at"

Testé à partir d'un compte superadmin avec la base rempli avec les fixtures.

**Comment by raphodn** [comment]
J'ai l'impression d'avoir déjà eu cette erreur..

Le champ `Membership.created_at` a été ajouté ici : #605
