### ISSUE TITLE
Suppression du Warning de dépassement de Quota

### ISSUE THREAD

**Issue by sebastienbianco** [elefan-grenoble/gestion-compte#1085]
Bonjour

Lorsque l'on souhaite réserver un créneau et que l'on va dépasser son quota d'heure, on reçoit le message suivant : 

![image](https://github.com/elefan-grenoble/gestion-compte/assets/26170232/8243e2d3-5a0f-4549-aa26-ddafcc0f1819)

Ce message nous semble contre-productif pour nos coopératives qui ont du mal à remplir leurs créneaux.

Est-il ce qu'il ne serait pas pertinent de supprimer ce message (ou de le tourner de faon plus positif en vert => Félicitation tu vas offrir bien plus de temps que requis pour ta coopérative. Confirme tu ta misanthropie ? ) ?

Bonne fin de journée

Sébastien (Scopéli)

**Comment by sebastienbianco** [comment]
De plus le message me semble faux car de ce que je constate, toutes les heures sont bien comptabilisé puis décomptées petit à petit le long des cycles...

**Comment by raphodn** [comment]
En effet je ne connaissais pas ce message, et il n'est pas très engageant ^^

Je me suis plongé dans le code, et les paramètres que vous avez (d'après un dump dans une autre issue), ainsi que les paramètres que nous avons nous. Le paramètre `max_time_in_advance_to_book_extra_shifts` joue un rôle ici. 
- chez nous c'est `max_time_in_advance_to_book_extra_shifts: null`
- chez vous c'est `max_time_in_advance_to_book_extra_shifts: '360 days'`

En mettant null vous n'aurez plus le message qui apparaitra :ok_hand:  

```
src/AppBundle/Service/ShiftService.php > canBookDuration
app/Resources/views/booking/_partial/modal.html.twig
```

**Comment by sebastienbianco** [comment]
Ca fonctionne effectivement très bien :)
Merci du tips !
