### ISSUE TITLE
Pérénnisation des bénévoles qualifiés sur des postes sans qualification

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#111]
Je ne sais pas exactement comment formuler la chose en des mots simples, je vous explique le "problème" : quand une personne avec une qualification s'inscrit sur un rôle non qualifié, et qu'elle confirme son créneau 4 semaines après, elle reste de facto sur un poste non qualifié. Et ce, même si la personne qui était qualifiée sur le créneau à T0 ne reprend pas son créneau à 28 jours. Je viens de basculer 3 personnes dans ce cas manuellement, je ne sais pas si c'est possible de le coder !

**Comment by janssens** [comment]
Tout le créneau horaire reçoit le mail de j28 en même temps, donc la ou les places qualifiées ne sont pas disponibles tant que les membres concernés n'ont pas répondu.
Idéalement il faudrait que si un place qualifié se libére, elle soit attribué au membre ayant cette qualification déjà inscrit. mais avec la conception actuelle ce n'est pas une opération simple.
Peut-être que l'opération la plus simple est de ne pas reserver le creneau et ne pas envoyer le message à j28 aux membres qualifié ayant effectué un créneau non qualifié ?
