### ISSUE TITLE
Automatiser le passage au statut de ressource

### ISSUE THREAD

**Issue by an-ca** [elefan-grenoble/gestion-compte#112]
Actuellement, on marque les personnes formées comme "Ressource" manuellement dans l'espace membre.
Cette action s'accompagne d'un email (avec liens mattermost, etc) aux personnes formées. Ce mail est envoyé manuellement également.

On pourrait imaginer créer une vue qui permette d'automatiser le processus. Sur cette vue, on sélectionnerait les personnes qui viennent d'être formées et le mail ainsi que le marquage comme ressource se ferait automatiquement.

**Comment by janssens** [comment]
:+1:

**Comment by symartin** [comment]
Le système de bénévole ressource n'est plus utilisé à l'éléfan, cette fonctionnalité ne sera donc pas développé dans un avenir proche
