### ISSUE TITLE
Espace membres : wording sur le tableau des tâches

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#118]
Est-ce qu'il serait possible de remplacer la mention "Personnes référentes" par "Contact" ou "Personne ressource" ? Cela afin que ce soit clair que toute personne membre de la commission ou du groupe peut être ressource sur une tâche, et pas que les référentes/référents.

**Comment by janssens** [comment]
Ok sur branch develop

**Comment by janssens** [comment]
ok prod
