### ISSUE TITLE
Correction d'une faute dans le message d'alerte qualification lors d'une réservation de créneau

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#119]
![image](https://user-images.githubusercontent.com/36693586/44134703-5101d47e-a066-11e8-9469-34b43d8f42b9.png)

"Ces compétences" plutôt que "Ses compétences". Je mettrais même "Tes compétences" puisque dans la suite de la phrase, on parle directement à la personne avec "Pense à les valoriser"

**Comment by janssens** [comment]
Ok sur branch develop

**Comment by janssens** [comment]
ok prod
