### ISSUE TITLE
Correction d'une faute sur le message de rappel de réservation dans l'espace membre

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#120]
![image](https://user-images.githubusercontent.com/36693586/44134908-0c445e82-a067-11e8-8bfa-cdc4a29e520e.png)

"Pense à réserver tes créneaux" plutôt que "penses à réserver tes créneaux"

**Comment by janssens** [comment]
Ok sur branch develop

**Comment by janssens** [comment]
ok prod
