### ISSUE TITLE
Gérer les non membre

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#126]
Possibilité de créer des utilisateurs non membre (sans adhésion) et non admin.
Actuellement les admins sont les seul non membre (member_number <=0 )
Les salariers ont besoin d'un accès espace membre mais pas nécessairement d'être admin.

**Comment by museOnSite** [comment]
Quel sorte d'actions pourront faire les non membres ?

**Comment by janssens** [comment]
Je vois plusieurs cas : 

1. le cas association. dont on a besoin de suivre l'adhésion/ré-adhésion, qui a besoin de recevoir les communication, mais qui ne fait pas son bénévolat. C'est un adhérent mais non participant.
On peux contourner en faisant un compte membre gelé, mais l'asso a besoin de faire ces courses... Il faudrait aussi pouvoir les identifier dans la liste.

2. les salariés.
Il veulent certain droits (voir les créneaux par exemple), recevoir les mails,... Avoir un badge "salarié".
Actuellement Charlotte est admin, mais c'est pas une solution très sécurisée.

3. Les producteurs ?

Si l'espace membre continu de développer un beau tableau de bord (nombre d'adhérent, chiffre d'affaire, dernier produits, ...)  l'accés doit être possible pour tous les usagers, non ?

**Comment by museOnSite** [comment]
Je pense qu'il n'y a pas besoin de faire des workaround avec le nouveau modèle de données.
En effet tu peux créer des User qui n'ont pas de bénéficiaires associé. Ce sera le cas des utilisateurs admin, il suffira juste d'associer des rôles adéquats.

**Comment by SebFalque** [comment]
Comme non membres, avez vous pensé aussi à intégrer de simple sympathisants ou personnes en entrée du processus d'adhésion/souscription (en attente de paiement...) ?
Cela pourrait vouloir signifier que des communication générale (infolettres) pourraient être envoyées depuis l'espace membre, ce qui est plus ou moins pertinent... Avez-vous une position ?
