### ISSUE TITLE
Donner automatiquement le ROLE_USER_MANAGER à tous les référents de commission

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#130]
Cela permettrait qu'ils puissent éditer les fiches des membres pour indiquer quand les personnes sont membres de leur commission. Cela leur permet ensuite de tenir le tableau des tâches bien à jour, puisqu'il faut être tagué comme membre de la commission pour devenir personne ressource d'une tâche

**Comment by janssens** [comment]
géré autrement. Les référents de commission peuvent éditer leur commission et ajouter / retirer des membres (beneficiaires)

**Comment by fgougou** [comment]
J'adore, encore mieux !
