### ISSUE TITLE
Donner automatiquement le ROLE_USER_MANAGER à tous les formateurs BR et AMBA

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#131]
Cela permet de tenir à jour la liste des personnes en attente de formation, et de taguer ensuite les personnes qui ont été formées comme bénévoles-ressource, ou comme ambassadeurs.
Cela permet aussi d'utiliser l'outil d'envoi d'emails.

**Comment by janssens** [comment]
Ces personnes (formateurs) ne sont pas identifiés dans l'outil, donc on affecte le Role à la main.

**Comment by fgougou** [comment]
Le rôle formateur BR existe dans l'outil, je l'avais créé ! Mais si vous préférez faire l'action manuellement, pas de souci.
Pour le rôle formateur AMBA, Armelle S. et Philippe C. le sont à ce jour, par le fait que ce sont les deux personnes qui le font. A ma connaissance, aucun élargissement du cercle n'a été fait à ce jour.
