### ISSUE TITLE
[bug] Pas de modification des comptes adhérents possible depuis le poste adhésion classique en magasin

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#132]
Impossible ce soir d'enregistrer une modification du prénom d'un bénéficiaire depuis un espace membre classique connecté à l'épicerie. Quand on appuyait sur le bouton "Modifier", rien ne se passait.

**Comment by janssens** [comment]
Pas de problème via Firefox, à tester sur chrome.

**Comment by janssens** [comment]
pas reproduit
