### ISSUE TITLE
Wording sur l'espace membre

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#135]
Deux mini fautes d'orthographe, rien de bien important mais je les mets là pendant que je les vois sur mon 
- Le NB au sommet : Florent ne **peut** plus / plutôt que ne **peux** plus
- Dans la légende : **ressource** / plutôt que **resource*
![capture espace membre](https://user-images.githubusercontent.com/36693586/44615775-a4250e80-a842-11e8-9f76-3f2b87d550fa.png)
Cet espace membre, c'est un petit bijou :-)

**Comment by janssens** [comment]
fixed
