### ISSUE TITLE
Gestion en mode Coop <> Asso

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#148]
Permettre une gestion en mode coopérative, sans gestion la annuelle des adhésions

**Comment by SebFalque** [comment]
Pour info nous avons hacké le mode "asso" pour qu'il passe avec notre fonctionnement "coop" à vis en mettant une date dans le lointain future (2050 ) pour l'expiration de l'adhésion... ça semble marcher.
