### ISSUE TITLE
Mettre à jour la fonction import CSV

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#149]
Importer en CSV les premiers coopérateur / adhérent

**Comment by SebFalque** [comment]
Bonsoir,
C'est une "good first issue"... mais par où commencer ?
La fonction import est-elle préexistante dans l'interface admin ? Ou seulement par un script ? Lequel ?

Aux 400 coop, nous avons développé un import direct en base... cf. https://github.com/elefan-grenoble/gestion-compte/issues/147#issuecomment-440083536

**Comment by janssens** [comment]
le bouton est "disabled"
![image](https://user-images.githubusercontent.com/675464/48758620-f2f70e80-eca0-11e8-8a4e-966c14bffbcb.png)
Mais la vielle fonction existe :
\AppBundle\Controller\AdminController::csvImportAction

**Comment by slapker** [comment]
Salut @janssens 

Ce post fait suite à ta réponse [ici](https://github.com/elefan-grenoble/gestion-compte/issues/147#issuecomment-450719191 )

J'essaye de rassembler les infos utiles pour le fichier CSV à importer dans Elefan et reviens vers toi dès que j'ai ça !

Merci !
