### ISSUE TITLE
Mettre nombre max de bénéficiaires en conf

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#151]
Mettre le nombre maximum de bénéficiaire autorisé par compte adhérent en conf.

**Comment by janssens** [comment]
done ?

**Comment by museOnSite** [comment]
La clé de conf existe mais je suis pas sûr qu'elle soit utilisée partout.

**Comment by janssens** [comment]
Ok, j'ai ajouté un check sur les deux actions d'ajout de bénéficiaires (BO + quick) (voir PR #270 )
Il faudrait ajouter aussi sur le merge de compte, je vais le noter sur le ticket #253
