### ISSUE TITLE
Adhésions rapides - Adhésion en ligne Helloasso

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#152]
Finaliser le système d'adhésion rapide.

**Comment by janssens** [comment]
Proposer le moyen de paiement "Helloasso" avec un montant à NULL.
Dans ce cas là, dans le formulaire pour "conclure" l'adhésion, le nouveau membre est invité à payer en ligne (CB) son adhésion.

**Comment by SebFalque** [comment]
> 
> 
> Proposer le moyen de paiement "Helloasso" avec un montant à NULL.
> Dans ce cas là, dans le formulaire pour "conclure" l'adhésion, le nouveau membre est invité à payer en ligne (CB) son adhésion.

Ce mode de fonctionnement peut être intéressant pour le fonctionnement "coopérative".
Avez-vous testé/mis en place un système de paiement par CB sur l'espace membre ou ailleurs  ? Lequel ?

**Comment by SebFalque** [comment]
Cette fonctionnalité est-elle aussi adaptable à un réglement par virement ou chèque ?

**Comment by janssens** [comment]
Alors
* Chèque est géré comme Espèce pour nous, on considére l'argent comme reçu au moment de l'adhésion. 
* Virement on fait pas, il faudrait pour ça une notion de paiement en attente.
Ca ne nous interesse pas car ça demanderai du sur-investissement de la part de ceux qui peuvent regarder l'état du compte en banque, et le sur-investisssement on aime pas ça. :)
Je crois qu'Helloasso propose le paiement par virement ce qui résout le problème, non ? (traité comme la cb)
* Le paiement Helloasso fonctionne très bien pour les ré-adhésions, mais n'est pas encore implémenté pour les adhésions > a venir très rapidement
