### ISSUE TITLE
Bloquer la réservation si créneau vide et premier créneau

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#156]
bloquer la réservation si le créneau est vide et que l'utilisateur n'a jamais fait de créneau.
Pour éviter qu'il s'y retrouve seul.

**Comment by lionf** [comment]
Bonjour,

Je suis coopérateur aux 400 Coop de Paris.
Comme vous le savez nous avons une version installée de votre logiciel des membres en cours d'adoption.

Nous avons importé l'ensemble de nos membres depuis une googleSheet directement dans la base et nous nous apprêtons à commencer des test de réservation de créneaux un peu approfondis.
Mais pour l'instant nous ne pouvons pas aller très loin dans la profondeur ;-) : aucun des créneaux définis n'est autorisé à personne.

En regardant le code il m'a semblé voir que la fonctionnalité évoquée dans le mail ci-dessous (issue # 156) , bien qu'elle semble être toujours open, a déjà fait l'objet d'une implémentation.
cf. le code de la méthode isBeginner de la class ShiftService.

Le problème est que lorsque l'on démarre, aucun membre n'a jamais été inscrit sur un créneau et tous se voient donc refuser l'accès aux créneaux, le serpent se mord la queue.
J'ai contourner le "problème" en affectant aux n premières lignes (correspondant à des créneaux anciens) de la table shift un shifter_id équivalent au beneficiary.id de chacun de nos n membres (beneficiary) afin que chaque membre soit considéré comme ayant déjà effectué un créneau.
C'est un artifice, ça marche, mais peut être y a t'il comme une sorte de bootstrap qui permette d'obtenir le même résultat plus proprement.

Autrement dit comment envisagiez vous l'application de cette règle #156 lors d'un démarrage à blanc ?

Mais peut-être n'ai je pas compris le sens de cette règle ou peut-être n'avons nous pas respecté certaines procédures initiales importantes en chargeant les membres directement dans la base ?

J'en profite pour vous remercier de tous vos efforts (et réussites!! ) de développement.

François

________________________________
De : Janssens Gaëtan [notifications@github.com]
Envoyé : vendredi 26 octobre 2018 15:34
À : elefan-grenoble/gestion-compte
Cc : Subscribed
Objet : [elefan-grenoble/gestion-compte] bloquer la réservation si créneau vide et première créneau (#156)


bloquer la réservation si le créneau est vide et que l'utilisateur n'a jamais fait de créneau.
Pour éviter qu'il s'y retrouve seul.

**Comment by janssens** [comment]
Bonjour @lionf 
Merci pour ton message. Ali de breizhicoop.fr a eut le même problème nous avons donc identifié cette coquille la semaine passée. 
Ce que nous avons prévu avec lui, (et dis moi si ça vous conviendra aussi !) c'est d'autoriser la réservation d'un créneau vide a tous les membres disposant d'une formation.

Ainsi, à l'ouverture, il suffit de former (ou d'identifier comme formé) un groupe de membre qui pourront remplir initialement le planning. Les nouveaux membres pourrons alors rejoindre les créneaux déjà "chapeautés" par un membre formé.

Est-ce que ce fonctionnement est suffisant pour vous ?
On peux aussi imaginer de mettre une conf "allow_booking_first_shift_if_empty" et chaque coop choisi ? 
à toi ! :)

**Comment by Arakmar** [comment]
Hello

Techniquement on pourrait avoir un role dédié à la réservation de créneaux vides et l'appliquer à certaines formations (comme elles font office de groupe).
Ce role serait ensuite automatiquement appliqué à l'utilisateur dès le premier créneau effectué (fonctionnement actuel) ou sous certaines conditions (avec un paramètre ?).
On pourrait également ajouter un paramètre qui permettrait de définir les roles par défaut des nouveaux utilisateurs (avec ce nouveau role par exemple), ce qui pourrait être ensuite modifiable une fois qu'une base conséquente de membres a déjà fait son premier créneau.

Vous en pensez quoi ?

**Comment by janssens** [comment]
@Arakmar c'est top, souple et propre
