### ISSUE TITLE
Ouverture des accés bénéficiaire non principal

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#158]
Quand un bénéficiaire non principal saisi son numéro de membre pour accéder, la première fois, à son espace personnel sur l'espace membre, ça lui dit que le compte est déjà activé (ce lui du bénéficiaire principal). 
NB : Le processus de création de compte bénéficiaire non principal fonctionne correctement avec la recherche par prénom.

**Comment by museOnSite** [comment]
Ça peut paraître évident mais il faut faire attention que n'importe qui ne puisse pas activer un utilisateur.
A discuter mais il me semble que pouvoir rechercher par nom alors que t'es pas connecté c'est pas top niveau sécurité des données.

**Comment by janssens** [comment]
les données sont (déjà) annonymisés et l'activation se fait par email

**Comment by museOnSite** [comment]
Après il faudra gérer tout ceux qui ont pas d'email (ou pas le bon)
