### ISSUE TITLE
Log de début de cycle manquant

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#168]
Certains compte adhérent se retrouvent à ne plus pouvoir réserver car leur log de temps n'est pas décrémenté en début de cycle.
Le code a été refactoré entre temps pour insérer un log de temps à 0 quand le compte est gelé.

Le problème est peut-être corrigé depuis mais il faut s'en assurer.

J'ai corrigé certains log de temps à la main comme le #1431.

**Comment by janssens** [comment]
```SQL
SELECT m.id,m.member_number FROM membership AS m 
LEFT JOIN time_log AS tl on tl.membership_id = m.id AND date > "2018-10-01" AND tl.description = "Début de cycle"
WHERE m.frozen = 0 AND m.withdrawn = 0 AND first_shift_date IS NOT NULL AND tl.id IS NULL;```

# id, member_number
1046, 1061
1515, 1473

**Comment by janssens** [comment]
Pour le premier
![image](https://user-images.githubusercontent.com/675464/48001796-e784de80-e109-11e8-8bb6-92094f7d567e.png)

**Comment by janssens** [comment]
Et le second, premier créneau prévu le 10 novembre.

Tout est ok pour toi @museOnSite ? on ferme ?

**Comment by museOnSite** [comment]
@janssens Après avoir corrigé les *withdrawn* qui étaient null ta requête renvoi 157 résultats. On a du boulot de correction.

**Comment by museOnSite** [comment]
Je vais m'en occuper. Mais si je peux faire ça uniquement en SQL, je me passerais bien d'une commande.

**Comment by janssens** [comment]
Si on est certain de régler le problème définitivement pourquoi pas. 
Mais je pensai que cette fonctionnalité était utile : Actuellement si tu fais une "bétise" en admin et tu supprime un log temps par exemple, avec cette fonction tu pourrais remettre au "propre".
L'autre solution est de mettre tous le monde au propre une fois le pb corrigé, et d'interdir la suppression de log en admin. 
Seul l'ajout d'un log "personalisé" est autorisé et seulement les logs "personalisés" sont supprimables.
Alors pour faire une faveur ou une "remise à plat", il faut créer un "bonus" personalisé de cette manière.
Si tu bosse dessus, est-ce que tu peux créer une colonne "type" au format int avec des variable de class BOOK_A_SHIFT, END_OF_CYCLE, PENALTY_FOR_NOT_SHIFTING, PENALTY_FOR_LATE_DISMISS, PENALTY_FOR_NOT_SHOWING, CUSTOM ? la colonne reste desc est utile pour le dernier cas CUSTOM.
tu me suis ?

Déso j'ai pas trop de temps cette semaine, beaucoup de boulot et j'assure le suivit du championnat du monde de raid pour la fédé.

**Comment by museOnSite** [comment]
Voilà le script, pas besoin de commande. Totalement réutilisable. Je te laisse jeter un œil, j'ai mis pas mal de commentaires pour comprendre plus facilement ce que ça fait.

Sinon entièrement d'accord avec toi pour le principe de gestion des logs en admin.

```
# Create temp table to store the membership cycles dates
DROP TABLE IF EXISTS tmp_cycles;
CREATE TABLE tmp_cycles
(
  member_id        INTEGER PRIMARY KEY,
  member_number    INTEGER,
  first_shift_date DATETIME,
  current_cyle     DATETIME,
  previous_cycle   DATETIME
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci;

# Calculate current cycle start dates for each member with following conditions:
# not closed
# not frozen
# with a first shift
# not the first cycle
INSERT INTO tmp_cycles (member_id, member_number, first_shift_date, current_cyle)
  SELECT
    id,
    member_number,
    first_shift_date,
    DATE_ADD(concat(CURDATE(), ' 00:00:00'), INTERVAL
             -MOD(DATEDIFF(concat(CURDATE(), ' 00:00:00'), first_shift_date), 28) DAY) AS cycle_start
  FROM membership
  WHERE frozen = 0 AND withdrawn = 0 AND first_shift_date IS NOT NULL
  HAVING first_shift_date < cycle_start;

# Calculate previous cycle start (if it was not the first cycle of the member)
UPDATE tmp_cycles
SET previous_cycle = DATE_ADD(current_cyle, INTERVAL -28 DAY)
WHERE first_shift_date < DATE_ADD(current_cyle, INTERVAL -28 DAY);

# Create temp table to store the missing time logs
DROP TABLE IF EXISTS tmp_missing_logs;
CREATE TABLE tmp_missing_logs
(
  member_id     INTEGER,
  member_number INTEGER,
  date          DATETIME
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci;

# Calculate missing logs for current cycle
INSERT INTO tmp_missing_logs (member_id, member_number, date)
  SELECT
    c.member_id,
    c.member_number,
    c.current_cyle
  FROM tmp_cycles c
    LEFT JOIN time_log AS tl ON tl.membership_id = c.member_id
                                AND (date BETWEEN c.current_cyle AND now()) AND tl.description LIKE 'Début de cycle%'
  WHERE tl.id IS NULL;

# Calculate missing logs for previous cycle
INSERT INTO tmp_missing_logs (member_id, member_number, date)
  SELECT
    c.member_id,
    c.member_number,
    c.previous_cycle
  FROM tmp_cycles c
    LEFT JOIN time_log AS tl ON tl.membership_id = c.member_id
                                AND (date BETWEEN c.previous_cycle AND DATE_ADD(c.current_cyle, INTERVAL -1 SECOND)) AND tl.description LIKE 'Début de cycle%'
  WHERE tl.id IS NULL AND c.previous_cycle IS NOT NULL;

# Insert missing logs
INSERT INTO time_log (date, time, description, membership_id)
    SELECT date, -180, 'Début de cycle', member_id FROM tmp_missing_logs;

# Clean tables
# TODO
```

**Comment by janssens** [comment]
#kingofsql #nicework !

**Comment by museOnSite** [comment]
Merci !
J'ai passé le script en prod. Ça a rajouté un peu plus de 200 logs de début de cycle.
J'ai aussi ouvert une pull request pour mettre les colonnes Not Nullable.
