### ISSUE TITLE
Créneaux: possibilité de réserver un créneau déjà réservé

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#17]
Scénario:
1. J'ai réservé un créneau Bureau des membres le vendredi 9 mars de 12h à 13h30
2. Je retourne sur la page de réservation, le créneau précédent est toujours disponible (non grisé, la popup s'ouvre quand on clique dessus)

Note: Je n'ai pas essayé de véritablement réservé le créneau une deuxième fois

**Comment by Luxoboy** [comment]
Est-ce que tu peux vérifier s'il s'agit effectivement du même shift ou du shift non qualifié à la même heure ?

**Comment by museOnSite** [comment]
J'ai réservé le créneau ambassadeur donc le créneau restant que je pouvais réserver était non qualifié

**Comment by Luxoboy** [comment]
Bug confirmé, rencontré en local.

J'investigue.

**Comment by Luxoboy** [comment]
Fix dans a2a0f3c.
J'ouvre une PR.

*Attention * : je viens de me rendre compte qu'en faisant comme ça les cas de chevauchement de créneaux ne sont pas gérés, et qu'on ne permet pas à deux bénéficiaires de faire le créneau en même temps.
