### ISSUE TITLE
L'alerte de réadhésion manque de précision 

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#179]
L'alerte de réadhésion mériterait plus de précision lorsque l'on s'approche du terme (cf. capture d'écran).
Je propose de rajouter une phrase: "Tu pourras réadhérer à partir de lundi 17 novembre 18:00".

![capture du 2018-11-11 12-04-29](https://user-images.githubusercontent.com/10038524/48312103-1982be80-e5aa-11e8-96f5-928e3f0eb398.png)

**Comment by janssens** [comment]
En fait la phrase serait plutôt, "ré-adhésion possible en ligne par carte bancaire à partir du <...> et dès à présent au bureau des membres par chèque, espèce ou monnaie locale."
Mais bien sûr je valide le principe ! :+1:

**Comment by museOnSite** [comment]
Done.
PR: #229
