### ISSUE TITLE
faute d'accord page de réservation de créneau

### ISSUE THREAD

**Issue by henrisamson** [elefan-grenoble/gestion-compte#19]
"Attention ! Cette inscription vous engage.
Pour pouvoir annuler, votre créneauX devra trouver repreneur."

Le X de créneau est en trop.
Merci et bonne journée !

**Comment by sdenier** [comment]
Vu. Corrigé dans la branche outil-creneau-v1. Pour la prochaine release
https://github.com/elefan-grenoble/gestion-compte/issues/9
