### ISSUE TITLE
Dégeler immédiatemment son compte

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#194]
Je pense qu'il serait bien de donner la possibilité à un membre de dégeler immédiatement son compte en plus de pouvoir le dégeler à la fin du cycle en cours.
Exemple de demande dans ce sens:
https://lelefan.freshdesk.com/a/tickets/4038

**Comment by janssens** [comment]
Effectivement c'est plus souple. 
Mais si j'ai fait ça comme ça c'était pour que gel dure au minimum un cycle (car sinon il ne sert à rien). 
Comme on ne garde pas les dates de gel/degel, si on autorise le dégel immédiat, on peux avoir un gel de moins d'un cycle.
A priori, et sauf si je me trompe, celà ne donne un avantage ou un moyen de tricher. Donc c'est ok.
Par contre il ne faudra jamais autoriser le gel immédiat :)
A coder avec un petite popin "Si tu degel tout de suite, tu devras faire 3 heures avant le X/X/20XX, fin de ton cycle"

**Comment by museOnSite** [comment]
Oui d'accord avec tout:
* Pas de gel immédiat
* La popup avec le message

**Comment by janssens** [comment]
Prévoir de choisir au moment du gel du compte la date de degel.

**Comment by janssens** [comment]
Proposer tous les cycles jusqu'à la fin de l'adhésion du membre pour le gel.
Créer un type de gel (vacance / maténité - maladie )

**Comment by symartin** [comment]
Les admins et les user managers peuvent déjà le faire. Dans notre système actuel, il faut maintenant au minimum deux mois de gel. Donc un jour on se penchera surement sur la possibilité d'avoir un tps de gel minimum et de pouvoir indiquer le début et la fin du gel. Mais clairement on ne peut pas laisser les membre dégeler à loisir leur compte sans garde fou.

pour les maladies et autre dispense : https://github.com/elefan-grenoble/gestion-compte/issues/469
