### ISSUE TITLE
Log de temps continue de se décrementer lorsque l'adhésion se termine 

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#196]
Le log de temps continue de se décrementer lorsque l'adhésion touche à sa fin.

**Comment by Arakmar** [comment]
On pourrait ajouter un paramètre pour la durée d'adhésion ?

**Comment by museOnSite** [comment]
Oui un paramètre me semble uen très bonne idée.
Par contre on 2 choix d'implémentation:
* Soit on utilise le paramètre un peu partout
* Soit on rajoute une colonne **end** dans la table registration. On utilise donc le paramètre uniquement au moment où l'on insert une adhésion en base.

J'ai une petite préférence pour la deuxième solution.

**Comment by Arakmar** [comment]
Je préfère aussi la deuxième solution, c'est plus souple. Surtout si jamais une coop décide de changer en cours de route sa durée d'adhésion pour les nouvelles cotisations.

**Comment by janssens** [comment]
GO solution 2

**Comment by museOnSite** [comment]
J'ai créé l'issue #201 pour rendre la durée d'adhésion configurable. Comme ça je peux fermer cette issue.
