### ISSUE TITLE
Durée de validité d'une adhésion configurable

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#201]
Ajouter une colonne **end** à la table **registration** contenant la date de fin de validité d'une adhésion. Cette colonne doit pouvoir être null sachant que le besoin d'adhésion n'expirant jamais existe.

Utiliser le paramètre **registration_duration** lors de la création d'une *registration* pour mettre la bonne date de fin. La valeur de ce paramètre pouvant être 'inifinite' (ou null ?) par exemple.

Refactorer le code pour utiliser cette date de fin.

**Comment by bagheera2382** [comment]
Hello je déterre cette conversation car à Rennes on vient de faire fasse à un problème qui semble être en rapport. Je m'explique. Dans le fichier `parameters.yml` nous avons mis le paramètre `registration_duration: 99 years`, car nous n'avons pas un fonctionnement avec des adhésions renouvelables, mais un système de prise de parts sociales qui n'a lieu qu'une fois.
J'avais pensé que ce paramètre permettrait de ne pas voir les comptes des coopérateurs être bloqués (ou pas avant 99 ans :-) ) mais plusieurs coopérateurs ont depuis plusieurs jours un bandeau de fin d'adhésion qui s'affiche sur leur page personnelle. Je précise que pour ces personnes la date d'adhésion approche de 1 an.
D'après ce que j'ai vu dans le code, le paramètre registration_duration n'est utilisé que dans la partie Timelog. À différents autres endroits (Membership.php et MembershipController.php) il y a des '1 year' en dur.
Du coup ma question est : est-ce que en théorie ces '1 year' font bien référence en théorie à la même chose que la 'registration_duration' qui est dans le code ?
SI c'est le cas je ferai la modification pour que la valeur vienne du fichier de paramètres.

**Comment by janssens** [comment]
@bagheera2382 je vais corriger ça dès que possible. 
Ce n'est pas simple car les paramêtres ne sont pas disponible dans les modèles. Il faut donc ajouter un service. Je vais faire ça proprement.

**Comment by janssens** [comment]
@bagheera2382 c'est corrigé dans la dernière version
