### ISSUE TITLE
URL /member/show/{id} accessibles ?

### ISSUE THREAD

**Issue by Luxoboy** [elefan-grenoble/gestion-compte#206]
Je viens de constater que les URLs de ce type sont accessibles si on est connecté (e.g. https://membres.lelefan.org/member/show/1). On a donc accès aux infos personnelles (adresse email, numéro téléphone, etc).

Cela m'a paru suspicieux donc je le mets là au cas où ce n'est pas souhaitable ; d'autant plus que ces pages sont indiquées faire partie de l'outil adhésion/réadhésion.

**Comment by janssens** [comment]
Il y a un système de 'proxy' maison, peut-être un peu maladroit, mais qui autorise tous les membres présent à l'épicerie (check ip) à ouvrir une fiche membre en connaissant ID et email (soit en présence du membre, soit avec cette information reçu).
