### ISSUE TITLE
Envoi de mails intempestifs tous les matins 

### ISSUE THREAD

**Issue by SebFalque** [elefan-grenoble/gestion-compte#213]
Bonjour,
Depuis quelques jours, alors que nous n'avons pas encore mis en place de crontab, des mails de relance concernant des créneaux sont envoyées chaque matin à tous les coopérateurs.
Pourriez-vous nous mettre sur la piste pour comprendre pourquoi ces mails sont envoyés.
PS : indice peut-être lié, nous avons mis en place une "bidouille" pour permettre l'inscription aux créneaux en simulant un premier créneau pour chaque copérateur afin qu'il puisse s'inscrire sur d'autres...

**Comment by museOnSite** [comment]
Salut,

Peux-tu nous en dire un peu plus sur ces emails (contenu) pour que nous puissions t'aiguiller?

Merci

**Comment by SebFalque** [comment]
Bonjour Bastien,
Il s'agit du mail "[ESPACE MEMBRES] Reprends ton créneau dans 28 jours
Il est très certainement envoyé car nous avons fictivement assigné un
premier créneau dans le passé à chaque cooperateur-trice pour leur
permettre dans réserver à partir de maintenant sans qu'ils soient formés...
mais nous sommes surpris que ces mails partent tous les jours à chaque
coopérateur sans que nous n'ayons mis en place de planification cron.
Sébastien

Le mer. 26 déc. 2018 à 13:05, Bastien Deshayes <notifications@github.com> a
écrit :

**Comment by museOnSite** [comment]
Ces emails sont envoyés par la commande qui génére les créneaux à J+28: **app:shift:generate**.
C'est effectivement le fait d'avoir attribué des créneaux qui a déclenché cela. En effet, lorsque qu'un créneau est effectué il est proposé au bénéficiaire de reprendre le même créneau à J+28.
Il n'est pour l'instant pas possible de désactiver cette fonctionnalité.

**Comment by pierre4205** [comment]
Bonjour, je voulais savoir si il y avait une évolution prévue pour désactiver cette fonctionnalité ou réduire le temps de blocage du créneau.

Nous pouvons peut être travailler dessus.

**Comment by museOnSite** [comment]
Bonjour @pierre4205 !
Il n'est pas prévu pour nous de bosser là-dessus mais si vous pouvez travailler dessus ce serait top. Cela va dans le sens de rendre le plus générique et configurable possible l'espace membre.
Si vous avez besoin des questions n'hésitez pas ! :smile:
