### ISSUE TITLE
Connexion au Wiki depuis l'épicerie

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#215]
A l'épicerie (depuis la tablette notamment), les membres doivent se connecter à l'espace membres pour accéder au wiki.
Je pense qu'il faudrait améliorer cela pour 2 raisons:
* Perte de temps. Le membre ne se souvient plus de ses identifiants, etc.
* Oubli de déconnexion. Ce qui peut être très problématique pour des personnes qui ont les droits admin par exemple.

**Comment by janssens** [comment]
Bonne idée, par contre ce n'est pas lié à l'espace membre mais un dev à faire sur le wiki.

**Comment by janssens** [comment]
@museOnSite it's done. 
J'ai juste fait un test sur l'IP autour de la ligne qui interdit la lecture au utilisateurs non connecté, dans le LocalSettings.php du mediwiki

**Comment by museOnSite** [comment]
Au top! Merci
