### ISSUE TITLE
Ajout d'un statut personalisable (quelques mots) pour chaque utilisateur

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#216]
Dans le but de "briser la glace" autoriser, les membres qui le souhaitent, à renseigner un "statut" perso.
ex: 
* "J'aime la montagne et le jardinage 🥕" 
* "expert en tarte au pomme 🥧"

Ces statuts pourront ensuite être affichés sur l'écran des membres actuellement dans l'épicerie, au scan du badge, sur le profil membre, accessible aux autre membres partageant le  même créneau ...

Attacher le statut à l'utilisateur ou au bénéficiaire (pas au membership)

Techniquement je vois 3 possibilités :
* Ajouter un champs à l'entité user ou au bénéficiaire (on ne garde alors pas l'historique des status)
* Ajouter une nouvelle entité dédiée
* Utiliser l'entité existante note : le statut est une note de soit sur soit (actuellement les "post-it" sont déjà des notes de soit sur null par exemple)

J'ai un préférence pour la 3. 
@Arakmar @museOnSite un avis ?

**Comment by museOnSite** [comment]
Je ne suis pas du tout pour la solution 3. Je trouve ça vraiment crade.
Je vote pour l'ajout d'un champ au niveau du bénéficiaire.

**Comment by Arakmar** [comment]
Pour les notes je trouve que dans l'idée ça peut être intéressant de pouvoir les réutiliser mais elles sont actuellement trop dépendantes du membership. Ce n'est pas du tout le même concept, on a un author (User) qui créé une note pour un Membership.

Je serais plutôt pour l'option 2 (avec texte et date de modification par exemple) avec un lien 1..n vers le bénéficiaire. Ca permettrait d'être assez souple et nous permettrait aussi d'enrichir cette mini bio avec éventuellement d'autres informations à l'avenir.

**Comment by janssens** [comment]
Je n'avais pas regardé en détail note, effectivement je pensai que c'était de user à user donc l'option 3 ne peux pas fonctionner. désolé.
Entre 1 et 2 je préfère 2. 
OK pour toi @museOnSite ?
