### ISSUE TITLE
Fermer le compte membre en fin d'adhésion

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#219]
Gel ou autre astuce pour éviter que les membres continuent à recevoir des mails "début de créneau" par exemple.
Fin d'adhésion + 1 mois ?

**Comment by museOnSite** [comment]
On fermerait pas le compte plutôt ?
Le gel est pour moi une notion pour les comptes actifs.

**Comment by janssens** [comment]
Oui pourquoi pas. j'ai mis "ou autre astuce" justement pour y réfléchir.
J'aime bien l'idée que les mails partent quand même au moins le premier mois. 
Je ne sais pas comment les membres gère mais moi les deux fois j'ai ré-adhéré après la fin de mon adhésion précédente. 
Fermer c'est à priori ok pour moi.

**Comment by museOnSite** [comment]
Oui par contre entièrement d'accord avec le fait de mettre un délai

**Comment by museOnSite** [comment]
Je prends cette issue
