### ISSUE TITLE
Problème lors de la mise à jour du schéma de la bdd 

### ISSUE THREAD

**Issue by aboigues** [elefan-grenoble/gestion-compte#240]
Bonjour,

Je me suis positionné sur la branche master du git. 
J'ai relancé la création d'une bdd : 

`bin/console doctrine:schema:create`

puis
` bin/console doctrine:migration:migrate`

Message de sortie : 

`
WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20190125122437 from 0

  ++ migrating 20181103153303_initial

  SS skipped (Reason: Good ! The database seems to be already populated, skipping this migration...)

  ++ migrating 20181111111529_drop_unmapped_tables

Migration 20181111111529_drop_unmapped_tables was executed but did not result in any SQL statements.

  ++ migrated (0.14s)

  ++ migrating 20181111111958_authcode_cascade

     -> ALTER TABLE auth_code DROP FOREIGN KEY FK_5933D02C19EB6921
     -> ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE
     -> ALTER TABLE access_token DROP FOREIGN KEY FK_B6A2DD6819EB6921
     -> ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD6819EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE
     -> ALTER TABLE refresh_token DROP FOREIGN KEY FK_C74F219519EB6921
     -> ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F219519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE

  ++ migrated (0.66s)

  ++ migrating 20181111120724

     -> ALTER TABLE membership CHANGE withdrawn withdrawn TINYINT(1) DEFAULT '0' NOT NULL, CHANGE frozen frozen TINYINT(1) DEFAULT '0' NOT NULL, CHANGE frozen_change frozen_change TINYINT(1) DEFAULT '0' NOT NULL

  ++ migrated (0.02s)

  ++ migrating 20181121092207

     -> CREATE ALGORITHM=TEMPTABLE VIEW abstract_registration AS (SELECT CONCAT('1_',registration.id) as id,1 as type,registrar_id,created_at as date,amount,mode,CONCAT(LOWER(beneficiary.firstname),' ',UPPER(beneficiary.lastname)) as beneficiary, registration.membership_id
       FROM registration
       LEFT JOIN membership ON registration.membership_id = membership.id
       LEFT JOIN beneficiary ON beneficiary.id = membership.main_beneficiary_id
      ) UNION ALL
      (SELECT CONCAT('2_',id) as id,2 as type,registrar_id,created_at as date,amount,mode,email as beneficiary, NULL as membership_id
       FROM anonymous_beneficiary
      );
Migration 20181121092207 failed during Execution. Error An exception occurred while executing 'CREATE ALGORITHM=TEMPTABLE VIEW abstract_registration AS (SELECT CONCAT('1_',registration.id) as id,1 as type,registrar_id,created_at as date,amount,mode,CONCAT(LOWER(beneficiary.firstname),' ',UPPER(beneficiary.lastname)) as beneficiary, registration.membership_id
       FROM registration
       LEFT JOIN membership ON registration.membership_id = membership.id
       LEFT JOIN beneficiary ON beneficiary.id = membership.main_beneficiary_id
      ) UNION ALL
      (SELECT CONCAT('2_',id) as id,2 as type,registrar_id,created_at as date,amount,mode,email as beneficiary, NULL as membership_id
       FROM anonymous_beneficiary
      );':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'abstract_registration' already exists

In AbstractMySQLDriver.php line 38:

  An exception occurred while executing 'CREATE ALGORITHM=TEMPTABLE VIEW abstract_registration AS (SELECT CONCAT('1_',registration.id) as id,1 as type,registrar_id,creat
  ed_at as date,amount,mode,CONCAT(LOWER(beneficiary.firstname),' ',UPPER(beneficiary.lastname)) as beneficiary, registration.membership_id
         FROM registration
         LEFT JOIN membership ON registration.membership_id = membership.id
         LEFT JOIN beneficiary ON beneficiary.id = membership.main_beneficiary_id
        ) UNION ALL
        (SELECT CONCAT('2_',id) as id,2 as type,registrar_id,created_at as date,amount,mode,email as beneficiary, NULL as membership_id
         FROM anonymous_beneficiary
        );':

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'abstract_registration' already exists

In PDOConnection.php line 90:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'abstract_registration' already exists

In PDOConnection.php line 88:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'abstract_registration' already exists

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
`

Merci !

**Comment by janssens** [comment]
Etrange, ça ne devrait pas pouvoir se passer car cette vue n'est créée nul part avant... 
J'ai ajouté un drop qui devrait te permettre de passer cette étape, c'est sur la branche dev.

**Comment by Arakmar** [comment]
En fait ici le problème c'est que la base a été créée à partir du mapping avec schema:create. Du coup ça a créé une table abstract_registration au lieu de la vue dans les migrations.
Et même ça plantera probablement dans les migrations d'après car les modifications seront déjà là.

Il faut qu'on enlève le schema:create de la doc d'installation et faire uniquement un migrate. Ou alors sinon, il faut qu'on vérifie dans chaque migration et pour chaque champ si les modifications ont déjà été faites.
