### ISSUE TITLE
Impossible d'afficher une fiche membre si pas de time log ?

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#242]
![image](https://user-images.githubusercontent.com/675464/52806979-9ed6ad00-308a-11e9-99b2-a8f4f1c80259.png)

**Comment by museOnSite** [comment]
T'aurais le numéro de membre concerné ?

**Comment by janssens** [comment]
C'est ok il manquait juste une migration ... sorry
