### ISSUE TITLE
Envoie du premier mail pour configurer son mot de passe

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#257]
Bonjour,
Lorsqu'on crée un nouvel adhérent, celui-ci reçoit au moins deux mails : un mail de bienvenu qui est personnalisable et un mail pour configurer son mot de passe. Ce dernier renvoie systématiquement sur une page de validation du compte sans configurer son mot de passe. 

La personne se trouve alors connecté à l'espace membre, mais devra utiliser l'option de récupération de mot de passe afin de se connecter la prochaine fois.

Le problème est le même à partir du bouton “nouvelle adhésion réunion d’info” ou “nouvelle adhésion”.

Merci pour votre aide

**Comment by jolleon** [comment]
Ca m'est en effet arrivé lors de mon inscription, et en plus de ça il m'était impossible de re-configurer mon mdp immédiatement (probablement à cause de la limite de 2h). Le lien ne m'avait aussi pas automatiquement connecté à l'espace membre et je n'ai donc pas pu y avoir accès avant 2h plus tard, pas top comme première expérience !

**Comment by Arakmar** [comment]
Effectivement il y a de gros soucis avec le mail pour le de mot de passe depuis qu'on a refait cette partie, j'essaie de m'en occuper dans les jours qui viennent. Il faudrait aussi qu'on fusionne ces deux mails car ça n'a pas beaucoup d'intérêt d'en avoir deux séparés.

**Comment by janssens** [comment]
traité #272
