### ISSUE TITLE
Nouveau rôle

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#258]
Bonjour,

Dans notre mode de fonctionnement, nous avons plusieurs 'bénévoles ressources' qui gère les planning et font adhérer les coopérateurs. Actuellement, ils sont tous admins, car c'est le seul rôle qui permettent de gérer les créneaux, mais ceux-ci ont aussi accès à plusieurs options 'sensibles', par exemple la semaine type ou le montant des parts sociales.

Il nous faudrait un rôle intermédiaire entre l'admin et le user_admin, ou alors augmenter les droits de l'user_admin pour pouvoir gérer les créneaux et le compteur de temps sur la fiche de membres.

J'ai fais un petit tableau récapitulatif des différents rôles dans l'espace membre, et j'ai mis en rouge les persmissions que j'aimerais voir rajouté à une sorte de super_user_admin.

![image](https://user-images.githubusercontent.com/45469217/54088539-534cb180-435f-11e9-9f6d-ba176a90f539.png)

**Comment by janssens** [comment]
Ajouter un ROLE_SHIFT_MANAGER
je valide.
