### ISSUE TITLE
Congé maladie

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#259]
Bonjour,
Actuellement, si un membre veut prendre congé, il peut geler son compte. Il ne fera pas ses créneaux, mais il ne pourra pas non plus acheter dans l'épicerie.

Il n'existe pas encore d'option pour ceux qui voudrait acheter, mais qui on une 'bonne raison' de ne pas faire leurs créneaux, par exemple ceux qui sont en congé maladie ou les femmes enceintes.

**Comment by janssens** [comment]
Bonne idée

**Comment by janssens** [comment]
sera géré dans #194

**Comment by symartin** [comment]
doublon avec https://github.com/elefan-grenoble/gestion-compte/issues/469

**Comment by symartin** [comment]
Réglé avec https://github.com/elefan-grenoble/gestion-compte/issues/469
