### ISSUE TITLE
role_admin disparait avec une formation

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#263]
Bonjour, voici la situation :

Sur un user qui a une formation : la promotion au rôle d'admin (ou autre rôle) ne fonctionne pas. Le bandeau vert s'affiche indiquant que ça bien fonctionné, mais son rôle ne s'actualise pas : sa fiche indique toujours "user" (et non pas "user_admin") et quand on se connecte avec son compte, les options ne sont pas là.

Par contre, sur la même personne qui n'a pas de formation, la promotion en admin fonctionne bien.

Dès qu'on remet une formation, le rôle admin disparait.

Il est donc impossible qu'une personne ait un rôle d'admin et une formation, ce qui est bien embêtant.

**Comment by janssens** [comment]
@Arakmar je pense que c'est lié à ton évolution sur le fait que les formations devenait des Roles, pourras-tu jeter un oeil ?

**Comment by Arakmar** [comment]
Effectivement c'était bien lié. On initialisait mal les roles pour les nouvelles formations. Ça marchait chez nous en prod (sauf pour les formations récentes) car ça avait été fait par la grosse migration vers le nouveau modèle.

**Comment by Ali-romdhani** [comment]
Donc pour nous il suffit de faire une mise à jour pour voir le bug disparaitre ?

**Comment by Arakmar** [comment]
Oui, j'ai rajouté une petite migration pour remettre tout ça d’aplomb ;)
