### ISSUE TITLE
Recherche de produits à partir des exports Kaso

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#267]
Implémenter une interface web permettant de rechercher des produits et leurs infos.

Les produits sont exportés depuis Kaso toutes les nuits et insérés dans la base kaso sur le serveur de prod (base différente de l'espace membre).

Comment implémenter cette interface ?

* Nouvelle application complètement séparée de l'espace membre ?
* Dans l'espace membre, même module ?
* Dans l'espace membre, module séparé ?

@Arakmar @janssens Votre avis ?
Perso je penche plutôt pour la première solution comme c'est spécifique à l'éléfan. Mais ça veut dire qu'on utilise pas Symfony à priori si on fait ça.

**Comment by Arakmar** [comment]
J'avais déjà commencé à développer ça en fin d'année dernière mais j'ai un petit peu mis en pause comme on avait trouvé une autre solution pour l'inventaire. J'étais parti sur un module Symfony séparé avec des datatables pour l'affichage. C'était à peu près utilisable mais il restait encore un peu de boulot.
Je crois qu'on avait discuté de tout ça fin décembre et des trois solutions sur MM.

Mais finalement avec le recul, je penche plutôt aussi pour une application séparée (en OAuth avec l'espace membre), à moins qu'on voit des avantages à pouvoir lier la base kaso à des fonctionnalités de l'espace membre ? Mais on a quand même metabase qui fait plutôt bien le boulot pour la partie stat.

Mais je pense que même pour une application séparée ça serait préférable d'utiliser Symfony (gestion de l'OAuth, Doctrine et API Rest) ou au minimum un ORM pour le gain de temps pour le développement et en maintenance. Après au niveau front, ça serait peut être l'occasion d'utiliser un framework JS type Vue ou Angular ?

Je pusherai ma branche aujourd’hui, peut être que certaines choses sont réutilisables dedans.

**Comment by museOnSite** [comment]
@Arakmar  On est sur de la lecture seule et les données ne sont pas du tout secrètes à priori donc pas besoin d'OAuth

**Comment by janssens** [comment]
Ok pour une app séparée de mon point de vue.
J'aimerai bien en profiter pour découvrir VueJs ou Angular, à vous de chosir.
J'aimerai bien restreindre l'accés à nos membres uniquement tout de même, notamment si on donne accès aux prix et aux statistiques de vente par exemple. 
Même si les données sont en lecture seul, je le vois un peu comme le wiki : un service réservé aux membres.

**Comment by janssens** [comment]
Et on pourra aussi le faire évoluer, pour proposer aux membres de faire des commentaires sur les produits, ou de proposer des modifications sur les données ?

**Comment by museOnSite** [comment]
Ok pour une app séparée.
Je touche pas mal en Angular donc je veux bien mettre ça en place. En tout ce choix n'est pas impacté par le fait de mettre en place une authentification car l'application Angular est standalone et s’exécute uniquement côté client (elle sera servie directement par le nginx), on peut mettre n'importe quel backend derrière (plus simple si c'est une API REST json).

Reste donc à trancher le choix du backend : 
* Dans l'espace membre (à priori non)
* Une autre app symfony connectée en Oauth2 sur l'espace membre.
* Autre (php simple, nodeJS, java, ...) ?

**Comment by janssens** [comment]
symfony 4 ou php simple je dirais, pour "contenir" les performances du serveur ? (moins de techno différentes)

**Comment by Arakmar** [comment]
Va pour Angular alors, ça faisait un moment que je voulais le tester.
Je suis plutôt aussi pour rester sur du Symfony, en plus avec la version 4 la mise en place du projet est vraiment simplifiée. J'ai déjà fait pas mal d'API avec FOSRestBundle, ça se fait super facilement ;)

**Comment by museOnSite** [comment]
Bon ben je te laisse mettre en place l'app Symfony. Je m'occupe de l'app Angular :)

**Comment by museOnSite** [comment]
Je ferme. On réouvira des issues dan les autres projets si besoin.
