### ISSUE TITLE
PHP-FPM 500: allowed memory size exhausted

### ISSUE THREAD

**Issue by PierrickBrun** [elefan-grenoble/gestion-compte#271]
Bonjour,

En essayant de déployer en production je me retrouve avec un problème de mémoire, voici les logs d'erreurs retrouvés par nginx:

`PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/elefan-gestion-compte/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 638" while reading response header from upstream, client: 90.65.166.201, server: adherents.demainsupermarche.org, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "adherents.demainsupermarche.org"
2019/03/30 18:49:10 [error] 1087#1087: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/elefan-gestion-compte/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107`

Afin de vérifier qu'il ne s'agisse pas juste du paramètre `memory_size` trop petit, je l'ai passé de 128M à 1G dans le php.ini mais le problème persiste.

Je n'ai pas le soucis avec le serveur de dev integré. J'ai eu le problème sur la branche master et develop.

Avez-vous déjà constaté cela ?

**Comment by janssens** [comment]
Bonjour @PierrickBrun Je n'ai jamais eut ça. 
Essai de désactiver toute forme de log dans ta fonc, étant donné que c'est monolog qui sempble manquer d'espace ?

**Comment by janssens** [comment]
@PierrickBrun des nouvelles ?

**Comment by PierrickBrun** [comment]
@janssens 
Désolé pour la réponse tardive.
Après des modifications dans le logging (via syslog au lieu de stream) j'ai pu retrouver l'erreur qui causait le problème.

C'était un classique problème de droits, j'avais oublié de donner les droits sur le dossier à www-data au lieu de mon user..

Merci
