### ISSUE TITLE
Interface de relance des bénéficiaires qui ne se connectent pas

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#273]
Faire une interface pour le bureau des membres semblable à celle pour relancer les membres qui n'ont pas ré adhéré mais pour les membres qui ne se connecte pas ou plus à l'espace depuis un certain temps.

**Comment by raphodn** [comment]
intéressant comme idée.
par exemple actuellement, sur les 319 comptes ouvert à l'Elefan, 17 ont l'un de leur bénéficiaire qui ne s'est jamais connecté (filtrer sur compte "ouvert" + "non activé")

**Comment by raphodn** [comment]
intéressant comme idée.

par exemple, sur les 319 comptes actuellement ouvert à l'Elefan, 17 ont l'un de leur bénéficiaire qui ne s'est jamais connecté (filtrer sur compte "ouvert" + "non activé")
