### ISSUE TITLE
Gestion des cartes membres

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#274]
Fonctionnalité à retoucher:
* Pas de pré-attribution des numéros de carte
* Ajouter la vérification de la validité numéro de carte (clé de contrôle)

**Comment by Ali-romdhani** [comment]
Bonjour, 
À Rennes ont utilise des cartes de membres avec codes barres, sera-t-il possible de les associés aux comptes des adhérents et de les faire fonctionner avec le lecteur de carte ?
Merci

**Comment by museOnSite** [comment]
Salut,
Nous allons prochainement retoucher la fonctionnalité car nous allons aussi commander des badges à codes barres. Mais je ne peux pas te donner de délai.

**Comment by janssens** [comment]
@Ali-romdhani vos codes ont quel format ? EAN13 ?

**Comment by Ali-romdhani** [comment]
Oui EAN 13 et commencent tous par 042

**Comment by janssens** [comment]
done

**Comment by Ali-romdhani** [comment]
Yeah merci !
