### ISSUE TITLE
séparer le bundle de sa distribution ?

### ISSUE THREAD

**Issue by lunika** [elefan-grenoble/gestion-compte#275]
Bonjour,

je vais être amené à déployer cette application, je ne me suis pas encore vraiment plongé dedans, vous m'excuserez si je suis à côté de la plaque.

L'application est donc à la base une `symfony-standard` dans laquelle a été développé un bundle et mis à disposition tel quel.

Et du coup j'ai plusieurs questions qui me viennent à l'esprit, notamment parceque je pense être confronté à certaines d'entre elles : 

- Pourquoi ne pas avoir choisi de distribuer directement le Bundle ? 
- Comment faire pour étendre l'application, rajouter d'autres fonctions sans casser les futurs mises à jour ?

Merci pour vos retours.

**Comment by Arakmar** [comment]
Je n'étais pas là au début du développement mais l'un des buts de ce projet est de fournir une solution clé en main pour les coop qui veulent un outil de gestion de leurs membres et du bénévolat.
Toutes les coop n'ont pas forcément les compétences pour intégrer un bundle.

Il est vrai que le projet contient beaucoup de spécificités liées à l'Elefan mais nous essayons le plus possible de les rendre paramétrables pour s'adapter aux besoins de tous.
Nous sommes également ouverts à intégrer de nouvelles fonctionnalités spécifiques à certaines coop, tant qu'elles restent un minimum réutilisables par d'autres.

Quelles fonctionnalités ou changements es-tu susceptible de devoir développer ?

Je te rejoins pour l'approche avec un bundle, cela permettrait pour ceux qui veulent d'éviter de forker le projet puis de le maintenir à jour. L'idéal serait de découper notre projet en deux, le bundle et un autre projet intégrant ce bundle.

Mais cela représente de gros travaux, notamment concernant la partie templating du projet qui n'est actuellement pas du tout conçue dans cette optique là. On en discutait il y a quelque jours avec @museOnSite, à terme on peut aussi envisager de passer sur une stack frontend type Angular ce qui rendrait le projet bien plus réutilisable, tant niveau back que front.

**Comment by lunika** [comment]
> Quelles fonctionnalités ou changements es-tu susceptible de devoir développer ?

Dans un premier temps faire une passerelle avec notre logiciel de caisse afin de synchroniser les utilisateurs dessus. Quand un nouveau membre est enregistré ça le met dans le logiciel de caisse.

**Comment by museOnSite** [comment]
Pour faire cela je pense qu'il faudrait créer un EventListener écoutant l'événement _MemberCreatedEvent_ (exemple dans _EmailingEventListener.onMemberCreated_).
Par contre comme ce sera un truc spécifique à une coop je ne sais pas trop comment intégrer ça. @Arakmar saura peut-être mieux répondre sur ce point.

**Comment by lunika** [comment]
> L'idéal serait de découper notre projet en deux, le bundle et un autre projet intégrant ce bundle.

Faudrait regarder ce que font d'autres projets qui ont cette approche, il y a des projets importants quand même dans l'univers symfony qui ont leur propre distribution, je pense notamment à akeneo, oro commerce, sylius. Je pense que tous ceux cités ont leur propre distribution qui est à l'image de la distribution `symfony-standard`.
Il y a certainement à travail à faire lors de l'installation, peut-être en utilisant les `post-install` hook de composer.

**Comment by janssens** [comment]
hello @lunika 
Alors je dirais en effet comme Yoann, l'app est pensée plus comme une solution clés en main, comme un tout.
D'ailleurs sur symfony 4 c'est plus clair car il n'y a pas de dossier bundle simplement un dossier src.
Développer sous la forme d'un bundle est une chouette option mais cela demanderai en effet un effort considérable sur l'existant.

La philosophie est donc plutôt de faire évoluer la solution pour quelle correspondent à tout le monde.

Pour ta demande de lien à la création d'utilisateur, peux être faire un autre ticket. 
A voir comment se comporte ton autre application caisse (API ?) et ce qu'on peux proposer qui puisse être réutilisable.

**Comment by lunika** [comment]
> La philosophie est donc plutôt de faire évoluer la solution pour quelle correspondent à tout le monde.

Et c'est une très bonne chose, nous contribuerons pour aller dans ce sens.

> Pour ta demande de lien à la création d'utilisateur, peux être faire un autre ticket.
> A voir comment se comporte ton autre application caisse (API ?) et ce qu'on peux proposer qui puisse être réutilisable.

Nous sommes en discussions avec l'éditeur du logiciel de caisse pour savoir comment procéder. Dès que nous en savons plus je vous tiens au courant.

Merci.
