### ISSUE TITLE
Choix d'un poste sur un créneau

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#287]
Bonjour,
À Rennes nous utilisons beaucoup d'étiquettes de formations, et donc plusieurs postes sur un créneau. Aujourd'hui, un utilisateur qui a fait plusieurs formations ne peut pas choisir quel poste il veut remplir sur un créneau.

Par exemple : 
Jean à trois formations : intégration, bénévole ressource et cariste.
Le créneau du lundi 16h-19h à besoin de 3 bénévoles intégration, 1 bénévole ressource et 2 cariste.
-> Jean ne peut pas choisir quel poste il rempli. 
Il me semble que actuellement, l'espace membre lui attribu un poste de manière aléatoire, ou d'une manière que je n'ai pas compris.

**Comment by museOnSite** [comment]
Salut,

Nous ne sommes jamais tombé sur ton problème car nous n'avons jamais plusieurs formations différentes sur un même créneau.

Pour gérer votre cas de figure il faudrait effectivement rajouter dans l'interface un moyen pour le bénévole de choisir quel poste qualifié il souhaite tenir.
