### ISSUE TITLE
Identifier les personnes qui ne font pas leurs créneaux

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#288]
Bonjour,
À moins que je me trompe, aujourd'hui il n'y a pas de manière de filter les adhérents qui n'ont pas fait leurs créneaux, autre que par le système de scan de la carte de membre (que nous n'utilisons pas).
Il est bien sure possible de voir un par un sur les fiches de membres, mais ce n'est pas une solution pérenne pour gérer des centaines de membres.

Est-ce possible de rajouter un filtre pour identifier facilement ces personnes ?

**Comment by museOnSite** [comment]
Salut,

On a déjà une issue ouverte là-dessus mais qui n'est pas dans nos priorités de développement.
On gère à la main, via des requêtes de ce style:

```
select m.member_number as member_number,
       l.logValue      as member_log
from registration r
       join membership m
            on m.id = r.membership_id
       join (SELECT membership_id, sum(time) as logValue FROM time_log GROUP BY membership_id) l
            on m.id = l.membership_id
where (now() between r.date and DATE_ADD(r.date, interval 1 year))
  and m.withdrawn = false
  and m.frozen = false
  and m.first_shift_date is not null
having member_log <= 0
order by member_number;
```



Duplicate of #68
