### ISSUE TITLE
Trier les co-titulaires

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#299]
Bonjour,
Dans "gerer les adhérents" il est possible de filtrer selon plusieurs critères, mais il n'est pas possible de trier les co-titulaire (les conjoints, coloc). 
Chez nous ça pose soucis, car uniquement les coopérateurs sont réellement en obligation de faire leur bénévolat.
On peut trier les co-titulaires avec Adminer, mais ça serait quand même plus pratique de pouvoir tout gérer depuis l'espace membre.
Merci.

**Comment by janssens** [comment]
Je ne suis pas sûr de comprendre.
Tu voudrais avoir uniquement les bénéficiaires principaux ? ou l'inverse ?
Chez nous il n'y a pas de différence entre les membres, les adhérents s'engagent ensemble à faire les 3h.
Peut-on imaginer une "étiquette" co-titulaire ? il y a un développement en attente pour pouvoir tagguer les membres et trier en fonction.

**Comment by Ali-romdhani** [comment]
C'est bien ça, nous faisons une distinction entre bénéficiares principaux et secondaires.

Tagguer les co-titulaires serait fastidieux et source d'erreur, mais reste sans doute l'option la plus simple pour l'instant.
