### ISSUE TITLE
Erreur 500 dans la page de paramètres personnels

### ISSUE THREAD

**Issue by bagheera2382** [elefan-grenoble/gestion-compte#301]
Sur la version 1.0 et 1.1 si un utilisateur qui n'a aucun badge va dans ses paramètres personnels (roue crantée en haut à droite) il obtient une erreur 500 :
`Attempted to call function "imagettftext" from namespace "CodeItNow\BarcodeBundle\Generator".`

Stack trace :
```
Symfony\Component\Debug\Exception\UndefinedFunctionException:
Attempted to call function "imagettftext" from namespace "CodeItNow\BarcodeBundle\Generator".

  at vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Generator/CINFontFile.php:205
  at CodeItNow\BarcodeBundle\Generator\CINFontFile->getBox()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Generator/CINFontFile.php:150)
  at CodeItNow\BarcodeBundle\Generator\CINFontFile->getDimension()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Generator/CINLabel.php:255)
  at CodeItNow\BarcodeBundle\Generator\CINLabel->getDimension()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Generator/CINean13.php:124)
  at CodeItNow\BarcodeBundle\Generator\CINean13->addDefaultLabel()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Generator/CINBarcode1D.php:142)
  at CodeItNow\BarcodeBundle\Generator\CINBarcode1D->parse('421234567890')
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Utils/BarcodeGenerator.php:278)
  at CodeItNow\BarcodeBundle\Utils\BarcodeGenerator->_getCode()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Utils/BarcodeGenerator.php:308)
  at CodeItNow\BarcodeBundle\Utils\BarcodeGenerator->_render()
     (vendor/codeitnowin/barcode/CodeItNow/BarcodeBundle/Utils/BarcodeGenerator.php:241)
  at CodeItNow\BarcodeBundle\Utils\BarcodeGenerator->generate()
     (src/AppBundle/Twig/Extension/AppExtension.php:226)
  at AppBundle\Twig\Extension\AppExtension->barcode('421234567890')
     (var/cache/dev/twig/c8/c841d9852f28ece0ad62d83851db6b06a1c90b4969f59b4011cd9305f6cb5645.php:165)
```

**Comment by Arakmar** [comment]
Salut,
Vérifie que tu as le module PHP gd installé et activé dans ta configuration PHP ?

**Comment by bagheera2382** [comment]
Salut, merci pour ton retour.
J'ai vérifié GD est bien installé sur le serveur et activé.
```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
```

**Comment by Arakmar** [comment]
C'est bizarre... Tu es sur quelle distribution ? Tu as installé PHP de quelle manière, via un dépôt tiers ?
La doc de PHP indique que imagettftext n'est disponible que si le module gd a été compilé en se servant de la lib freetype.

Est-ce que tu peux me mettre le retour complet de la partie relative à gd quand tu fais un php -i ?

De mon côté j'ai ça :
```
gd

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
**FreeType Support => enabled**
FreeType Linkage => with freetype
FreeType Version => 2.10.0
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.6.37
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

```

**Comment by bagheera2382** [comment]
J'utilise une image Docker de PHP avec Apache ([php:apache](https://docs.docker.com/samples/library/php/)) . J'ai un Dockerfile dans lequel j'installe (entre autres) gd.

La partie complète de gd que j'ai avec php -i :

```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
GIF Read Support => enabled
GIF Create Support => enabled
PNG Support => enabled
libPNG Version => 1.6.28
WBMP Support => enabled
XBM Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```
Je vais essayer avec un conteneur Nginx à tout hasard

**Comment by bagheera2382** [comment]
Ce que je trouve quand même bizarre c'est que si on a affecté un code EAN 13 à l'adhérent et générer le code barres, il n'y a plus d'erreur 500 (le code barre ne s'affiche pas mais je pense que ça vient simplement du fait que je n'ai pas mis le "tweak" indiqué dans la doc pour les urls dynamiques.

**Comment by bagheera2382** [comment]
Je crois que la bibliothèque FreeType est en effet manquante. Je vérifie si c'est bien ça le  souci.

**Comment by bagheera2382** [comment]
Je confirme : problème dû à l'absence de FreeType, merci de ton support @Arakmar (toujours au top !).
Et désolé pour ce faux problème.
