### ISSUE TITLE
[FEATURE] Vue Admin créneaux : voir le passé

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#31]
Ajouter la possibilité de voir et de modifier le passé sur la vue admin
(pas seulement les shift futur)

**Comment by museOnSite** [comment]
Jusqu'à quand doit-on pouvoir voir ?
On met un filtre non ?

**Comment by janssens** [comment]
par defaut en admin depuis le premier jour de la semaine en cours.
Au choix, les 28 jours suivant une date choisie : on affiche jamais plus de 28 jours.

**Comment by museOnSite** [comment]
Pour aller plus vite je vais déjà mettre ça en dur, et après on rajoutera le choix de la date dans l'interface
