### ISSUE TITLE
ERROR while importing CSV from console or /admin/importcsv

### ISSUE THREAD

**Issue by SebFalque** [elefan-grenoble/gestion-compte#316]
Dealing with 602 lines
   1/602 [>---------------------------]   0%22:48:30  ERROR     [console] Error thrown while running command "app:import:users --env=prod 'cooperateur_20190627.csv'". **Message: "Argument 1 passed to AppBundle\EventListener\BeneficiaryInitializationSubscriber::makeUser() must be an instance of Symfony\Component\Form\FormEvent, instance of AppBundle\Event\BeneficiaryCreatedEvent given**, called in /home/elefan/sites/gestion-compte/src/AppBundle/EventListener/BeneficiaryInitializationSubscriber.php on line 35" ["exception" => TypeError { …},"command" => "app:import:users --env=prod 'cooperateur_20190627.csv'","message" => "Argument 1 passed to AppBundle\EventListener\BeneficiaryInitializationSubscriber::makeUser() must be an instance of Symfony\Component\Form\FormEvent, instance of AppBundle\Event\BeneficiaryCreatedEvent given, called in /home/elefan/sites/gestion-compte/src/AppBundle/EventListener/BeneficiaryInitializationSubscriber.php on line 35"]

In BeneficiaryInitializationSubscriber.php line 43:

  Type error: Argument 1 passed to AppBundle\EventListener\BeneficiaryInitializationSubscriber::makeUser() must be an instance of Symfony\Component\Form\F
  ormEvent, instance of AppBundle\Event\BeneficiaryCreatedEvent given, called in /home/elefan/sites/gestion-compte/src/AppBundle/EventListener/Beneficiary
  InitializationSubscriber.php on line 35

app:import:users [-d|--delimiter [DELIMITER]] [-l|--limit [LIMIT]] [--default_mapping] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <file>

**Comment by Les400Coop-fr** [comment]
Bonsoir,
Nous avons fait quelques tests et modifications à la marge du code.
Nous réussissons à contourner la première erreur en changeant le type de la classe dont herite BeneficiaryCreatedEvent, de Event à FormEvent.

Mais nous avons une nouvelle erreur pour tout import manuel (CSV on console app:import:users) :
Dealing with 1 lines
 1/1 [============================] 100% < 1 sec18:19:50 ERROR     [console] Error thrown while running command "app:import:users 'cooperateur_20190627_premier.csv' --env=prod --verbose". Message: "Call to a member function setEmail() on null" ["exception" => Error { …},"command" => "app:import:users 'cooperateur_20190627_premier.csv' --env=prod --verbose","message" => "Call to a member function setEmail() on null"]

In Beneficiary.php line 220:

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function setEmail() on null


Exception trace:
 () at /home/elefan/sites/gestion-compte/src/AppBundle/Entity/Beneficiary.php:220
 AppBundle\Entity\Beneficiary->setEmail() at /home/elefan/sites/gestion-compte/src/AppBundle/Command/ImportUsersCommand.php:170
 AppBundle\Command\ImportUsersCommand->execute() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/elefan/sites/gestion-compte/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/elefan/sites/gestion-compte/bin/console:27

app:import:users [-d|--delimiter [DELIMITER]] [-l|--limit [LIMIT]] [--default_mapping] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <file>

**Comment by Les400Coop-fr** [comment]
Pourtant, une création d'adhésion via l'interface web (/member/new : NOUVELLE ADHESION) fonctionne parfaitement.
Voici le fichier que nous essayons d'insérer :

numero;nom;prénom ;adresse;complément;code postal;commune;telephone;email;commission;compte associé;date inscription;montant
1;Frémaux;Brigitte;84 rue de Reuilly;;75012;Paris;;bfremaux@yahoo.fr;;;27/06/19;100
2;Gouyer;Christophe;40 square Henri Sellier;;94220;Charenton le Pont;;ch.gouyer@laposte.net;;;27/06/19;100

**Comment by Les400Coop-fr** [comment]
Bonjour,
Nous sommes coincés. Nos efforts d'hier n'ont pas permis de resoudre le probleme...
Question aux autres projets (que l'Elefan), avez-vous utilisé recemment l'outil d'impprt CSV ?
Question à l'Elefan (@museonsite, @janssens) : des modificiation de code recentes (moins de 6 mois) peuvent-elles expliquer une regression sur l'import CSV de membres ?

**Comment by Arakmar** [comment]
Salut,
J'ai réussi à reproduire hier le problème de mon côté. Je pense que c'est lié à des changements d'il y a quelques mois sur les inscriptions. J'essaie de finir les corrections ce soir.

Par contre avec ton csv de 2 lignes sur une base clean j'ai beaucoup d'autres erreurs liées à doctrine (sur la table fos_user) . Tu les avais eues aussi ?

**Comment by Les400Coop-fr** [comment]
Bonjour Yoann,

Merci de t'être penché sur nos difficultés.

Hier nous avons tenté de corrigé le script d'import sur ce fichier
minimaliste (2 cooperateurs sur les plus de 600 que nous devons importer
pour un lancement demain), et après avoir contourné les premiers bugs nois
avons bien eu des erreurs de consistence des donnees en base (au moment de
persister les User) : nous avons abandonné car nous pensions justement que
nos tentatives de debugger etaient vaines car contraire a la facon de faire
pour la persistence des données qui suit.
Ta question me rend perplexe car je ne vois pas en quoi ce CSV hyper simple
pourrait causer des problèmes coté Doctrine (nous avons bien vu passer les
migrations lors de l'initialisation...)
Bien à toi.
Sébastien



Le dim. 30 juin 2019 à 12:18, Yoann Laissus <notifications@github.com> a
écrit :

**Comment by Arakmar** [comment]
J'ai fait une correction rapide dans cette branche pour vous débloquer : https://github.com/elefan-grenoble/gestion-compte/tree/bugfix/csv_import

Je vais réorganiser ça un peu plus en profondeur car à mon avis on a pas mal d'autres bugs dans d'autres cas de figure.
Hésite pas à nous remonter si tu as d'autres problèmes d'import ;)

**Comment by SebFalque** [comment]
Bonsoir,
Merci pour le fix ! ! Testé et concluant : 599 coopérateurs importés à l'instant.
Bonne soirée.
Sébastien et les 400 Coop
