### ISSUE TITLE
Incompréhension sur la gestion des cycles et des créneaux

### ISSUE THREAD

**Issue by lunika** [elefan-grenoble/gestion-compte#317]
Bonjour,

j'essaye de comprendre le fonctionnement des cycles et des créneaux et j'avoue que... je suis perdu !

Sur mon instance de test, je suis dans un cycle qui va du 18 juin au 15 juillet.

![Screenshot from 2019-06-30 11-47-15](https://user-images.githubusercontent.com/767834/60395012-3960f580-9b2d-11e9-9b9b-274b02721cd7.png)

Je me suis inscrit sur des créneaux les 2 et 9 juillet. Chaque créneau a une durée de 2h30 et la durée minimum à effectuer sur un cycle est de 2h30

```
due_duration_by_cycle: 150
```

![Screenshot from 2019-06-30 11-52-19](https://user-images.githubusercontent.com/767834/60395027-8cd34380-9b2d-11e9-8c18-9e3a23c49762.png)

J'ai toujours le message indiquant que je suis en retard sur mes contributions et qu'il faut que je réserve des créneaux. Ce qui ne me parait pas logique étant donné que je me suis inscrit pour 5h de bénévolat dans le cycle en cours.

![Screenshot from 2019-06-30 11-57-31](https://user-images.githubusercontent.com/767834/60395071-43cfbf00-9b2e-11e9-92b5-e1b8e07d87a9.png)

Un petit coup de main pour comprendre le fonctionnement des cycles et des créneaux ne serait pas de refus :-)

Merci

**Comment by janssens** [comment]
Il peut y avoir plusieurs raisons, mais je pense que ton compteur de temps est en négatif car tu dois avoir du retard sur les cycles précédents.

- S'inscrire à un créneau crédite le compteur temps.
- terminer un cycle débite le compteur de temps.

**Comment by lunika** [comment]
Merci pour la réponse.

Il n'est pas possible de s'inscrire à plusieurs contributions sur une même période ? Dès que le compteur est à 0 c'est fini on ne peut plus s'inscrire ?

**Comment by janssens** [comment]
le compteur peut monter à nb_beneficiary*due_duration_by_cycle
Concrètement pour une adhésion à 2 bénéficiaire avec des shifts de 3h, le compteur peut monter à 6.
Il retombera à 0 à la fin du cycle.

Il n'est donc pas possible d'anticiper du bénévolat, seulement de le rattraper. (un compteur négatif permet d'enchainer plusieurs shifts)

Comment fonctionnez vous dans votre projet ?

**Comment by lunika** [comment]
Il faut réaliser au minimum 2h30 par mois. Mais si quelqu'un souhaite faire plusieurs contributions et donc aller jusqu'à 5h ou plus il peut aussi.

Pour certains postes, notamment les référents qui ont plus de responsabilité, ils font plusieurs contirbutions par mois. Ils n'ont pas le choix car pas assez nombreux.

**Comment by janssens** [comment]
Ok. Ici à Grenoble ce n'est pas possible pour interdire le surinvestissement dont on ne saurait se passer.
Souhaite intégrer un fonctionnement "sans plafond" dans l'outil ?

**Comment by lunika** [comment]
> Souhaite intégrer un fonctionnement "sans plafond" dans l'outil ?

C'est facile à faire ? Rajouter un settings dans `parameters.yml` par exemple et s'en servir pour lister les créneaux ? Si tu me guides je peux essayer de faire la feature.

**Comment by janssens** [comment]
Comme ça, sans replonger dans le code je ne sais pas dire.
Il y a plusieurs chose à gerer : la jauge, le décrément (qui faire revenir à 0 en fin de cycle), les messages du type "vous pouvez encore reserver 3h", ... 
pas idéal pour débuter :)

Mais dans l'idée oui, un settings dans parameters, peut être "max_counter_value", à -1 pour illimité et 1 pour un shift/personne, etc...
