### ISSUE TITLE
Donner la possibilité de supprimer un créneau uniquement aux admins

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#318]
Bonjour, 
Pour l'instant, la possibilité de supprimer un créneau est donnée à tous ceux qui ont le rôle "shift_manager". À Breizhicoop, ce rôle est donnée à plusieurs dizaines de personnes (60 aujourd'hui) ce qui permet une gestion décentralisé du planning, mais augmente aussi les risques d'erreurs. Pour l'instant, ça nous ait arriver qu'une seule fois, mais ça me semble risqué de continuer ainsi.
Est-ce possible de donner cette option uniquement aux admins ?

**Comment by janssens** [comment]
Salut Ali,
Je ne comprends pas bien de quel façon vous utilisez ce rôle. 
Pour nous il est justement là pour donner la possibilité au utilisateur identifiés de faire les taches comme supprimer un créneau.
Que font les membres avec ce rôle chez vous ?
Ne pouvons nous pas préférer une modal de confirmation à la suppression ?

**Comment by Ali-romdhani** [comment]
Salut,
Chez nous les membres avec ce rôle ajoutent en enlèvent des gens sur les créneaux, mais jamais n'en suppriment.
Sinon une confirmation de suppression est une bonne alternative.

**Comment by janssens** [comment]
@Ali-romdhani confirmation ajoutée.
