### ISSUE TITLE
[FEATURE] faire évoluer le schema pour enregistrer la participation

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#32]
faire évoluer le modèle pour qu'on puisse savoir si un membre a été présent à l'épicerie pour faire son créneaux (heure de début / heure de fin ?)
A réfléchir

**Comment by museOnSite** [comment]
On est pas forcément obligé une fois qu'on affichera le planning dans le passé, si on rajoute la possibilité d'annuler le créneau à posteriori par un admin.

**Comment by janssens** [comment]
Gestion des retards et des départ anticipés : https://wiki.lelefan.org/index.php?title=Commission:gestion:creneaux#Retards
Cette feature va de paire avec la badgeuse.
De plus, de manière générale, les actions admin ne sont pas souhaitables plus que de raison : trop chronophage

**Comment by museOnSite** [comment]
Oui tu as tout à fait raison.
J'avais pas pensé à la badgeuse.

**Comment by museOnSite** [comment]
Du coup on attends que la badgeuse soit en place pour faire cette fonctionnalité non ?

On rajoute un booléen *done* dans la table *shift* ? (en mettant à true pour tous les créneaux *passés*?)

**Comment by janssens** [comment]
à discuter. 
car selon la politique il faudrait savoir si le créneau à été totalement réalisé ou juste partiellement. donc peut-être une heure "check in" et une heure "check out". on verra ça tous ensemble.

**Comment by museOnSite** [comment]
Proposition de Florent:
Enregistrement participation collective

**Comment by symartin** [comment]
réglé par la mise en place de la badgeuse.
