### ISSUE TITLE
Envoyer un mail aux membres d'un créneau

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#330]
À moins que je ne me trompe, pour l'instant c'est uniquement possible d'envoyer une mail à une équipe sur un créneau si l'on fait parti de ce créneau, et uniquement 48h à l'avance.

Il serait pratique de pouvoir envoyer un mail aux membres d'un créneau à partir de l'interface "gerer les créneaux" pour tous les créneaux.

**Comment by janssens** [comment]
Oui je valide,
peut-être plus sur la partie gestion de créneaux que sur la partie membre.

**Comment by janssens** [comment]
@Ali-romdhani Bouton ajouté sur l'admin des créneaux.
![image](https://user-images.githubusercontent.com/675464/64238409-a498c080-cefe-11e9-8897-ce273d4df612.png)

**Comment by Ali-romdhani** [comment]
Super merci !
