### ISSUE TITLE
[FEATURE] Utiliser des icones pour représenter les shifters

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#34]
Utiliser des icones pour représenter les shifters inscrit et avoir une meilleur compréhension du remplissage
personnages en ligne, noir pour occupé gris transparent pour libre ?

**Comment by museOnSite** [comment]
Oui ça me parait bien, en faisant se chevaucher légérement les icones pour gagner de la place.
Je vais essayer de faire ça.
