### ISSUE TITLE
Gérer différent type de compte membre

### ISSUE THREAD

**Issue by Arakmar** [elefan-grenoble/gestion-compte#343]
Pouvoir gérer au minimum les cas suivants :
- compte de type membre classique : fait ses créneaux régulièrement de manière classique
- compte de type associatif : adhésion avec montant libre au nom d'une autre association mais pas tenu de faire des créneaux

Le fonctionnement actuel est de geler les comptes.

**Comment by Ali-romdhani** [comment]
On pourrait élargir la proposition pour un fonctionnement en coopérative avec différent type de parts sociales. Pourquoi pas pouvoir personnaliser le champs "types" à l'adhésion.
