### ISSUE TITLE
Gestion commission

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#35]
Pour les référents :

- Ajouter la génération d'un lien d'invitation pour que les membres puissent rejoindre une commission.
- ~~Ajouter l'ajout manuelle d'un membre~~
- ~~Ajouter le retrait manuelle d'un membre~~

**Comment by janssens** [comment]
Bug : si un membre identifié comme référent quitte la comm, il reste référent et il est impossible, via l'interface, de modifier.

**Comment by museOnSite** [comment]
@janssens Tu es sûr ?

J'ai enlevé le rôle de référent à Florent B hier et j'ai l'impression que tout est ok ...
https://membres.lelefan.org/member/show/722

**Comment by janssens** [comment]
Pour reproduire, il faut que tu laisse un membre identifié comme référent de la com dans la com (ex Florent) puis que tu désinscrive ce membre de la com (que tu vire Florent de Gestion). 
Il reste alors bien identifié dans la com comme référent mais la liste déroulante ne propose pas son nom (elle ne propose que les membres de la com).
Voir sur la com Gouvernance en prod.

NB: A Grenoble on utilise des formation "referent","voisin", ... pour identifier les membres dans la liste, ce qui n'est pas une bonne pratique. Il y a un ticket pour ajouter la notion de tag.

Pour corriger le bug, plus propre je pense est de faire des events pour les changements (commission/formation/tag) et de faire un observeur qui supprime le lien "référent" si il existe en cas de désinscription à une com.

**Comment by janssens** [comment]
J'ajoute
>y'a t il une façon d'ajouter un membre à une commission avec le bouton "gérer les membres de la commission" en faisant une recherche par le nom ? (car la liste est dans le désordre)
Note : utiliser le FormType qui va bien (et qui n'existait pas à l'époque)

**Comment by symartin** [comment]
Les commission ne sont plus utilisé par l'éléfan et donc seront probablement très faiblement maintenu.
