### ISSUE TITLE
Afficher les personnes inscrites sur un créneau

### ISSUE THREAD

**Issue by lunika** [elefan-grenoble/gestion-compte#352]
Bonjour,

Actuellement lorsqu'un personne s'inscrit à sa contribution il n'est pas possible de voir les personnes déjà inscrites. C'est une demande récurrente à la coop des domes, nous fonctionnions ainsi avec notre ancien logiciel de réservation.
Aujourd'hui seul la vue admin permet d'accéder à cette information et les personnes faisant leur contribution ne sont pas admin, par conséquent il n'est pas possible de savoir qui va venir ensuite et pourvoir les contacter si besoin est. De même certains aiment se retrouver sur les même créneaux et s'inscrivent en fonction, c'est peut-être le choix qui vous a motivé pour ne pas afficher les noms ?

![Screenshot_2020-01-27 coop des domes](https://user-images.githubusercontent.com/767834/73176509-e8d66880-410c-11ea-8c06-e7fd7da76788.png)

Est-ce que c'est une fonctionnalité qui vous intéresse ? Si non prévoir via un settings dans le fichier `parameters.yml` la possibilité de activer/désactiver l'affichage des noms ?

Merci

**Comment by museOnSite** [comment]
Bonjour @lunika !
C'est effectivement un choix délibéré de notre part de ne pas afficher le nom des personnes sur l'écran de réserveration pour des raisons de "confidentialité". Il faudra donc effectivement pouvoir désactiver cette fonctionnalité si vous l'ajoutez.
Par contre on a eu un besoin un peu simlaire qui était d'afficher la liste des noms des bénévoles sur les créneaux en cours à l'épicerie. Cette page, qui sert aussi de support de communication pour les membres, est situé à sur l'URL *$base_url/cardReader*

**Comment by janssens** [comment]
L'idée philosophique derrière est de ne pas pouvoir discriminer, ni positivement ni négativement des membres : même si je n'aime pas beaucoup Bastien :heart_eyes: , rien ne me permet d'éviter les créneaux sur lesquels il est inscrit.

**Comment by museOnSite** [comment]
Je comprends mieux pourquoi on a jamais fait un créneau ensemble :thinking: :joy:

**Comment by MattBHub** [comment]
je t'ai envoyé un email @lunika  si la demande est encore d'actualité

**Comment by Meandres** [comment]
J'ai fait les modifications nécessaires à cet affichage. Je l'ai mis dans une PR avec d'autres trucs qu'on ne veut pas voir. #431 
L'IC ne passe pas pour une raison étrange.

**Comment by raphodn** [comment]
Salut @lunika et @MattBHub , cette fonctionnalité est disponible depuis fin 2022 (release v1.37.8) :)
Grâce à la PR #613 qui rajoute un nouveau paramètre `display_name_shifters`.

J'avais d'ailleurs créé une issue doublon - #600 - sans faire gaffe.
