### ISSUE TITLE
Gérer les adhérents erreur 500

### ISSUE THREAD

**Issue by avoineur** [elefan-grenoble/gestion-compte#353]
Bonjour à tous,

Je suis nouvel utilisateur du logiciel pour la coopérative La Mouette au Havre. J'ai repéré un bug dans la branche develop qui n'est pas présent dans la branche master.
Après avoir importé des membres à l'aide d'un csv, je me connecte en super admin et je clique sur 'Gérer les adhérents', et ça me donne cette erreur.

[Semantical Error] line 0, col 120 near 'lr LEFT JOIN': Error: Class AppBundle\Entity\Membership has no association named lastRegistration

IL s'agit d'une erreur SQL semble-t-il, j'ai joint une copie d'écran
![Capture d’écran de 2020-01-30 12-21-00](https://user-images.githubusercontent.com/60421887/73445568-419b4080-435b-11ea-833a-da2579605954.png)

EN espérant pouvoir contribuer au développement de ce super outil très bientôt!

Boris

**Comment by janssens** [comment]
Salut @avoineur je vais regarder ça rapidement, merci d'avoir fait remonter !
