### ISSUE TITLE
Comment mettre en service la page /cardReader

### ISSUE THREAD

**Issue by OursDesCavernes** [elefan-grenoble/gestion-compte#369]
Bonjour,

Je souhaite mettre en /cardReader pour contrôler les badge à l'entrée.
La page fonctionne et affiche le créneau en cours, mais comment faire pour scanner les badges ?
Quel scanner ?
Quelle integration entre le poste d'acceuil et le site ?

On est en v1.21.

Merci,
Thomas,
Les 400Coop

**Comment by museOnSite** [comment]
Salut,

Au préalable if faut activer un badge:
![Screenshot from 2020-03-11 16-45-37](https://user-images.githubusercontent.com/10038524/76500523-f50a5100-6440-11ea-8bd4-f29dedc78ce3.png)

Au niveau du scanner c'est une douchette à code barre classique de ce style:
![douchette](https://user-images.githubusercontent.com/10038524/76433762-145b9c80-63b5-11ea-9880-164085121e6d.jpg)

Ensuite il suffit de scanner une fois sur la page /cardReader, si cela correspond à un badge l'écran change automatiquement pour afficher l'état du bénévolat. Il me semble qu'il n'est pas nécessaire d'avoir un scanner, il doit être possible de tester en utilisant le clavier numérique (à vérifier).

Il est aussi possible de mettre du contenu sur la partie droite de la page /cardReader grâce aux contenus dynamique (admin > contenus dynamiques > Lecteur de cartes membres). Voilà ce que ça peut donner par exemple:
![Screenshot from 2020-03-12 09-12-06](https://user-images.githubusercontent.com/10038524/76500864-9beeed00-6441-11ea-96e8-1f8af8baf0f8.png)


Je ne comprends pas ta dernière question par contre.

**Comment by OursDesCavernes** [comment]
J'ai un associé un code EAN13 à mon compte,.
"Quelle integration entre le poste d'acceuil et le site ?"
Je veux dire que je n'ai pas trouvé ce qu'il fallait faire au niveau du navigateur ou de gestion-compte pour que la page /cardReader permette de lire un bagde. Je n'ai que le créneau en cours.

Pour l'instant je teste avec un clavier, on a pas encore acheté de douchette car on aura un autre problème derrière, les badges des 400coop sont en EAN8 (codes barres client pour Kaso), on investira quand on sera sûr que ça marchera.

**Comment by OursDesCavernes** [comment]
J'ai fait un test à la coop avec la douchette du PC de caisse sur /cardReader et il ne se passe rien quand je scan le code barre. Je pense qu'il manque un composant dans le navigateur qui affiche /cardReader.
Avez-vous fait une configuration/installation sur le PC pour que /cardReader réagisse à la douchette ?

**Comment by OursDesCavernes** [comment]
Quelqu'un a-t'il pu activer cette fonctionnalité ailleur que chez Elefan ?

**Comment by museOnSite** [comment]
Salut @OursDesCavernes !
As-tu déjà vérifié que la douchette fonctionne en scannant un code barre dans un éditeur de texte (style gedit) ?
Je ne crois pas que ce soit installé ailleurs qu'à l'éléfàn pour le moment (@janssens ?). D'ailleurs même chez nous ce n'est pas encore réellement utilisé, donc peut-être que la fonctionnalité a été cassée. Malheureusement je n'ai que peu accès à l'éléfàn avec le confinement donc je ne peux pas tester.

**Comment by thomasbauge** [comment]
Bonjour, 
j'arrive sûrement trop tard, mais ça pourra servir au suivant qui veulent tester :)
Nous regardons cette fonctionnalité chez nous aussi (breizhicoop Rennes) et j'ai simplement testé sans douchette pour l'instant : Ctrl+V sur la homepage suivi de "entrée" envoie bien vers la page cardReader.

**Comment by OursDesCavernes** [comment]
Bonjour,
Je viens de comprendre, il faut être sur la page d'acceuil pour que ça marche. Je testais sur la page cardReader ...
Du coup, ça marche ici aussi !
Merci pour l'info
