### ISSUE TITLE
Separateur de cycle affiché en double

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#37]
Probablement à cause de l'introduction des jobs sur les créneaux, le separateur de cycle s'affiche 2 fois.
![capture du 2018-03-04 16-50-16](https://user-images.githubusercontent.com/10038524/36947459-53adecb4-1fcc-11e8-9041-5dccfa9199bb.png)

**Comment by janssens** [comment]
Je l'avais repéré aussi celui là. Mais c'est pas réglé en 2 minutes, il faut repenser un peu le truc.

**Comment by museOnSite** [comment]
Si c'est bon je l'ai corrigé dans la branche que je suis en train de faire sur le planning (icônes etc.)
