### ISSUE TITLE
Mise en place d'Angular

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#378]
Mise en place d'Angular sur l'espace membre.
L'idée est de faire cohabiter les anciennes pages en Symfony/Twig et des pages Symfony/Angular (avec des ressources REST json pour la partie Symfony). 

J'ai initié une branche il y a quelques mois mais il faut reprendre pas mal de choses (mettre à jour sur la branche develop, mettre à jour la version d'angular, etc.)
https://github.com/elefan-grenoble/gestion-compte/tree/feature/angular
A noter que le plus simple est peut-être de repartir d'une nouvelle branche tirée du develop et de s'inspirer de ce qui a été fait.

**Comment by linkev44** [comment]
Salut, 
Je vais regarder ce qui a été fait prochainement et je te ferais un retour avant d'entreprendre quoi que ce soit. Je laisse déjà un lien ici vers un document qui a été également revu il y'a quelque temps par Antoine (le contrib Api Platform) qui a déjà servi pour initier avec des équipes plusieurs projets. (Stack NG6 / .net Core).  Elles dates un peu mais cela peut servir de base pour créer des préco pour Elefan. Antoine serait motivé pour vous accompagner sur la mise en place d'api platform si vous vous orientez vers ce choix.  Ou sur d'autres sujets symfony. 

https://docs.google.com/document/d/1W94BgMsb2DuaYdKGv9zn2JI3wlIJhiwzEPJpKysDPyo/edit?usp=sharing

**Comment by linkev44** [comment]
@museOnSite  j'ai enfin le temps de vous filer un coup de main sur le dev. J'ai une branche en local pour faire l'update vers ng 9 et structurer un peu plus le projet. j'aurais ensuite quelques questions pour continuer.
