### ISSUE TITLE
[FEATURE] Notes sur les utilisateur pour les ambassadeurs

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#38]
Pour faciliter le travail des ambassadeurs et le suivit des comptes membres : 
- Ajouter la possibilité pour un amba de consulter, d'ajouter, éditer, supprimer/clore des notes sur le profil adhérent.
- Ajouter la possibilité de consulter, d'éditer, ajouter et supprimer des notes sur son propre profil pour tous les utilisateurs
- Ajouter une notification interne ou un mail en cas d'ajout de note à son sujet
- permettre de répondre à une note (thread) ou a un post-it (note non attaché à un utilisateur).

NB: les notes existent déjà mais ne sont visible que sur le phoning pour le moment

**Comment by janssens** [comment]
NB: passer l'editer en textarea (post-it, notes)

**Comment by janssens** [comment]
@museOnSite tu fermes tout mais ya plein de truc pas terminé.
Comme là 
- Ajouter la possibilité de consulter, d'éditer, ajouter et supprimer des notes sur son propre profil pour tous les utilisateurs
- Ajouter une notification interne ou un mail en cas d'ajout de note à son sujet
Après je comprends le besoin d'air :)

**Comment by museOnSite** [comment]
Ah pardon je pensais que tout était fait déjà

**Comment by museOnSite** [comment]
On pourrait peut-être créer des issues spécifiques pour ces améliorations
