### ISSUE TITLE
Erreur 500 lorsqu'on annule son créneau en 1.26

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#384]
Dans la nouvelle version 1.26
J'inscris une personne sur un créneau puis la désinscrit depuis la page d'accueil : ça donne une erreur 500
J'ai testé sur notre espace membre de dev avec le compte superadmin en mode ninja.

**Comment by Ali-romdhani** [comment]
J'ai aussi testé avec un "vrai" compte (pas en mode ninja) et j'ai toujours le même problème

**Comment by mathiasjura** [comment]
Même problème à Lons en dev ... Que ce soit en admin pour un créneau à supprimer ou à libérer, ou en mode user pour libérer sa résa.

**Comment by bagheera2382** [comment]
Une exception PDO a priori :
"Column \'fixe\' cannot be null" au moment de faire le flush dans le BookingController
