### ISSUE TITLE
/cardReader renvoie vers /login au lieu de la page d'accueil

### ISSUE THREAD

**Issue by thomasbauge** [elefan-grenoble/gestion-compte#387]
Bonjour, 

Nous testons cette fonctionnalité pour comment (et si) nous la mettrons en place chez nous.
Après un simple test d'envoi de code-barres sur l'écran d'accueil : testé sans douchette pour l'instant avec Ctrl+V, puis entrée ; mais je pense que le comportement est le même quel que soit l'input
Une fois la page d'information affichée (en retard, créneau à réserver, surplu d'heures) que ce soit après le timeout ou en cliquant sur la croix en haut à droite : on revient sur https://[URL]/login au lieu de https://[URL]/

Est-il possible de retomber sur https://[URL]/ au retour du scan ? 
Aurions-nous raté une config quelque part ?

J'observe le même comportement en 1.24 (Prod) et 1.26.1 (dev)

Merci !
Tom // Breizhicoop Rennes

**Comment by MattBHub** [comment]
je viens de tester (version actuelle) et pour moi, une fois le badge scanné il y a une redirection vers https://[URL]/cardReader au bout de 10 secondes.
De la tu peux scanner un autre badge

**Comment by janssens** [comment]
Oui, il faut bien être sur https://mycoop.url/cardReader et pas seulement sur la home.
