### ISSUE TITLE
Installation serveur gestion-compte sur un environnement Windows

### ISSUE THREAD

**Issue by SandrineC** [elefan-grenoble/gestion-compte#399]
Bonjour,
La coop des Vénètes de Vannes m'a demandé de leur donner un coup de main pour la recherche et l'installation d'un gestionnaire de planning coopérateurs. Ils ont choisi un prestataire pour tout ce qui est compta/caisse/gestion des stocks. Il ne manque plus que le planning.
Nous pensons que la gestion de compte de l'Elefan pourrait satisfaire à leur besoin.
Je suis ingénieur logiciel spécialisée en base de données, je peux donc m'adapter aux différents environnement mais je ne suis pas familière avec le web (serveurs/php).
Dans un premier temps, j'aimerais installer sur mon PC un environnement qui me permettra de tester le gestionnaire (et l'installation).
Pourriez-vous me donner quelques conseils ?
Une solution comme XAMPP simplifiera peut-être la mise en place d'un environnement de test mais quels sont les versions PHP/composer/... qu'il faut absolument pour que tout fonctionne ?

**Comment by Arakmar** [comment]
Bonjour Sandrine,

Dans l'absolu ça devrait fonctionner sans problème sur Windows. Pour PHP on est rétrocompatible jusqu'en 7.1 si je ne me trompe pas mais je te recommande PHP 7.4 ou 7.3 selon ce que tu as de disponible. Pour composer, on est compatible 1.x et depuis très récemment 2.x.
Concernant la base de donnée, le dernier MariaDB ou MySQL devrait le faire mais je ne sais pas ce qui est proposé sur Windows pour ça...
Mais je pense que tu as des XAMP ou YAMP tout prêt avec tous ces outils.

Sinon tu peux aussi installer un Linux sur virtualbox (avec partage de fichiers) et développer comme ça, au moins tu es sûre d'avoir les bons outils.

Bon courage, développer sur windows c'est pas une partie de plaisir ;)

**Comment by SandrineC** [comment]
J'ai abandonné rapidement l'environnement Windows. Comme tu dis, trop compliqué pour un environnement de test ...
Je suis partie finalement sur une solution Linux VirtualBox !!!
Merci pour ton message ;-)
