### ISSUE TITLE
[bug] mauvais calcul de la date de début de cycle

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#40]
" Bonjour, j'ai effectué un créneau de 3h samedi dernier de 12h à 15h. Or ce matin en consultant le site, voice le message"
![image pasted at 2018-3-5 10-06 png](https://user-images.githubusercontent.com/675464/36970506-2410fd32-2069-11e8-9c16-501a9723339b.jpeg)

**Comment by museOnSite** [comment]
Origine du bug probablement situé dans la fonction startOfCycle($cycleIndex) de l'entité User

**Comment by janssens** [comment]
Je me demande si c'était pas la volonté de la personne qui l'a codé. @christopheswe ?
Est-ce que le 1er créneaux commence le lendemain du tout premier cycle, ou le jour même du 1er cycle ? en d'autre terme, est ce que le premier créneaux appartient au premier cycle ou non ?
Ce qui est certain, c'est que l'affichage avant d'avoir choisi un premier créneau doit être cohérent avec ce choix.

**Comment by janssens** [comment]
Non reproduit après la dernière mise en production

**Comment by museOnSite** [comment]
Non je pense pas que ce soit volontaire. C'est sûr que le premier créneau doit appartenir au 1er cycle.

**Comment by janssens** [comment]
Stephane, l'utilisateur, me dit que c'est encore le cas sur son compte.

**Comment by museOnSite** [comment]
Je n'arrive pas à reproduire le bug en local (voir screenshots). La seule possibilité que je vois, un problème de timezone.

![capture du 2018-03-09 23-42-09](https://user-images.githubusercontent.com/10038524/37233500-bc331a40-23f3-11e8-9791-189192caf68f.png)
![capture du 2018-03-09 23-42-42](https://user-images.githubusercontent.com/10038524/37233501-bc53eaa4-23f3-11e8-93ed-e192a62ddfb6.png)

**Comment by janssens** [comment]
très bonne piste la timezone, comment vérifier ?

**Comment by museOnSite** [comment]
Il faut changer la Timezone du système et redémarrer le navigateur.
Par contre il se peut que ce soit pas testable en local vu que MySQL, Symfony et le navigateur auront la même Timezone.
Il faut donc tester sur membres.lelefan.org.

**Comment by museOnSite** [comment]
Bon ben j'arrive non plus pas à reproduire en changeant la timezone.
@janssens Tu pourrais me filer le numéro de membre de Stéphane ?

**Comment by museOnSite** [comment]
Il ne voit pas ses créneaux passés parce que la date de début de cycle est mauvaise.
Sinon tu vois tous les créneaux du cycle en cours (passés ou pas).
Exemple sur mon compte:
![capture du 2018-03-11 22-05-05](https://user-images.githubusercontent.com/10038524/37258433-4b09a8bc-2578-11e8-8d03-c7d235f110ce.png)

**Comment by museOnSite** [comment]
Bug reproduit chez une autre membre (clorene74@hotmail.fr):
> J'étais surprise d'autant plus que j'ai fait mon créneau le 2/03 soit au début du cycle de l'ancien fonctionnement (planning mois de mars).
et je me retrouve avec un nouveau cycle qui début le 3/03 soit le lendemain ? donc le cycle d'avant s'est réduit à 3 jours. Je le signale car il y a certainement plein de personnes qui ont fait leur shift la première semaine de >mars qui se retrouvent dans cette situation (on doit faire 2 créneaux sur mars ?).

**Comment by janssens** [comment]
![image](https://user-images.githubusercontent.com/675464/37783473-e00b2316-2df5-11e8-911f-8a3e7977908a.png)

**Comment by fgougou** [comment]
Et pour compléter, là c'est redevenu normal 
![image](https://user-images.githubusercontent.com/36693586/37784515-469b91ea-2df8-11e8-9b66-943cd0f6b449.png)

**Comment by christopheswe** [comment]
J'ai essayé en local de reproduire le bug en modifiant la date de mon PC mais sans succès. Je suis à lelefan pour ma deuxième fermeture (après celle d'hier soir) et j'ai le même problème. Il me dit qu'il me manque 1h30 à faire en plus de ce soir. Il ne compte pas mon créneau d'hier. J'essaierai de me connecter demain matin pour voir.
![deepin capture-ecran_20180322192417](https://user-images.githubusercontent.com/32469669/37790502-0e3af8ae-2e07-11e8-9342-ac175c8b906a.png)

**Comment by christopheswe** [comment]
Et là c'est revenu dans l'ordre... bizarre

**Comment by christopheswe** [comment]
Ok bug corrigé dans la branche develop : vous pouvez tester ?
Correction de la fonction startOfCycle qui calculait un modulo entre deux dates dont les champs heure, minute, seconde n'étaient pas à zéro. Du coup si mon tout premier créneau commençait à 19h30 et que ma date courante était supérieure (entre minuit et 19h30) mon modulo était faux et donc ma date de début de cycle était augmentée de 1. Entre 19h30 et minuit (période pendant lesquelles on codait et testait) le modulo est correct et tout fonctionne. J'ai donc resetter les temps avant de faire cette comparaison. Une fois que vous confirmez que vous reproduisez le bug et que mon évolution corrige le truc, on peut mettre la correction en prod

**Comment by museOnSite** [comment]
C'est chiant à tester, je te fais confiance perso.
Par contre fait une pull-request la prochaine fois.

**Comment by christopheswe** [comment]
Je savais qu'il fallait en faire une mais j'en avais jamais fait donc j'ai corrigé crade comme auparavant directement en branche.

**Comment by janssens** [comment]
J'ai validé ton dev, ce qui est certain c'est que ça ne pouvais pas marcher sans ça. Et je me doutais bien que c'était un problème d'heure et pas de jour.
Mise en prod faite ce matin
