### ISSUE TITLE
Bug sur la création de badge

### ISSUE THREAD

**Issue by Ali-romdhani** [elefan-grenoble/gestion-compte#400]
Sur la v 1.27 un soucis de droit pour ceux qui veulent créer un badge à un autre membre :  les utilisateurs qui ont un badge ne peuvent pas donner un badge à un autre utilisateur.

Test mené avec le comte super admin. En mode ninja, deux utilisateurs (A et B) avec les mêmes droits (gestion utilisateur, gestion créneaux, gestion procédure), tentent de modifier le badge d'un autre utilisateur (C) : ça fonctionne pour le premier, mais pas pour le second. 

L'utilisateur C n'avait pas de badge. La seule différence, c'est que B avait un badge d'enregistré sur son compte.

Quand on ajoute un badge à A, lui aussi ne peut plus ajouter de badge à C

On obtient une erreur "tu n'as pas le droit de venir ici".

Ça vous semble logique ?

**Comment by Arakmar** [comment]
Effectivement y'avait bien un soucis si le user manager avait un badge. Merci !
