### ISSUE TITLE
Compatibilité composer 2.0

### ISSUE THREAD

**Issue by xavierdemaillard** [elefan-grenoble/gestion-compte#403]
Bonjour,
Serait-il possible de faire un petit upgrade pour assurer la compatibilité avec composer 2.x ?
Pour information, voici le retour lors d'un composer install avec composer 2.x

Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.5.1 and an update of this package was not requested.
    - ocramius/package-versions 1.5.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.5.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - doctrine/orm v2.7.3 requires ocramius/package-versions ^1.2 -> satisfiable by ocramius/package-versions[1.5.1].
    - doctrine/orm is locked to version v2.7.3 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.

Test réalisé sur une machine ubuntu 20.04 avec PHP 7.4

**Comment by xavierdemaillard** [comment]
Une solution potentielle pour s'assurer du bon fonctionnement est de passer ocramius/package-versions en version 1.9 directement dans le fichier composer.json (et non en dépendance de doctrine/orm), mais il faut impérativement faire un composer update au lieu d'instlall, donc cela peut avoir des effets de bord pas très agréable.

**Comment by Arakmar** [comment]
Bonjour Xavier,
J'ai fait un update général des dépendances et fixé monolog bundle en 3.5 pour le moment.
On est en train de migrer sur SF4 donc on va essayer de vivre comme ça le temps de la migration !
