### ISSUE TITLE
Impossible de s'inscrire à un créneau

### ISSUE THREAD

**Issue by Meandres** [elefan-grenoble/gestion-compte#409]
Je me suis occupé pour l'épicerie coopérative de Malain "La Tourniquette" d'installer ce logiciel. Merci beaucoup pour tout ce développement et pour cette documentation (les issues fermées sont très utiles aussi ;) )

Seulement pour une raison que j'ignore aucun des utilisateurs ne peut s'inscrire au créneaux créés. Ci-après un exemple : 

![image](https://user-images.githubusercontent.com/44814098/105698892-d7ce5c00-5f06-11eb-9df7-9ee704685fe4.png)

J'imagine que c'est juste moi qui n'ai pas compris comment cela fonctionnait mais cela me perturbe de ne pas arriver à me servir de la fonction principale du logiciel.

Pour infos : 
- la base est créée, migrée, tout me semble bon de ce côté
- aucune formation n'est nécessaire pour ces créneau donc pas de ce côté ?

Bref je ne vois pas. Merci de votre aide.

**Comment by ricosuavefr** [comment]
Bonjour,
Je rencontre la même problématique sans trouver la solution...
@Meandres si tu as résolu ce point, je suis preneur ;)
Merci par avance

**Comment by SandrineC** [comment]
dans parameters.yml
new_users_start_as_beginner: false

**Comment by ricosuavefr** [comment]
Merci Sandrine, ça fonctionne.
Ne pas oublier de relancer composer install pour prise en compte :)

**Comment by Meandres** [comment]
Merci de cette suggestion mais je crains que ça ne résolve pas le problème avec mon installation. Une personne disposant de toutes les formations ne peut même pas acceder à des créneaux prévus pour de simples "membres".
Comment vous faites chez vous @ricosuavefr ? Vous avez mis en place le système de formations ou tout le monde peut tout faire ?

Sinon plus généralement comment cela-se fait-il que cette option (new_users_start_as_beginner) existe ? Dans quels cas peut-elle se révéler utile ?
