### ISSUE TITLE
[bug] possibilité par le même membre de réserver un créneaux qu'il vient d'annuler

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#42]
Vu en prod
"J'ai encore un créneau à faire sur la période en cours mais le tableau est bloqué et je ne peux trouver quand venir. "
![selection_009](https://user-images.githubusercontent.com/675464/37161025-e6e66114-22f1-11e8-918e-74f16a87da76.png)

**Comment by museOnSite** [comment]
De ce que je comprends il faut bloquer dans le planning la possibilité de se retrouver dans la situation ci-dessus.
Par contre, est-ce qu'on developpe la fonctionnalité qui permet d'annuler l'annulation ? :)

**Comment by museOnSite** [comment]
J'arrive pas à reproduire, à mon avis ça a été corrigé via un autre bug

**Comment by janssens** [comment]
"Par contre, est-ce qu'on developpe la fonctionnalité qui permet d'annuler l'annulation ? :)" => oui

**Comment by museOnSite** [comment]
OK je créé l'issue
