### ISSUE TITLE
Gestion des membres sans addresse email

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#45]
Lorsqu'il n'y a pas d'addresse email sur un bénéficiaire, on ne sait pas si c'est normal ou pas.
Cela peut générer des appels téléphoniques inutiles.

Pourra être géré avec la fonctionnalité de notes ? #38 

Exemple: Adhérente 1255

**Comment by janssens** [comment]
J'allais justement créer une feature.
J'y réfléchi depuis le début de cette version de l'espace membre. 
Je pense que c'est une bonne chose de pouvoir gérer les membres sans emails : (personnes agées comme cette dame, ou tout simplement quelqu'un qui ne souhaite pas le communiquer)
En effet, actuellement la nomenclature utilisée (et non documentée) membres+NUM@lelefan.org loge tous les membres à la même enseigne : email manquant.
A discuter, mais en attendant effectivement, le gérer avec les notes est bien.
