### ISSUE TITLE
dépendance barcode-generator inaccessible

### ISSUE THREAD

**Issue by PierreMacherel** [elefan-grenoble/gestion-compte#458]
Bonjour,
La dépendance `barcode generators` listée dans `composer.json` n'est plus accessible. En effet, le répertoire https://github.com/codeitnowin/barcode-generator est `unavailable due to DMCA takedown`.
Cela rend l'installation impossible.

**Comment by guillett** [comment]
Je confirme, même expérience de mon côté et vue ma faible expérience en PHP je ne sais pas comment contourner ce problème.

**Comment by raphodn** [comment]
On se penche dessus la semaine prochaine 🤞

**Comment by raphodn** [comment]
un packet a été "dupliqué" à partir de celui qu'on utilise
https://packagist.org/packages/asmshaon/easy-barcode-generator

cc @symartin

**Comment by raphodn** [comment]
@PierreMacherel @guillett on a remplacé par une lib alternative, dites-nous si ca coince toujours

**Comment by PierreMacherel** [comment]
J'ai toujours une erreur (cf [log.txt](https://github.com/elefan-grenoble/gestion-compte/files/9354724/log.txt)) sur la commande `docker-compose up`.
Le fichier `composer.lock` fait toujours référence au package `codeitnowin/barcode-generator`. Il semblerait qu'il ait la précédence sur le fichier `composer.json`. J'essaierais de régénérer le fichier  `composer.lock` demain.

**Comment by raphodn** [comment]
en effet @PierreMacherel @guillett j'étais allé trop vite :sweat_smile: 
nouvelle PR #473 pour réparer ça une bonne fois pour toute :)
