### ISSUE TITLE
Mise à jour de Materialize CSS

### ISSUE THREAD

**Issue by symartin** [elefan-grenoble/gestion-compte#468]
Le code d'origine n'est plus maintenu : 
-> https://github.com/Dogfalo/materialize/issues/6243
-> https://github.com/Dogfalo/materialize/issues/6615

Un nouveau fork existe et est plus ou moins maintenu : 
https://github.com/materializecss/materialize

le bundle 'evheniy/materialize-bundle' n’est plus maintenu et n'est de tout façon pas utiliser dans le code (cf app/Resources/views/layout.html.twig) pas utiliser dans le code, le package directement dans les assets dans /web/bundles/app/materialize, mais pas à jour.

**Comment by raphodn** [comment]
la dernière version est la v1.1.0 : https://github.com/materializecss/materialize/releases/tag/1.1.0

**Comment by raphodn** [comment]
Les plus gros changements
- le padding des `.btn` a diminué 
- la font des input a changé
- `data-html` ne marche plus avec `data-tooltip` :thinking: 
-

**Comment by raphodn** [comment]
Reste à faire : 
- retirer `evheniy/materialize-bundle` du `composer.json`
- mettre à jour jQuery ? #464

**Comment by raphodn** [comment]
Je découvre enfin ce doc de migration :cry: 
https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

**Comment by raphodn** [comment]
Recap des PR liées à cette issue : 
- https://github.com/elefan-grenoble/gestion-compte/pull/515
- https://github.com/elefan-grenoble/gestion-compte/pull/519
- https://github.com/elefan-grenoble/gestion-compte/pull/522
- https://github.com/elefan-grenoble/gestion-compte/pull/529
- https://github.com/elefan-grenoble/gestion-compte/pull/530

**Comment by raphodn** [comment]
TODO : 
- refaire une passe sur les "chips"

**Comment by raphodn** [comment]
v1.2.0 vient de sortir : https://github.com/materializecss/materialize/releases/tag/1.2.0
