### ISSUE TITLE
[FEATURE] Jour férié, fermeture exceptionnelles, créneaux exceptionnels

### ISSUE THREAD

**Issue by janssens** [elefan-grenoble/gestion-compte#47]
Afin d'anticiper les fermetures (jours fériés, ...) et les changement de planning (absence de salarier, ...) il faudrait pouvoir créer, à partir de la semaine type, des exceptions.
Schema BDD à imaginer.
J'imagine une liste de jour exception et un lien avec l'entité périod.
le générateur check alors si le jour à généré est une exception ou non avant de charger les périodes associés et de créer les shifts. a discuter.

**Comment by museOnSite** [comment]
+1 pour la solution proposée

**Comment by janssens** [comment]
Needed ! 
Ajouter la possibilité aux créneaux type d'une fréquence bi hebdomadaire (semaines paire, semaines impaire)

**Comment by Arakmar** [comment]
@janssens C'est pas totalement fini mais j'ai pas mal avancé sur ta branche des exceptions (Nouvelle ici : https://github.com/elefan-grenoble/gestion-compte/tree/feature/%2347-exceptions-v2). J'ai dû retoucher un peu le modèle en décorrélant les Period des Exceptions.
Sinon ça pose plusieurs problèmes :
- C'est pas cohérent d'avoir une Period liée à une PeriodException comme une Period est valable pour un jour de la semaine et la PeriodException sur une date précise. Ça change donc d'une année à l'autre et c'est également pas envisageable si on veut mettre en places des exceptions périodiques.
- Pour l'ajout de Shift exceptionnels, on ne peut pas se baser sur des Period comme ça peut être à des heures différentes de celles que l'on retrouve dans les Period.

Du coup je me retrouve avec une entité PeriodException (peut être à renommer ?) avec juste une date de début et fin (l'heure de début et fin fonctionnent aussi).

J'ai rajouté plusieurs éléments :
- Notion de périodicité de l'exception : aucune, annuel, mensuel, hebdo et quotidien (bi-mensuel à réfléchir, je crois qu'on en avait besoin)
- Type d'exception : ajout de shift / exclusion de Period
- Raison de l'exception : exemple : Jour férié, Congé de Charlotte. J'ai créé une entité pour ça car ça peut permettre de plus facilement contrôler les types d'exception qu'on a. Un champ string pourrait aussi très bien faire l'affaire.
- Champs utilisés pour l'ajout de créneau : lien vers un Job et une Formation

Qu'est ce que vous en pensez ?

J'ai intégré ça dans la commande de génération des shifts et ça marche plutôt pas mal d'après mes tests.
La requête pour la périodicité est impressionnante mais elle est suffisamment décomposée pour être compréhensible :)

Pour les ajouts de shifts exceptionnels il faut qu'on voit ce qu'on veut exactement. Pour le moment j'ai ajouté des champs Job et Formation pour reprendre le même fonctionnement que les PeriodPosition, à voir si ça suffit.
A voir aussi comment on ajoute ces shifts "exceptionnels" si les shifts pendant cette période ont déjà été générés. Pour ceux d'après, on pourra y intégrer facilement à la commande de génération.

**Comment by janssens** [comment]
Cool taf,
Dommage que je n'ai pas eut le temps de t'expliquer ce que j'avais en tête avant.
period = "créneau horaire".
En fait le but n'est pas de lies des period existantes a une periodException, mais de créer de **nouvelles** periods, non rattaché à un jour de semaine (day_of_week=null), mais attaché à une periodException.
De créer donc "un jour type" pour une date donnée (mon entité exception).
J'aurais alors commencé "petits bras" avec juste une date, avant de traiter la récurrence plus tard (en faisant évolué l'entité exception). La periode reste lié à une exception, qui devient alors ponctuelle ou récurente.
Le plus propre serait alors de faire un class mère AbstractPeriod de laquelle hérite deux classes, la periode régulière liée à un jour de semaine, et la période exceptionnelle, lié à une exception.

D'ou mon idée, en plus de demander la date et la récurrence, de demander si oui on non on souhaitait copier les période du jour type dans le jour exception (juste une modification) ou non (un nouveau jour ou un jour vide).

Je n'avais pas envisagé la façon avec laquelle tu as abordé ça, (date de début date de fin)... je ne sais pas ce qui est le mieux.

Pour la périodicité, annuel c'est quoi ? même jour de l'année = même date ?
Idem mensuel ? 2ème mercredi ? ou tous les 10 du mois ?
C'est compliqué à gérer cette chose, je pense qu'il existe des design tout fait sur le net. j'ai fait quelques recherche sans succès. Il y a la notion de periodicité, et d'aniversaire, ex : le 3ème lundi tous les mois. ou le premier mai tous les ans.
Et idéalement il faudrait sortir cet "outil", dans un service ou une entity autre, je sais pas comment c'est possible, pour qu'on puisse le réutiliser ailleurs (exemple sur les date de réunion). ??

**Comment by Arakmar** [comment]
Ah oui effectivement j'avais vraiment rien compris ;)
Du coup si j'ai bien suivi c'est assez similaire à mon entité PeriodException (mis à part la date de début et fin) mais en séparant la partie intervalle temps dans une Period "spéciale" à la place.

Ça résoudrait effectivement une grosse limite de mon approche qui ne permet pas de gérer par exemple une exception uniquement entre 9h et 12h sur un intervalle de 3 jours.
Il aurait fallu pour cela séparer l'heure de la date dans des champs différents.

Je pense qu'il faut qu'on pose tout ça sur un uml et qu'on en discute. En combinant les bonnes idées des deux approches, on devrait tenir quelque chose de pas mal :)
Je vais essayer d'y réfléchir dans les jours qu'arrivent.

Pour la récurrence :
- Annuelle : Les mêmes jours chaque année sur l'intervalle (26/11 -> 27/11 = ceux deux jours là de chaque année)
- Mensuelle : Les mêmes jours chaque mois sur l'intervalle (26/11 -> 27/11 = 26 et 27 de chaque mois)
- Hebdo : Les même jours de la semaine sur l'intervalle défini (26/11 -> 27/11 = Lundi et mardi pour toutes les semaines)
- Quotidienne : La même plage horaire chaque jour (La date n'est pas prise en compte)

Ma solution est loin d'être optimale pour la récurrence et il faut surement l'améliorer. Je me demande si avoir d'autres tables ou d'autres champs aurait pas été une meilleure idée que de se baser uniquement sur deux dates pour tous les calculs.
Mais au pire comme tu dis, on peut commencer sans et y faire évoluer après y avoir mieux réfléchi.

Le champ "type" que j'avais mis dans PeriodException était justement là pour gérer d'autres cas de figure, comme la recopie ou non des créneaux par exemple (pas encore implémenté) mais on peut imaginer plein de choses si on rend l'entité suffisamment générique.

**Comment by janssens** [comment]
Je propose d'ajouter une entity pour gerer la récurence. Cette dernière poura être utilisée pour la date des réunions de commission aussi (exemple pour nous, mardi toutes les 4 semaine).
Le système de google doc est pas mal.

![image](https://user-images.githubusercontent.com/675464/53409756-12998380-39c2-11e9-9405-2abc6bd812be.png)
![image](https://user-images.githubusercontent.com/675464/53409810-44aae580-39c2-11e9-8218-82a43996e398.png)
![image](https://user-images.githubusercontent.com/675464/53409838-54c2c500-39c2-11e9-8e68-b949cf756567.png)
![image](https://user-images.githubusercontent.com/675464/53409854-5f7d5a00-39c2-11e9-8706-e5829492f5cc.png)

firstday (ex: 25-02-2019 date du premier évenement)
lastday (ex: 25-02-2020 date du dernier évenement, laisser null si sans fin)
recurence (ex: 2, toutes les 2 semaines, tous les 2 jours, tous les 2 ans)
frequency (daily, weekly, monthly, yearly)
byday (facultatif, uniquement si c'est par mois (monthly) est-ce que c'est tous les 3ème mardi ou tous les 26... ex: -1WE dernière semaine, +2WE deuxième semaine)
