### ISSUE TITLE
Vue admin des créneaux illisible

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#48]
Vue admin des créneaux illisible (surtout sur petits écrans). Les heures à la verticale ne sont pas pratique à lire.

Amélioration possible en implémentant ce qui a été fait sur la vue pour les membres.

Je propose de mettre des icones comme sur la vue membre et d'enlever les noms des inscrits (accessibles dans la popup). 
Ou alors on peut laisser uniquement le nom du benevole avec le role (resource ou ambassadeur).

**Comment by janssens** [comment]
Je suis d'accord, les heures verticalse ne fonctionnent pas aussi bien que ce que je pensais en l'implémentant.
par contre je suis pour la jouer **responsive** : si la place le permet (c'est le cas sur mon 15" rétina et sur le 32' que j'ai à la maison off course) afficher plus d'info. et sur les petits écrans, en faire moins comme tu le suggère.
utiliser toute la largeur comme ce qui a été fait pour la vue membre est une première étape nécessaire comme tu dis.
Penser aussi à un système, à implémenter aussi sur la vue membre, pour différencier les types de créneaux : les bénévoles ressource et amba doivent pouvoir identifier les postes qualifiés des autres.
