### ISSUE TITLE
aurtograffffe

### ISSUE THREAD

**Issue by henrisamson** [elefan-grenoble/gestion-compte#5]
Oups, erreur de saisie, nous n'avons pas enregistré d'adhésion pour ***se**** compte. 
Oups, erreur de saisie, nous n'avons pas enregistré d'adhésion pour ***ce**** compte.

**Comment by henrisamson** [comment]
http://membres-preprod.lelefan.org/4/confirm?beneficiary=5

**Comment by janssens** [comment]
ok
