### ISSUE TITLE
Table swipe_card_log : Ajout du beneficiary_Id ou du numéro du badge

### ISSUE THREAD

**Issue by SabineJa** [elefan-grenoble/gestion-compte#509]
Dans la table swipe_card_log, les scan de badge sont aujourd’hui anonymes. On a juste le compteur.
Serait-il possible d’avoir - de manière optionnelle dans la table des paramètres - le beneficiary_Id ou  le numéro du badge afin de savoir qui vient faire ses courses au magasin ?

**Comment by raphodn** [comment]
Salut Sabine :wave: 

en effet on a fait le choix (à l'Elefan) de rendre ça anonyme.
mais on peut réflechir ensemble pour rajouter ce champ en effet, et rendre son remplissage optionnel en fonction d'un paramètre.

est-ce que tu serais en mesure de proposer une PR ? de notre coté on est pas mal occupé par d'autres tâches, peu de chances que cela soit fait rapidement...

Tu fais partie de quelle coop ?

Merci !

**Comment by raphodn** [comment]
@SabineJa la PR a été mergée sur master ! on fera une release sometime ce weekend, mais vous pouvez déjà tester et nous faire un retour.
- la table a été recrée, donc vous perdrez l'historique si vous ne faites pas de backup.
- c'est possible qu'il y ait des bugs... je n'ai pas testé

**Comment by raphodn** [comment]
et un commit additionnel qui répare certains bugs : https://github.com/elefan-grenoble/gestion-compte/commit/38375f1353d4d8ba0ec5b77389d10ea990370b9c

il faut prendre la release https://github.com/elefan-grenoble/gestion-compte/releases/tag/v1.37.2

**Comment by SabineJa** [comment]
Bonsoir

 

Super rapide  😀 ! 

On installe la release et on vous fait un retour

Merci beaucoup

Sabine

 

De : Raphael Odini ***@***.***> 
Envoyé : lundi 31 octobre 2022 10:21
À : elefan-grenoble/gestion-compte ***@***.***>
Cc : SabineJa ***@***.***>; Mention ***@***.***>
Objet : Re: [elefan-grenoble/gestion-compte] Table swipe_card_log : Ajout du beneficiary_Id ou du numéro du badge (Issue #509)

 

et un commit additionnel qui répare certains bugs :  <https://github.com/elefan-grenoble/gestion-compte/commit/38375f1353d4d8ba0ec5b77389d10ea990370b9c> 38375f1

il faut prendre la release https://github.com/elefan-grenoble/gestion-compte/releases/tag/v1.37.2

**Comment by SabineJa** [comment]
Bonjour

 

On a installé la dernière release dans notre environnement d’intégration et testé les 2 évolutions que nous vous avions demandées (Issue #509 et #568) 

Ça marche nickel ! C’est parfait 👍

Merci beaucoup 

Sabine

POP La coop 

 

 

De : ***@***.*** ***@***.***> 
Envoyé : lundi 31 octobre 2022 23:00
À : 'elefan-grenoble/gestion-compte' ***@***.***>; 'elefan-grenoble/gestion-compte' ***@***.***>
Cc : 'Mention' ***@***.***>
Objet : RE: [elefan-grenoble/gestion-compte] Table swipe_card_log : Ajout du beneficiary_Id ou du numéro du badge (Issue #509)

 

Bonsoir

 

Super rapide  😀 ! 

On installe la release et on vous fait un retour

Merci beaucoup

Sabine

 

De : Raphael Odini ***@***.*** ***@***.***> > 
Envoyé : lundi 31 octobre 2022 10:21
À : elefan-grenoble/gestion-compte ***@***.*** ***@***.***> >
Cc : SabineJa ***@***.*** ***@***.***> >; Mention ***@***.*** ***@***.***> >
Objet : Re: [elefan-grenoble/gestion-compte] Table swipe_card_log : Ajout du beneficiary_Id ou du numéro du badge (Issue #509)

 

et un commit additionnel qui répare certains bugs :  <https://github.com/elefan-grenoble/gestion-compte/commit/38375f1353d4d8ba0ec5b77389d10ea990370b9c> 38375f1

il faut prendre la release https://github.com/elefan-grenoble/gestion-compte/releases/tag/v1.37.2

**Comment by raphodn** [comment]
Top ! C'était une bonne idée l'affichage des log de temps, on s'en sert aussi du coup :)
