### ISSUE TITLE
Pouvoir séparer un bénéficiaire d'un membre (et lui créer un nouveau membre autonome)

### ISSUE THREAD

**Issue by symartin** [elefan-grenoble/gestion-compte#510]

**Comment by raphodn** [comment]
Est-ce que ca serait utilise aussi de pouvoir "inverser un membre et un bénéficiaire" ?

Ou est-ce que peut-être dans cette issue on pourra sélectionner le bénéficiaire qui sera "nouveau" du bénéficiaire qui "gardera l'historique" ? :)
