### ISSUE TITLE
Disparition des radiobox et de l'autocomplétion ap MAJ de Materialize CSS

### ISSUE THREAD

**Issue by symartin** [elefan-grenoble/gestion-compte#520]
Autre bug detecté depuis la MAJ de Materialize, les radiobox ont disparu et l’autocomplétion ne fonction plus sur /booking/admin (détecté sur chrome et Firefox sur windows):

![bug_materialiaze_radiobox](https://user-images.githubusercontent.com/31699829/193099171-f10e7268-02fa-4cf2-a081-289404beb49f.jpg)

**Comment by raphodn** [comment]
pour les radio c'est une histoire de label qui doit englober l'input, c'est facile à réparer :ok_hand:

**Comment by raphodn** [comment]
pour l'autocomplete, c'est plus compliqué..
- ca ne fonctionne plus aussi sur la page /period/edit
- ca fonctionne sur la page /member/join

je pense qu'il n'arrive pas à initialiser l'autocomplete au chargement de la page, car les 2 endroits où ca ne fonctionne pas, l'autocomplete est présent dans des modals. mais je n'ai pas encore trouvé de solution

**Comment by raphodn** [comment]
j'ai trouvé le fix pour l'autocomplete, enfin... https://github.com/icefox0801/materialize-autocomplete/issues/52#issuecomment-423281820

il faut que l'input ait comme parent un div qui contienne la class `input-field`
