### ISSUE TITLE
Gérer l'adhésion annuelle pour la génération de la liste d'émargement pour les événements

### ISSUE THREAD

**Issue by petitalb** [elefan-grenoble/gestion-compte#526]
Actuellement la liste d'émargement contient soit : 
- tous les membres (cas d'un gestion avec parts sociales)
- tous les membres dont l'adhésion est de - XX ans

Quand on a une adhésion annuelle, le code fonctionne mais n'est pas idéal : on se retrouve avec une liste d'émargement plein de comptes fermés (ceux qui étaient adhérents il y a moins d'un an et qui n'ont pas réadhéré à l'année courante)

**Comment by raphodn** [comment]
@symartin ca été résolu dans ta dernière PR (https://github.com/elefan-grenoble/gestion-compte/pull/528) ou c'est un autre sujet ?

**Comment by symartin** [comment]
Avec la PR #528, le système actuel ne montre plus (jms) les comptes 'désactivé' sur la liste d’émargement. Donc pour moi ça résout le problème...

**Comment by raphodn** [comment]
ok top, je close alors :)
