### ISSUE TITLE
Pas de retour à la ligne pour les Post-It ambassadeurs

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#54]
Ajouter la possibilité de mettre des retours à la ligne dans les post-it du Bureau des Membres. En remplaçant par un textarea.
![capture du 2018-03-12 12-36-19](https://user-images.githubusercontent.com/10038524/37281695-315bb0ca-25f2-11e8-968b-83078c2908ae.png)

**Comment by janssens** [comment]
Je ferme, il y a une issue plus compléte sur les notes dans laquelle ceci sera traité.

**Comment by janssens** [comment]
#38
