### ISSUE TITLE
Mysql 5.7 : Erreur sur une migration Doctrine

### ISSUE THREAD

**Issue by pengu-fr** [elefan-grenoble/gestion-compte#548]
Bonjour,

Il y a une migration Doctrine qui ne passe pas sur un Mysql 5.7

Voici l'erreur qui bloque la migration d'une base existante :

```
Migration 20210425170158 failed during Execution. Error An exception occurred while executing 
'ALTER TABLE period ADD week_cycle LONGTEXT DEFAULT '0,1,2,3' NOT NULL COMMENT '(DC2Type:simple_array)'':
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'week_cycle' can't have a default value
```
En effet, il ne semble pas possible d'établir de valeur par défaut sur ce champs. Est-il possible de modifier la définition du champs pour supprimer cette valeur par défaut, et la définir directement en php lors de la création de l'entité ?

**Comment by raphodn** [comment]
Salut !

Ca concerne ce fichier de migration : https://github.com/elefan-grenoble/gestion-compte/blob/master/app/DoctrineMigrations/Version20210425170158.php

Est-ce que tu pourrais essayer avec une DB `mariadb` ? C'est ce qui est utilisé par le docker-compose, ou que j'utilise en local, et qu'on utilise en prod à l'Elefan.

N'empêche, ce n'est pas une solution, mais une façon temporaire de contourner le problème en attendant de trouver un fix. Tu l'as résolu en local ? Tu pourrais proposer une PR qui fonctionne ?

**Comment by symartin** [comment]
Bonjour,

apparemment, cela peut être réglé par une configuration MySQL [^1][^2]
```
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

ou juste ajouté des parenthèses ligne 26 comme proposé [ici](https://stackoverflow.com/a/73972232):
```php
$this->addSql('ALTER TABLE period ADD week_cycle LONGTEXT DEFAULT (\'0,1,2,3\') NOT NULL COMMENT \'(DC2Type:simple_array)\'');
```


## Sources
[^1]: https://stackoverflow.com/questions/38433603/mysql2error-blob-text-geometry-or-json-column-body-cant-have-a-default-v
[^2]:https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql?answertab=trending#tab-top
