### ISSUE TITLE
Problème filtre sur le planning créneaux

### ISSUE THREAD

**Issue by symartin** [elefan-grenoble/gestion-compte#555]
Les filtres semaine sur le planning /booking/admin filtre les créneaux du lundi matin

| Filtre date | Filtre semaine    |
|--------------|-----------|
| ![creneaux_par_date](https://user-images.githubusercontent.com/31699829/197506940-6ea1909f-5814-42f9-bb99-f985df127c92.png) | ![creneaux_par_semaine](https://user-images.githubusercontent.com/31699829/197507002-95b3ccc2-4d76-4c56-b0c1-144af8975437.png)    |

**Comment by raphodn** [comment]
ok j'ai creusé, il semblerait qu'en mode "week", le `$from` met la bonne date, mais l'heure "actuelle" ^^
donc si on filtre en fin de journée, le Lundi disparaît même complètement !
je suis en train de faire une PR
