### ISSUE TITLE
Mauvais affichage du restant à faire

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#56]
En local sur mon PC pro, je n'ai pas encore réservé de créneau. Cela me dit que je doit faire encore 2h.
Non reproduit en prod ou en local sur mon PC perso. Peut-être que des membres ont eu le même problème ?

![capture du 2018-03-12 14-20-46](https://user-images.githubusercontent.com/10038524/37285864-a928dd68-2600-11e8-9e28-c6d3cc42330e.png)

**Comment by sdenier** [comment]
J'ai le même soucis en local. J'ai cherché un peu, c'est lié à ce commit mais faudra demander à Christophe pour le détail. Vraisemblablement une histoire de locale et de format de date (qu'on utilise peut-être pas de la bonne façon).

https://github.com/elefan-grenoble/gestion-compte/commit/2e0083c6795828a16ceb8b6ffaa832edd1cf7caf#diff-b9da5d9431f91b2c30592bade9caaa60

**Comment by sdenier** [comment]
Cherry-pick sur 69a3dc2b62bb4a2208be66256c7daa1d08372763 ?
