### ISSUE TITLE
Permettre à chaque membre de consulter sa propre log « compteur de temps » à partir de sa page d’accueil

### ISSUE THREAD

**Issue by SabineJa** [elefan-grenoble/gestion-compte#568]
L’historique du compteur de temps est visible dans la fiche des membres quand on les consulte avec un rôle User_mgr mais les membres eux-mêmes n’ont pas accès à leur propre historique.
La question de l’état du compteur génère beaucoup de questions auprès de notre support qui consulte alors l’historique pour identifier le/les cycles ou aucun service n’a été effectué.
La proposition est de permettre à chaque membre de consulter sa propre log de « compteur de temps » à partir de sa page d’accueil.
Ce menu « **Compteur de temps** » pourrait être accessible via l’icône profile du bandeau d’accueil avec mes informations , gel de compte et badge en reprenant le même affichage que celui de l’administrateur

**Comment by raphodn** [comment]
Salut Sabine, merci pour l'issue et la proposition d'implémentation.
Ca ne devrait pas être trop compliqué à faire :ok_hand: 

Quelques détails d'implémentation supplémentaires : 
- ca concerne le template `app/Resources/views/Profile/show_content.html.twig`
- on rajoutera un paramètre pour afficher ou pas cette section (comme `display_swipe_cards_settings` actuellement)
- on veillera à ce que les actions "admin" (déjà visible dans `app/Resources/views/member/_partial/time_logs.html.twig`) ne soient pas possible dans son espace membre (même en ayant les bons droits : on préfère que chaque action admin passe par l'interface admin)

**Comment by SabineJa** [comment]
Bonjour Raphael

 

C’est parfait 👍  Super 😀

Merci beaucoup !

Sabine

De : Raphael Odini ***@***.***> 
Envoyé : samedi 29 octobre 2022 12:13
À : elefan-grenoble/gestion-compte ***@***.***>
Cc : SabineJa ***@***.***>; Author ***@***.***>
Objet : Re: [elefan-grenoble/gestion-compte] Permettre à chaque membre de consulter sa propre log « compteur de temps » à partir de sa page d’accueil (Issue #568)

 

Salut Sabine, merci pour l'issue et la proposition d'implémentation.
Ca ne devrait pas être trop compliqué à faire 👌

Quelques détails d'implémentation supplémentaires :

*	ca concerne le template app/Resources/views/Profile/show_content.html.twig
*	on rajoutera un paramètre pour afficher ou pas cette section (comme display_swipe_cards_settings actuellement)
*	on veillera à ce que les actions "admin" (déjà visible dans app/Resources/views/member/_partial/time_logs.html.twig) ne soient pas possible dans son espace membre (même en ayant les bons droits : on préfère que chaque action admin passe par l'interface admin)
