### ISSUE TITLE
[espacemembre] Dater le moment des formations

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#59]
Afin de simplifier la gestion des rôles pour le bénévolat, est-ce qu'on peut prévoir dans l'espace membre, un peu de la même façon que la date de l'adhésion et de la ré-adhésion, la date des formations suivies et des éventuels recyclages ?

**Comment by symartin** [comment]
regrouper dans un projet plus grand de log des action décrit ici : https://github.com/elefan-grenoble/gestion-compte/issues/619
