### ISSUE TITLE
[espacemembre] Outil de mailing

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#61]
L'outil de mailing depuis "Formations l'éléfàn" ne fonctionne plus. Après un test depuis "Gestion créneaux", je fais l'hypothèse que c'est lié au changement de l'intitulé de l'expéditeur : jusque-là, c'était "Gestion formations"

**Comment by janssens** [comment]
A mon avis cela n'a jamais fonctionné, l'adresse utilisée était formation@lelefan.org, sans le s final.
C'est réglé
