### ISSUE TITLE
Filter les adhérents sur des infos créneaux

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#68]
Filtres à ajouter:

Ceux qui n'ont pas fait de créneau réservé sur le cycle correspond contenant la date passée en paramètre (sur intervalle si techniquement réalisable)

**Comment by museOnSite** [comment]
Proposition de solution technique:

* Ajout d'une colonne ****first_shift_date** ** dans la table User
* Création d'une commande qui initialise ce champ quand il est vide (voir pseudo query ci-dessous)
* Mise à jour des fonctions de réservations de créneau pour initialiser la **first_shift_date**

```
SELECT * FROM USER u WHERE u.first_shift_date is null and u.shifts.length > 0
```

Reste à réfléchir au cas limite où le premier créneau est annulé

**Comment by janssens** [comment]
oui j'avais pensé à la même solution donc RAS je suis OK.
On peux aussi ne pas géré le cas où le 1er créneau est annulé : le cycle commence une fois pour toute : est-ce fondamentalement gênant ?

**Comment by museOnSite** [comment]
Effectivement je pense que c'est pas nécessaire de le gérer

**Comment by raphodn** [comment]
Je cloture car : 
- le champ `Membership.first_shift_date` existe
- la PR #873 a rajouté un filtre sur ce champ dans la liste des membres
- il y a aussi la PR #872 qui rajoute un filtre "le membre a un créneau fixe ?"
