### ISSUE TITLE
Route pour setAsMainBeneficiaryAction dans BeneficiaryControler 

### ISSUE THREAD

**Issue by symartin** [elefan-grenoble/gestion-compte#681]
Il y a une incohérence, la route pour mettre un bénéficiaire en principal ([ici](https://github.com/symartin/gestion-compte/blob/a0c2accb385d57558f1387f2a35a6aa8060d5b88/src/AppBundle/Controller/BeneficiaryController.php#L75)) est ``/beneficiary/{id}`` alors que l'on s'atendrait à avoir une fiche récapitulatif du bénéficiaire, ou qqc comme ça, pas une action. On s'attendrait a ce que l'action soit à la route ``/beneficiary/{id}/set_main/`` comme c'est le cas pour ``/{id}/detach`` ou ``/{id}/edit``.

```PHP
    /**
     * Set as main beneficiary
     *
     * @Route("/beneficiary/{id}", name="beneficiary_set_main")
     * @Method("GET")
     * @param Beneficiary $beneficiary
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function setAsMainBeneficiaryAction(Beneficiary $beneficiary)
    {
```

 De plus la route est aussi utilisée pour supprimer le bénéficiaire de la BDD, ce qui est encore plus _confusant_:

```PHP
    /**
     * Deletes a beneficiary entity.
     *
     * @Route("/beneficiary/{id}", name="beneficiary_delete")
     * @Method("DELETE")
     * @param Request $request
     * @param Beneficiary $beneficiary
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteBeneficiaryAction(Request $request, Beneficiary $beneficiary)
  ```

Je veux bien le changer (surtout que je crois qu'il est appelé indirectement dans que dans [beneficiary_card.html.twig](https://github.com/symartin/gestion-compte/blob/a0c2accb385d57558f1387f2a35a6aa8060d5b88/app/Resources/views/beneficiary/_partial/beneficiary_card.html.twig#L35)

**Comment by raphodn** [comment]
Bien vu ! J'ai fait des modifs un peu similaires dans cette https://github.com/elefan-grenoble/gestion-compte/pull/676 , où j'ai réparé les requêtes pour qu'elles utilisent des formulaire + méthode "POST"
