### ISSUE TITLE
Créneaux: compteur de bénévolat

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#69]
Fonction à ajouter sur le membre pour dire si il est à jour de ses créneaux

Définir les conditions

**Comment by janssens** [comment]
modifier le schéma pour sauver les date de gel/degel et prendre en compte ces dates dans le calcul.

**Comment by museOnSite** [comment]
Je suis d'accord au sujet du compteur de temps, l'historique devient opaque.

Il y a juste un truc qui me dérange avec ce log de temps, c'est que l'on perd le lien avec les créneaux. Il faudrait rajouter une colonne shift_id (nullable).

Un truc qui est bien avec cette solution c'est qu'on peut éventuellement immaginer n'importe quel type d'entrée dans ce log (bonus, annulation de pénalités si le membre a un mot des parents, etc.)

**Comment by museOnSite** [comment]
Voir ma proposition #92 pour l'enregistrement des participations/retards/absences

**Comment by museOnSite** [comment]
### Modèle

Champ | Type | Nullable|Comment
------------ | ------------- | -------------| -------------
id | Integer | No | Primary key
date|Datetime|No|
time|Integer|No|In minutes
shift_id|Integer|Yes|FK

###  Initialisation du log de temps

Choix possibles:

*  Tout le monde part à 0 au moment du déploiement (les créneaux du cycles en cours après le déploiement sont comptés). C'est le plus simple techniquement mais pas forcément le plus équitable.
* Tout le monde part à 0 mais on commence à compter qu'à partir du prochain début de cycle du membre. Plus équitable mais je vois pas trop comment faire.
* On initialise on prenant aussi en compte les créneaux effectués du cycle en cours
* On initialise en prenant en compte des cycles précédents 


### Incrémentation du log de temps lors de la réalisation d'un créneau

Choix possibles:

* Via débriefing (cf. #92 ). Problème: comment on vérifie pour les ambassadeurs par exemple.
* Automatiquement une fois le créneau passé. Le plus simple techniquement, nécessite une interface d'ajustement pour les absences (voir plus loin).

### Interface d'ajustement

Interface admin pour ajouter des entrées dans le log de temps.
Nécessaire pour enregistrer les absences et les retards par exemple.
Possibilité de mettre des cas prédéfinis (retard moins de 50% de la durée du créneau, absence, etc.) dans un second temps.

### Créneau compte double

Je propose d'ajouter un champ (booléen ?) dans l'entité Shift pour marquer un créneau compte double. Ce champ est setté à la bonne valeur lors de la réservation.

**Comment by janssens** [comment]
== schema ==
- Ok pour ajouter la FK shift, que j'avais volontairement pas mis pour pouvoir purger les vieux shifts par exemple. mais finalement j'en ai besoin plus tard (voir plus bas) => je suis donc ok avec ton entité.

== Init ==
- je dirais mode retroactif si possible. histoire que ceux qui ne participent pas, si il en reste, soient identifiés dés la mise en place.

== Création log temps ==
- à la réservation du shift (daté dans le futur)
- édité si absence, retard ou départ anticipé (via debrief, admin ou badgeuse) (ici FK indispensable)

== Créneau double ==
- créneau double je n'ajouterai rien au shift, seulement un "effet" en front à h-48h et je préremplierai le log temps au moment de la résa en double.

== badgeuse ==
Je reste convaincu que c'est vraiment pas compliqué de la mettre ne place

16h30 - "bonjour gaëtan, tu es en avance, ton créneau commence dans 30min"
16h55 - "Tu pars déjà ? mais ton créneau va commencer dans 5min"
a)  'oui je sort' => membres parti, je recommence le sénario
b) 'oups je reste' =>
16h56 - "Content que tu reste, à tout à l'heure"
19h10 - "Tu pars déjà ? mais ton créneau n'est pas terminé !"
a) 'désolé je dois vraiment partir' => édition du log pour pénalité
b) 'oups c'est une erreur' =>
20h05 - "merci d'avoir fait ton créneau, le prochain est le samedi 31 avril à 17h30, à bientôt !"
Tous ceux qui sont considéré comme "à l'intérieur" à 21h sont "check out" par le système.

badge en retard => édition du log pour pénalité
pas de badge détecté => mail à creneaux@ ssi pas de debrief non plus. (sinon confiance au debrief)

Ceux qui ne badgent pas en sortant ne sont pas considéré comme absent.

**Comment by museOnSite** [comment]
### Initialisation

Pour l'initialisation je propose de prendre en compte le cycle précédent et le cycle en cours.

**Pseudo code de la commande d'initialisation:**

```
$users = UserRepository->findAll();
foreach ($users as $user) {
   $shifts = array_merge($user->shiftsOfCycle(0, true) + $user->shiftsOfCycle(1, true))
   foreach($shifts as $shift) {
      $log = new TimeLog();
      $log->setUser($user->getId());
      $log->setTime($shift->getDuration());
      $log->setShift($shift));
      $log->setDate($shift->getStart());
      $em->persist($log);
   }
   // Decrement one cycle beginning
   $log = new TimeLog();
   $log->setUser($user->getId());
   $log->setTime(-180);
   $log->setDate($user->startOfCycle(1));
   $em->persist($log);
}
$em->flush();
```
**2 remarques:**

* Vérifier que récupérer les créneaux du cycle précédent avec User->shiftsOfCycle(0) fonctionne
* Si il y a eu du surbooking on ne filtre pas, on peut donc potentiellement se retrouver avec des compteurs supérieurs à 3h (c'est pas un problème de mon point de vue)

**Comment by museOnSite** [comment]
### Interface admin

Visualisation des entrées du log de temps sur la page du membre.
Les ambassadeurs doivent-ils pouvoir les visualiser ou uniquement la valeur du compteur ?

Pour les admins, les actions suivantes sont possibles:

* Editer une entrée
* Ajouter une entrée
* Supprimer une entrée

**Comment by janssens** [comment]
Ambassadeur je dirais oui visualiser, comme les utilisateurs devraient pouvoir le faire pour leur propre log.
ça permet de bien comprendre je pense.

**Comment by janssens** [comment]
penser à gérer les gels en même temps.
idée : 
* au moment du gel, on génère le log décompte de fin de cycle (-3h à la date de fin de cycle)
* tant que le compte est gelé, aucun log n'est généré.
* le degel est immédiat, sur le cycle en court (même si il ne reste que quelques jours (penser warning))

reste à voir qui gel : seulement un admin ou l'utilisateur ?
idem qui dégel ?
quid d'un gel quand il y a des créneaux programmés ?

**Comment by museOnSite** [comment]
Oui ça me parait bien ton idée ... Du coup la philosophie c'est "tout cycle commencé est du".
Je pense qu'on peut se contenter de faire la fonctionnalité uniquement en admin (gel et dégel)...moins de boulot et ça évitera de perdre encore un peu plus les gens sur leur espace membre. Cela règle aussi le problème de ta dernière question, à la charge de l'admin de vérifier.

**Comment by museOnSite** [comment]
### Réservation créneau

Même comportement en admin et par le membre.

Insertion d'une entrée dans le log de temps.
Application du x2 si les conditions sont réunies (@janssens quelles sont t'elles ?)

**Comment by museOnSite** [comment]
### Annulation créneau

Modification du log en mettant le temps et le commentaire adéquat (temps à 0 si annulé dans les temps, sinon un nombre négatif)

@janssens Tu peux compléter avec les règles exactes de pénalité

### Reprise d'un créneau annulé

Si le membre clique sur "Je peux finalement tenir mon créneau"

On remet comme si le membre n'avait jamais annulé ?

**Comment by museOnSite** [comment]
Ca va être un peu compliqué de gérer le log de temps si on intègre les règles de cette issue #84

**Comment by janssens** [comment]
* condition pour x2 : créneau en attente de reprise h-48 passée.
* annulation => pénalité (a rediscuter ?)
- avant h-48 => péna 0. 
- après h-48 => péna 1h30 (quid des créneaux de 1h30 ? péna 45 min ?! ).
le fait que le créneau dismissed soit repris ou non bloque le membre pour faire une autre resa et le pénalise donc d'une manière différente et supplémentaire.
https://wiki.lelefan.org/index.php?title=Commission:gestion/creneaux/politiques#Gestion_des_absences
* reprise du créneau == prise du créneau == log créneaux complet à date du créneau (/!\ ne pas traiter en x2 l'auto reprise à h-48)
* #84 revient à gérer le surbooking
- a la fin du cycle (ou pour le gel), on remet le membre à "0" ssi solde >= 3 ou à "solde - 3" sinon

**Comment by museOnSite** [comment]
Je commence le dev, je vais faire l'entité et la commande d'initialisation

**Comment by janssens** [comment]
c'est aussi un bon moyen de régler le bug car ce ne sera plus le même mode de calcul du temps restant à reverser :)

**Comment by museOnSite** [comment]
Tâches:

- [ ] Ajout de la table TimeLog
- [ ] Commande d'initialisation des données
- [ ] Insertion log de temps à la réservation d'un créneau
- [ ] Gestion des créneaux compte double
- [ ] Gestion annulation de créneaux
- [ ] Gestion des pénalités
- [ ] Gestion reprise créneaux (après annulation)
- [ ] Ajout log de temps -3 heures en début de cycle
- [ ] Function entité user: calcul du compteur à partir du log de temps
- [ ] Affichage du compteur/log de temps sur la page d'accueil du membre
- [ ] Interface admin de gestion du log de temps d'un membre

**Comment by museOnSite** [comment]
Actions de mise en prod:

- [ ] Initialiser le log de temps avec la commande app:user:init_time_log
- [ ] Renommer la commande app:user:send_cycle_start_emails en app:user:cycle_start dans la CRON

**Comment by museOnSite** [comment]
En prod.
Je crée des issues à part pour les tâches qui n'ont pas été faites (interface admin, pénalités etc.)
