### ISSUE TITLE
Format moins restrictif pour les codes postaux

### ISSUE THREAD

**Issue by phfroidmont** [elefan-grenoble/gestion-compte#759]
L'application permet uniquement d'entrer un code postal composé de 5 chiffres.

En Belgique et au Luxembourg, les codes postaux sont formés de 4 chiffres. Il existe également un florilège d'autres formats.
Je propose de simplement accepter une chaine de 10 caractères pour couvrir la grande majorité des cas d'utilisation possibles.

**Comment by raphodn** [comment]
Bonne idée pour élargir l'usage aux autres pays limitrophes / francophones :)

En allant sur https://www.codepostalmonde.com/ par contre je vois très peu de pays avec autre chose que des chiffres dans leurs codes postaux. Donc ok pour être flexible sur la longueur, moins ok pour pouvoir mettre des lettres ^^

**Comment by phfroidmont** [comment]
Au Luxembourg, les codes postaux sont normalement préfixés d'un `L-`: https://worldpostalcode.com/luxembourg/
Dans les faits, je pense qu'il n'y a pas d'autre préfixe donc l'ignorer n'est probablement pas un problème.

En ce qui me concerne ça m'est égal, je te laisse le dernier mot et j'adapterai ma PR en fonction. :)
