### ISSUE TITLE
Avoir un jeu de données d'initialisation

### ISSUE THREAD

**Issue by raphodn** [elefan-grenoble/gestion-compte#780]
Pour les nouvelles coopératives qui souhaitent tester ce repo, il serait intéressant de fournir un jeu de données avec quelques utilisateurs / créneaux / formations / ...

Sous quelle forme ?
- CSV / JSON + script d'import ? 
- db.sql ?

**Comment by phfroidmont** [comment]
Un simple fichier SQL qui permet de faire `mysql < db.sql` me semble le plus intuitif.
Ce serait également utile pour mettre en place des tests end to end qui permettraient à leur tour de vérifier que ce fichier reste à jour.
