### ISSUE TITLE
Lecteur de carte membre

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#79]
Un membre qui vient faire ses courses: est-il à jour de ses créneaux ?

**Comment by janssens** [comment]
compte Fermé : NOK
compte Gelé : NOK
Adhésion expirée : NOK
Compteur <  9h : NOK
Sinon OK

**Comment by janssens** [comment]
La badgeuse envoi le numéro de badge a l'espace membre, en retour l'espace membre lui donne une URL à afficher.
Côté espace membre, gérer les badges (id, user_id, index, barrecode_number)
l'index correspond au numéro de badge (1er, 2ème,....)
le barre code est aléatoire.

**Comment by janssens** [comment]
en prod
