### ISSUE TITLE
Non accumulation dans les compteurs temps

### ISSUE THREAD

**Issue by sebastienbianco** [elefan-grenoble/gestion-compte#864]
Bonjour,

Je ne constate plus d'accumulation des heures en excédent dans le compteur temps. 

Notre utilisateur de test a fait largement son quota d'heure (3h) pour le cycle  précédent (5h sup normalement) :

CYCLE PRÉCÉDENT (DU 18/04/23 AU 15/05/23)
mardi 18 avril de 18:30 à 20:30
personPrénom6
Créneau soir fermeture 2h
Formation : Vrac

jeudi 20 avril de 11:00 à 14:00
personPrénom6
Créneau 3h
Formation : Vrac

jeudi 11 mai de 13:30 à 16:30
personPrénom6
Créneau 3h
Formation : Vrac

 Il a de plus de heures programmée pour le cycle courant : 

Mes créneaux pour le cycle courant (du mardi 16 mai au lundi 12 juin)
jeudi 18 mai de 12:00 à 13:30
personPrénom6
Créneau Renfort Magasin 1h30
Formation : Poly-volant

mardi 23 mai de 08:30 à 11:30
personPrénom6
Créneau 3h
Formation : Vrac

vendredi 26 mai de 16:00 à 19:00
personPrénom6
Créneau 3h
Formation : Vrac

mardi 30 mai de 12:00 à 13:30
personPrénom6
Créneau Renfort Magasin 1h30
Formation : Poly-volant

Pour autant son Compteur Temps est toujours à 0 (nous avons attendu le changement de cycle pour voir si le CET était valorisé à cet instant).

NB : Nous ne sommes pas en mode cycle "ABCD" ce qui signifie que les cycles sont personnels.
NB2 : Nous n'avons pas ajouté de cron particulier... Est-ce une tache batch qui valorise les CET ?

Version testée 1.44.2

Dans la version 1.44.0 (mais en configuré en cycle ABCD), les compteurs étaient mieux valorisés.

**Comment by raphodn** [comment]
Salut Sébastien, bug toujours d'actualité ? :)

**Comment by sebastienbianco** [comment]
Bonjour

Considère que non. Nous n'avons finalement pas opté pour le CET (et probablement, c'est une mauvaise config de nos conteneurs qui a du nous mettre dans le jus).

Bonne fin de journée

Sébastien
