### ISSUE TITLE
Erreur 500 avec le parametre use_fly_and_fixed: false 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#895]
Nous utilisons l'application Gestion de compte à POP la Coop.
3 instances (test, formation, production) sont installées sur notre VPS chez OVH

J'ai fait une mise à jour de la version 1.29 sur la version 1.44.6 sur notre environnement de test.
Je rencontre une erreur 500 avec le parametre use_fly_and_fixed: false

Connexion avec mon ID
> Administration > Gérer les membres > 
la première page des membres s'affiche correctement
Le passage à une autre page via <1 2 3...> donne l'erreur 500

Je joins le fichier log  (test1.log) avec l'issue CRITIQUE 
[2023-06-27 09:19:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\OutOfBoundsException: "Child "has_period_position" does not exist." 
[test1.log](https://github.com/elefan-grenoble/gestion-compte/files/11878980/test1.log)

Le changement de la valeur du parametre à True corrige le problème
[parameters.yml.txt](https://github.com/elefan-grenoble/gestion-compte/files/11879008/parameters.yml.txt)

**Comment by raphodn** [comment]
Salut ! Merci pour la remontée détaillée du bug.

En effet dans la PR #872 je suis allé un peu vite et je n'ai pas testé dans le cas `use_fly_and_fixed=false`

Je viens de le réparer dans ce commit : https://github.com/elefan-grenoble/gestion-compte/commit/45764b8b59f774540bf11f4de6fda6d782272c3d
