### ISSUE TITLE
Erreur 500 Déposer les clés

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#897]
Nous utilisons l'application Gestion de compte à POP la Coop.
3 instances (test, formation, production) sont installées sur notre VPS chez OVH

J'ai fait une mise à jour de la version 1.29 sur la version 1.44.6 sur notre environnement de test.
Je rencontre une erreur 500 avec l'option Déposer les cléfs
Note : cette fonction n'a jamais fonctionnée dans notre environnement quelque soit la version installée
POur info, POP la Coop n'utilise pas de boite à clé

Administration > Déposer les cléfs
> donne l'erreur 500

Je joins le fichier log (test3.log) avec l'issue CRITIQUE [2023-06-27 09:43:04] (dernière du fichier log)
[2023-06-27 09:52:42] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response 
[test3.log](https://github.com/elefan-grenoble/gestion-compte/files/11879211/test3.log)

**Comment by raphodn** [comment]
Merci pour les détails.

L'erreur je crois est "normale". dans le fichier [CodeController](https://github.com/elefan-grenoble/gestion-compte/blob/master/src/AppBundle/Controller/CodeController.php) tu rentres dans la partie qui renvoie un `createAccessDeniedException` (helper qui est utilisé à d'autres endroits dans le code d'ailleurs).

Par contre il y a en effet un petit bug, cela devrait `throw` d'utilisé.

**Comment by raphodn** [comment]
J'ai rajouté un commit pour "réparer" : https://github.com/elefan-grenoble/gestion-compte/commit/bcdccc03528cd5185560e427d9ae4d445ca5a829
