### ISSUE TITLE
Fonction Adhésion erronée ? 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#901]
Nous utilisons l'application Gestion de compte à POP la Coop.
3 instances (test, formation, production) sont installées sur notre VPS chez OVH

J'ai fait une mise à jour de la version 1.29 sur la version 1.44.6 sur notre environnement de test.
J'ai ensuite anonymisé la base avec la commande php bin/console app:anonymize

POP la Coop est une coopérative à adhésion unique (et non annuelle) 
=> Dans parameters.yml, registration_duration: '99 years'

> Administration > Relances Créneaux
l'écran affiche des messages erronés (dépasé de X jours) sur la colonne **Dernière Adhésion** 

![retard](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/8ca635a2-a078-4576-b7e0-ea9cd9a0ea75)

Suggestion : Retirer de cet écran la colonne **Dernière Adhésion** qd le parametre registration_duration est à 99 Years

**Comment by raphodn** [comment]
Salut Christophe, j'avoue que ça me surprend un peu que la seule façon d'indiquer des "adhésions unique" et de mettre un chiffre important dans le paramètre `registration_duration` :thinking: 

@janssens c'est le setup recommandé pour les coopératives non-associatives ?

**Comment by ctmareil** [comment]
Mais de toute façon, le message "Dépassé depuis x jours" est erroné, car la durée d'adhésion est à .... 99 années
De plus ce message n'apparait pas sur tous les membres.

**Comment by janssens** [comment]
Je ne me souviens plus comment ça a été pensé, il faudrait que je regarde le code. Peut-être mettre 0 ?

**Comment by ctmareil** [comment]
J'ai vu qu'il y avait des issues sur ce pb mais je ne suis pas très sur de comprendre ce qu'il faut faire
La coopérative de Rennes utilise également le parametre registration_duration: '99 years'

Issues sur ce pb : 
Durée de validité d'une adhésion configurable #201
Add service to deal with registration duration #359

**Comment by janssens** [comment]
Bonjour,
Il y avait un bug, la durée d'un an était hard codé à cet endroit.
J'ai fait [cette PR](https://github.com/elefan-grenoble/gestion-compte/pull/913)
A tester ;)

**Comment by ctmareil** [comment]
La correction corrige le problème.
Merci
