### ISSUE TITLE
Le titre des évenement est illisible avec une image sur fond blanc

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#902]
En créant un événement qui comprend une image sur fond blanc, le titre est illisible (utilise une police couleur blanche)
![evenement](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/07b84f07-2af7-4cc0-86d8-222036817b4b)

Suggestion : Permettre de changer la police ou le fond du titre d'un évenement

**Comment by raphodn** [comment]
On a le même soucis à l'elefan.
Je vais voir pour commencer de mettre le titre dans la section en dessous ^^
