### ISSUE TITLE
Fonction find_member_number inaccessible ? 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#903]
Nous utilisons l'application Gestion de compte à POP la Coop.
3 instances (test, formation, production) sont installées sur notre VPS chez OVH

J'ai fait une mise à jour de la version 1.29 sur la version 1.44.6 sur notre environnement de test.
J'ai ensuite anonymisé la base avec la commande php bin/console app:anonymize

> Administration > Adhésion > Editer un Adhérent > Si tu ne connais pas le numéro d'adhérent, [clique ici pour le retrouver](https://membres-test.poplacoop.fr/beneficiary/find_member_number).

Message d'erreur : 
Oups, nous n'avons pas trouvé ce que tu cherches
La page demandée n'a pas pu être chargée. Vérifie l'URL ou [retourne à l'accueil](https://membres-test.poplacoop.fr/).

Mes rôles : ROLE_ADMIN ROLE_PROCESS_MANAGER ROLE_SHIFT_MANAGER ROLE_USER_MANAGER ROLE_FINANCE_MANAGER ROLE_USER

[test7.log](https://github.com/elefan-grenoble/gestion-compte/files/11947021/test7.log)

**Comment by raphodn** [comment]
Bien vu ! J'ai réparé et amélioré : https://github.com/elefan-grenoble/gestion-compte/commit/a15e66c98e07b00513c953c33144ce3fbd926d4e & https://github.com/elefan-grenoble/gestion-compte/commit/24ff993d6131c9e61ee5addf6090294e3065e427
