### ISSUE TITLE
Champs Nom-membre en copie est trop court

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#908]
Dans l'écran d'envoi de mail, Le champs _Non-membre en copie_ est trop court
![copienonmembre](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/404553ef-6817-411d-b7a2-9eb9145d3a37)

**Comment by raphodn** [comment]
C'est quelle url, `/admin/mail/` ? Tu utilises quel navigateur ?

Je viens de tester sur Brave (Chromium), et je n'ai pas ce soucis. L'autocomplete est un peu étroit en effet (120 px de largeur - je vais corriger), mais une fois un e-mail de non-membre sélectionné le chip est entier.

**Comment by raphodn** [comment]
Tu as bien la version 1.2.1 de MaterializeCSS ? (normalement est elle est inclue dans le code)

**Comment by raphodn** [comment]
Vu avec Christophe, ce champ ne prend que des utilisateurs dans la base de données, donc ce n'est pas un bug
