### ISSUE TITLE
Rôle ressource du samedi 17h00-20h00

### ISSUE THREAD

**Issue by fgougou** [elefan-grenoble/gestion-compte#91]
Pour le moment, seul le rôle fermeture est associé au job spécifique de ce créneau : comme c'est aussi un créneau classique, il faudrait la combinaison ressource/fermeture

**Comment by janssens** [comment]
Je trouve que ça complexifie le système pour pas grand chose, ce n'est pas une grosse contrainte que de n'ouvrir le rôle fermeture qu'aux BR. 
On a 5 membres fermeture qui ne sont pas ressource : Emilie, Noëmie, Sandy, Christophe et Louis.
Qui, au passage, ne serait très bien en BR.

**Comment by museOnSite** [comment]
Je suis d'accord. La fonctionnalité serait intéressante mais clairement pas prioritaire

**Comment by fgougou** [comment]
Bien d'accord sur le fait que ce n'est pas prioritaire, je mets juste les
trucs auxquels je pense.

Au-delà, je me suis posé la question de la qualification de ce dernier
créneau du samedi soir en le faisant, pour la première fois, sous sa
nouvelle formule. Et pour moi, en fait, c'est fondamentalement un créneau
de bénévole-ressource et pas de fermeture. La fermeture, il n'y a rien de
sorcier quant aux compétences techniques : tout est indiqué sur le guide de
l'épicerie, la seule chose qui manque c'est le code du coffre. En revanche,
compte tenu de la durée d'ouverture au public du magasin sur ce créneau,
cela ressemble beaucoup plus à un vendredi 17-20 qu'à un vendredi 19h30-21h.

On en reparle !

Le 23 avril 2018 à 11:40, Bastien Deshayes <notifications@github.com> a
écrit :

**Comment by janssens** [comment]
Je ferme avec la disparition du rôle fermeture, on va dans le bon sens :)
