### ISSUE TITLE
Rendre d'avantage accessible le bouton 'Nouvelle Adhésion'

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#914]
Nous utilisons l'application Gestion de compte à POP la Coop.
3 instances (test, formation, production) sont installées sur notre VPS chez OVH
J'ai fait une mise à jour de la version 1.29 sur la version 1.44.6 sur notre environnement de test.
J'ai ensuite anonymisé la base avec la commande php bin/console app:anonymize

Sur mon profil, j'ai les roles suivants : je suis donc Admin
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/b3f36cca-e76c-42af-877c-eafecb5a00cd)

Je n'ai pas accès à la procédure de nouvelle adhésion. 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/382e6a42-8d99-4b40-b2e1-294f1a3ea321)

Est-ce normal ?

**Comment by raphodn** [comment]
Actuellement dans le code ce bouton est seulement accessible aux ROLE_SUPER_ADMIN.
En général 1 utilisateur a ce rôle là, et on s'y connecte pour des actions "critiques".

Par contre je ne maitrise pas bien le formulaire qui se cache derrière le bouton "Nouvelle adhésion". Il me semble qu'il demande de définir manuellement le numéro de membre, ce qui à l'éléfàn ne nous convient pas (on le génère incrémentalement).

Est-ce que le bouton "Nouvelle adhésion réunion info" vous convient ?

En tout cas tu peux tout de même accéder au formulaire derrière le bouton grisé, en te rendant sur `/member/new`

**Comment by ctmareil** [comment]
Avec la version 1.29, un utilisateur avec le role ADMIN pouvait accéder à cette fonction

Effectivement, il permet de définir le numéro du membre (c'est important pour POP la Coop) mais il propose le dernier numéro libre.   On ne se sert pas de l'option Nouvelle Adhésion Réunion d'Info. 

Si pas possible de remettre l'ancien comportement, ton option /member/new est acceptable
