### ISSUE TITLE
Page de debrief d'un créneau

### ISSUE THREAD

**Issue by museOnSite** [elefan-grenoble/gestion-compte#92]
Je propose d'ajouter une fonctionnalité de debriefing des créneaux.

A la fin de son créneau, le bénévole ressource (ou n'importe quel membre du créneau?) peut accéder à une page pour débriefer le créneau. Il pourra notamment y renseigner les informations suivantes:

* Bénévoles présents/absents
* Retards
* Incidents / Suggestions
* Liste des tâches restantes à faire (pour les créneaux suivants). Efficace à partir du moment où on aura un écran d'affichage dans l'épicerie.

**Comment by janssens** [comment]
- Je suggère une vue différente de la home, "mode créneau", pour plus de simplicité : Visible 15minutes avant le début et 30min après la fin d'un créneau. par exemple.
- Tout les bénévoles doivent pouvoir faire ça, surtout pas juste le BR
- prévoir peux être un genre de verrou : prendre la main pour éditer le debrief.
- Une fois les 30 minutes après fin créneau passées, le "bilan" part par mail aux shifter avec deux boutons "approuver" "réfuter"
- la fonctionnalité de taches est intéressante mais il ne faudrait pas que ça remplace la transmission orale et physique qu'il faut généraliser. j'attendrait un peu pour vraiment définir le besoin.
- qui dépile incidents ? un exemple d'incident qui pourrait être renseigné ?
- suggestion je vois plus un "genre" formulaire de contact, qui ne garde rien en BD mais qui envoi un mail.
A discuter aussi avec Florent G
