### ISSUE TITLE
Problème pour annuler soi-même un créneau

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#925]
La suppression d’un créneau par le membre semble impossible dans cette version 

Quels sont les paramètres à ajuster pour le permettre à nouveau dans la config de POP la Coop? 
```
time_log_saving_shift_free_min_time_in_advance_days: null
use_time_log_saving: true
```

![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/36be29f5-4662-48a3-8e3e-84e9db76625a)

**Comment by raphodn** [comment]
Salut Christophe, c'est une capture d'écran d'un créneau d'un membre (dans son espace utilisateur) c'est bien cela ?

Il y a plusieurs règles qui sont prises en compte pour l'affichage (ou non) du bouton. Ils sont définis dans la fonction canFreeShift : https://github.com/elefan-grenoble/gestion-compte/blob/e36c93d3fd2c065fcd20b4faebe5b365b0999956/src/AppBundle/Service/ShiftService.php#L265

- être le bénéficiaire du créneau (pas possible d'annuler le créneau de son co-bénéficiaire dans le cas d'un compte avec 2 bénéficiaires)
- le créneau doit être dans le futur
- si `use_fly_and_fixed: true` et si le créneau est un créneau fixe, alors il faut que `fly_and_fixed_allow_fixed_shift_free: true`
- si `use_time_log_saving: true` (compteur épargne)
  - si `time_log_saving_shift_free_min_time_in_advance_days: X`, il faut que le créneau ait lieu au moins dans X jours
  - il faut que le membre ait un compteur temps au moins égale ou supérieur à la durée du créneau

C'est très surement la dernière règle qui te concerne.

Nous l'avons implémenté avec notre logique, qui est un peu restrictive en effet.
1) Tu voudrais que tes membres puissent annuler leur créneau peu importe la valeur de leur compteur épargne ?
2) Lors d'une annulation de créneau, tu voudrais que le créneau soit effectivement comptabilisé (et le temps pris sur le compteur épargne), ou pas ?
3) Quand imagine-tu que le compteur épargne soit utilisé par tes membres ?

**Comment by ctmareil** [comment]
Bonjour Raphaël
c'est une capture d'écran d'un créneau d'un membre (dans son espace utilisateur) 
Idéalement, j'aimerais un process simple  : 
- Un membre peut annuler une réservation d'un créneau qui aura lieu dans x jours ou plus. Et si c'est moins de x jours, c'est un admin qui doit le faire.
- Dans tous les cas, un créneau annulé n'est pas comptabilisé dans le compteur temps ou le compte épargne.

De même, le compte épargne est incrémenté du temps de service effectué par le membre au delà de ses heures obligatoires 
Si la valeur épargnée est supérieure aux heures obligatoires, le compte épargne peut être décrémenté (par le membre ou un admin ?) à la demande dans un cycle ou il ne peut/veut pas venir faire son service

**Comment by ctmareil** [comment]
Raphael
Il semble que ta dernière condition est la suivante : 

>  - si `time_log_saving_shift_free_min_time_in_advance_days: X`, il faut que le créneau ait lieu au moins dans X jours
>   - il faut que le membre ait un compteur ~~temps~~ EPARGNE au moins égale ou supérieur à la durée du créneau

**Comment by raphodn** [comment]
Y'a toujours un problème ici du coup ?

**Comment by raphodn** [comment]
Du coup je pense que ca nécessite de rajouter 1 ou 2 paramètres : 

|paramètre|Explication|Elefan|Pop la Coop & autres|
|---|---|---|---|
|`time_log_saving_shift_free_allow_only_if_enough_saving`|Un membre souhaite annuler un créneau dans le futur : est-ce qu'on lui autorise seulement si son compteur épargne est suffisant ?|`true`|`false`|
|`time_log_saving_shift_free_use_saving`|Un membre (ou un admin) annule un créneau dans le futur : est-ce qu'on tente d'utiliser le compteur épargne du membre ?|`true`|`false`|

Le 2e n'est pas nécessaire chez vous, car dans la PR #1001 (issue #1000) on a déjà statué que les coop qui ne valident pas les créneaux ne peuvent pas utiliser le compteur épargne en cours de cycle.

**Comment by raphodn** [comment]
@ctmareil je viens de merger dans master la PR qui rajoute le nouveau paramètre `time_log_saving_shift_free_allow_only_if_enough_saving`. En le mettant à `false` (valeur par défaut), tes membres pourront à nouveau annuler leur créneau même si leur compteur épargne n'est pas satisfaisant.
