### ISSUE TITLE
Widget d'affichage des fermetures exceptionnelles

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#945]
Avec la gestion des fermetures exceptionnelles, , il serait intéressant d'avoir un widget d'affichage de ces fermetures sur la page d'accueil.

Par exemple : 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/5636eb88-ca43-41ce-9484-067941acc158)

**Comment by raphodn** [comment]
Tu souhaiterais voir seulement les fermetures exceptionnelles à venir ?
