### ISSUE TITLE
Erreur 500 Séparation de 2 comptes joints

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#951]
Sur le système de test de POP la Coop, 

1. jointure de 2 comptes => OK
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/9da8a5d9-070b-4392-b7d3-11a64746964b)

3. séparation de ces 2 comptes => Erreur 500

**Comment by ctmareil** [comment]
même problème que issue 953
Dans le fichier log la colonne Column 'flying' cannot be null"
[log3.log](https://github.com/elefan-grenoble/gestion-compte/files/12397209/log3.log)

**Comment by raphodn** [comment]
j'ai retiré de l'historique la PR qui a provoqué ces erreurs (#918), donc en remettant master (et en ayant une base de données d'equerre) le problème devrait disparaitre.

On se penchera pour réintégrer cette PR (avec les correctifs) un peu plus tard
