### ISSUE TITLE
Erreur 500 : Création d'une Nouvelle Adhesion avec registration_manual_enabled: true

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#953]
Sur le site de test de POP la Coop, 
avec le parametre registration_manual_enabled: true

Le menu NOUVELLE ADHESION est accessible pour le role ROLE_ADMIN 

Cependant l'ajout  d'un nouveau membre par un admin (mais également un super admin) donne Erreur 500.

**Comment by ctmareil** [comment]
Dans le fichier log la colonne Column 'flying' cannot be null"

[log2.log](https://github.com/elefan-grenoble/gestion-compte/files/12397163/log2.log)

**Comment by raphodn** [comment]
Salut Christophe, cette erreur est liée à la PR #918. 
Pour faciliter les choses, je l'ai retirée de master (on la mergera plus tard dans un lot séparé avec la 940).
Donc il faudrait que tu récupères master en faisant un `git pull --f`.
Le hic, c'est que tu as sûrement lancé la migration qu'elle contenait... est-ce que tu pourrais réinitialiser ta base de données avec une version antérieure ?

**Comment by raphodn** [comment]
j'ai retiré de l'historique la PR qui a provoqué ces erreurs (#918), donc en remettant master (et en ayant une base de données d'equerre) le problème devrait disparaitre.

On se penchera pour réintégrer cette PR (avec les correctifs) un peu plus tard
