### ISSUE TITLE
Erreur d'affichage pour le premier créneau d'un nouveau membre 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#963]
Sur la version en test de POP la Coop

1. Création d'un nouveau membre par un admin (OK) 
![1301init](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/8320cf0d-d0c0-4798-b926-1e056e47015e)
2. Le nouveau membre se connecte et choisit son PREMIER créneau => KO
![1301creneau](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/8a75aa8b-2a1a-4136-a3fd-5a99856c1ff7)

**Comment by raphodn** [comment]
c'est bizarre en effet.

en tout cas, pour les épiceries pas en `cycle_type: abcd`, les cycles d'un membre sont liés à la date du tout premier créneau.

donc dans ta première capture il faudrait cacher toutes ces infos et mettre un message indiquant que le membre n'est pas encore inscrit à aucun "premier" créneau.

**Comment by raphodn** [comment]
pour la deuxième capture, maintenant que le membre a son premier créneau, on voit bien que les cycles commencent le vendredi 1 septembre. il faudrait cacher les cycles précédents.

mais il doit y avoir un soucis dans la fonction `findShiftsByCycles` pour qu'il t'affiche le créneau dans le mauvais cycle :thinking: je vais regarder

**Comment by ctmareil** [comment]
Pour la première capture, c'est juste après l'inscription. Il n'a pas fait de créneau, donc la date présumée premier cycle est  la date d'inscription et c'est OK.
Par contre c'est effectivement dans la deuxième capture, le premier créneau est le 1er septembre. Donc les dates marquées d'une flèche rouges sont incompréhensibles et le créneau doit être mis dans la rubrique Cycle en Cours (1er septembre...)..... il y a effectivement un souci :)

**Comment by ctmareil** [comment]
L'erreur de positionnement du premier créneau n'est toujours pas résolue dans la 1.45.1
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/f7ea6024-4af9-426c-9763-4064ea444b48)

**Comment by raphodn** [comment]
Ah zut.. Quand tu vas dans la section "Informations diverses" du membre, c'est indiqué quoi comme date de premier créneau ?

**Comment by ctmareil** [comment]
nos valeurs :
`new_users_start_as_beginner:`  `false`
`cycle_duration:` '28 days'
`cycle_type:` `null`

**Comment by raphodn** [comment]
Ok merci ! Et dans ton exemple le membre s'est inscrit lui-même ? Ou c'est un admin qui l'a inscrit ?

En tout cas il y a une incohérence, la date du tout premier créneau indique le "jeudi 21 septembre", alors que sur ta capture d'écran il y a affiché "dimanche 17 septembre" :thinking: 

ton serveur est au "11 septembre" ou au "15 septembre" ?

**Comment by raphodn** [comment]
Ah mais tu fait référence à l'image de la capture 994. Du coup c'est bon en fait ! Le premier créneau sert de premier jour de cycle, donc c'est normal que ca soit annoncé comme "cycle suivant" et non "cycle courant". cf ma capture aussi

**Comment by raphodn** [comment]
Idéalement il ne fait réserver qu'un seul créneau, ou alors le deuxième doit avoir lieu après le "first shift date". pour éviter des bugs potentiels :thinking:

**Comment by ctmareil** [comment]
Le premier créneau sert de premier jour de cycle, donc le premier créneau devrait être le premier jour du "cycle courant", 
non ? 
Je pinaille, je pinaille.  On peut clore l'issue

**Comment by raphodn** [comment]
on appelle "cycle courant" le cycle qui contient "aujourd'hui". donc si le premier créneau est dans le futur ca ne peut pas être le cycle courant, à moins de ne pas faire démarrer les cycles à partir du first shift date (mais on devrait changer tout le code ^^).

content que cette issue soit close :sweat_smile:
