### ISSUE TITLE
Légende Choisir un créneau

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#984]
Il semble que l'affichage des Créneau annulé, à reprendre : aide un bénévole en galère ne fonctionne pas.
Nous ne l'avons jamais fait apparaitre dans nos tests. 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/6e9a721a-ca90-440d-89d7-175140a92a86)

**Comment by raphodn** [comment]
Ca n'est pas utilisé dans le fonctionnement actuel de l'Elefan, j'ai cherché et je n'ai pas trouvé les cas de figure nécessaires pour le faire "apparaitre".

@petitalb c'est encore utile ? Ou on peut supprimer cette ligne ?

**Comment by petitalb** [comment]
Il me semble que initialiement, quand tu annulais un créneau,tu resterais inscrit sur le créneau tant qu'un autre membre ne l'avait pas repris. C'est créneau était mis en avant avec cette légende 'benevole en galère'

Ce n'est plus utilisé à l'elefan depuis des années et le code a du se perdre au fur et à mesure des releases. Je ne sais pas si c'est quelque chose que l'on veut remettre en avant ? Ex, un nouveau s'est inscrit sur le créneau parce qu'un autre membre était deja inscrit. Cet autre membre annule le créneau, et le nouveau se retrouve tout seul.

**Comment by ctmareil** [comment]
Ce n'est pas utilisé à POP la Coop. Ca me semble absolument pas prioritaire et trop sophistiqué pour nos coopérateurs.

**Comment by petitalb** [comment]
ok donc je pense que l'objectif de cette issue est d'enlever la légende (vu que ca n'existe plus en prod) et on peut ouvrir une autre issue pour tracer cette idée si un jour on veut la remettre en place.
