### ISSUE TITLE
Activation d'un nouvel adhérent

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#993]
En version 1.45.1, l'application demande 2 fois le mot de passe à l'activation d'un nouvel adhérent

**En tant qu'Administrateur**
1. OK : Création d'un nouvel adhérent (>Administration > Adhésion / Nuvelle Adhésion >  Nouvelle Adhésion
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/78c19cf0-3721-4605-b655-f83b5821b767)

2. OK : ACTIVER LE COMPTE DE TEST2 (sauf que ce n'est pas une réinitialisation de mot de passe)

![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/98519929-b647-499b-9f4c-9394d1a3af2b)
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/6b5e7389-38b8-47d7-b071-ae9f37c7d640)

**En tant que TEST2**
1. Click sur le lien de l'email
2. Affichage écran changement de mot de passe 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/0fa91b33-d20a-4e7d-9569-377ebd31268d)
3. Entrée d'un nouveau mot de passe et Click sur MODIFIER LE MOT DE PASSE
4. Affichage du message d'accueil et demande d'initialiser le mot de passe 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/276923bb-f57b-42f4-8216-093ae0eb5ab7)

**Comment by raphodn** [comment]
Avec Albin on a un peu mis le nez ce weekend dans le parcours d'adhésion justement.

Normalement au moment de l'adhésion le nouveau membre recoit déjà un e-mail. Tu as cliqué sur "Activer le compte c'est cela" ? Ca a envoyé un second e-mail du coup ? :thinking:

**Comment by ctmareil** [comment]
Effectivement : j'ai cliqué sur Activer le compte et du coup j'ai le double message

Je viens de refaire le test sans cliquer et j'ai effectivement un message 
Bonjour ttest3,
Pour valider ton compte membre, merci de cliquer sur (Lien)

Donc c'est ok. JE ferme
