### ISSUE TITLE
Premier créneau d'un nouvel adhérent

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#994]
En version 1.45.1 : des erreurs dans le positionnement du premier cycle 
Date du jour : 18 septembre, Date de création de l'adhérent : 15 septembre

**Connecté en tant qu'adhérent Testchris pour réserver son premier créneau**
1. OK : Ecran d'accueil :
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/1be0b9f3-9e2f-4e54-a106-56583ca7bfa8)
2. OK : Liste des créneaux disponibles (message Ton cycle actuel commence le 18 Septembre : KO)
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/61de547d-c2b1-4c2a-9fb4-dcc927981639)
3.OK : Sélection d'un créneau disponible le JEUDI 21 septembre
4.KO : "on cycle actuel se termine le mercredi 20 septembre" 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/fd271a90-1e97-4085-9c14-81a569828aa6)
5. KO : Tentative de réservation d'un deuxième créneau et affichage 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/411a0309-a142-429b-8e0f-2f9e18579f29)
6: KO : Créneau réservé mis dans le cycle suivant et premiers créneaux réservables le 21 septembre
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/7bfa3b16-f1b4-4792-b144-1cc0a8b78c4f)

**Comment by raphodn** [comment]
Doublon avec l'issue #963
