### ISSUE TITLE
Ajout du numéro de badge impossible 

### ISSUE THREAD

**Issue by ctmareil** [elefan-grenoble/gestion-compte#995]
en version 1.45.1, l'ajout d'un numéro de badge est impossible ni pas l'adhérent ni par l'administrateur 
![image](https://github.com/elefan-grenoble/gestion-compte/assets/49201885/fe3b5a97-ddc9-424f-9843-5ac11336f6f8)

**Comment by raphodn** [comment]
Salut Christophe, tu peux détailler ? Tu essaies de mettre quel numéro de badge par exemple ? Il y a une erreur d'affichée ?

**Comment by ctmareil** [comment]
en 1.45.1 le champs "Code du badge à 13 chiffres" n'est pas modifiable. Toute entrée de données par le clavier est bloquée

**Comment by raphodn** [comment]
Il me semble que dans les versions antérieurs à la 1.45.2, le champ est modifiable mais il faut réussir à le sélectionner en cliquant plusieurs fois entre le label et la ligne du formulaire...

**Comment by ctmareil** [comment]
Ah bah si c'est un champs caché 🤣

Effectivement il faut réussir à le sélectionner ....
